import { test } from '@playwright/test'
import { DocumentExtractionPage } from './document-extraction-page'

const original = Buffer.from(`<?xml version="1.0" encoding="UTF-8"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"><cbc:CustomizationID>urn:cen.eu:en16931:2017</cbc:CustomizationID><cbc:ID>ER-MIXED-E2E</cbc:ID><cbc:IssueDate>2026-07-25</cbc:IssueDate><cbc:InvoiceTypeCode>380</cbc:InvoiceTypeCode><cbc:DocumentCurrencyCode>EUR</cbc:DocumentCurrencyCode><cac:Delivery><cbc:ActualDeliveryDate>2026-07-25</cbc:ActualDeliveryDate></cac:Delivery>
<cac:AccountingSupplierParty><cac:Party><cac:PartyName><cbc:Name>Mixed Credit Supplier GmbH</cbc:Name></cac:PartyName><cac:PostalAddress><cbc:StreetName>A 1</cbc:StreetName><cbc:CityName>Berlin</cbc:CityName><cbc:PostalZone>10115</cbc:PostalZone><cac:Country><cbc:IdentificationCode>DE</cbc:IdentificationCode></cac:Country></cac:PostalAddress><cac:PartyTaxScheme><cbc:CompanyID>DE123456789</cbc:CompanyID><cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme></cac:PartyTaxScheme></cac:Party></cac:AccountingSupplierParty>
<cac:AccountingCustomerParty><cac:Party><cac:PartyName><cbc:Name>Buyer GmbH</cbc:Name></cac:PartyName><cac:PostalAddress><cbc:StreetName>B 2</cbc:StreetName><cbc:CityName>Berlin</cbc:CityName><cbc:PostalZone>10115</cbc:PostalZone><cac:Country><cbc:IdentificationCode>DE</cbc:IdentificationCode></cac:Country></cac:PostalAddress></cac:Party></cac:AccountingCustomerParty>
<cac:TaxTotal><cbc:TaxAmount currencyID="EUR">26.00</cbc:TaxAmount><cac:TaxSubtotal><cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount><cbc:TaxAmount currencyID="EUR">7.00</cbc:TaxAmount><cac:TaxCategory><cbc:ID>S</cbc:ID><cbc:Percent>7</cbc:Percent><cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme></cac:TaxCategory></cac:TaxSubtotal><cac:TaxSubtotal><cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount><cbc:TaxAmount currencyID="EUR">19.00</cbc:TaxAmount><cac:TaxCategory><cbc:ID>S</cbc:ID><cbc:Percent>19</cbc:Percent><cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme></cac:TaxCategory></cac:TaxSubtotal></cac:TaxTotal><cac:LegalMonetaryTotal><cbc:LineExtensionAmount currencyID="EUR">200.00</cbc:LineExtensionAmount><cbc:TaxExclusiveAmount currencyID="EUR">200.00</cbc:TaxExclusiveAmount><cbc:TaxInclusiveAmount currencyID="EUR">226.00</cbc:TaxInclusiveAmount><cbc:PayableAmount currencyID="EUR">226.00</cbc:PayableAmount></cac:LegalMonetaryTotal>
<cac:InvoiceLine><cbc:ID>1</cbc:ID><cbc:InvoicedQuantity unitCode="C62">1</cbc:InvoicedQuantity><cbc:LineExtensionAmount currencyID="EUR">100.00</cbc:LineExtensionAmount><cac:Item><cbc:Name>Books</cbc:Name><cac:ClassifiedTaxCategory><cbc:ID>S</cbc:ID><cbc:Percent>7</cbc:Percent><cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme></cac:ClassifiedTaxCategory></cac:Item><cac:Price><cbc:PriceAmount currencyID="EUR">100.00</cbc:PriceAmount></cac:Price></cac:InvoiceLine><cac:InvoiceLine><cbc:ID>2</cbc:ID><cbc:InvoicedQuantity unitCode="C62">1</cbc:InvoicedQuantity><cbc:LineExtensionAmount currencyID="EUR">100.00</cbc:LineExtensionAmount><cac:Item><cbc:Name>Service</cbc:Name><cac:ClassifiedTaxCategory><cbc:ID>S</cbc:ID><cbc:Percent>19</cbc:Percent><cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme></cac:ClassifiedTaxCategory></cac:Item><cac:Price><cbc:PriceAmount currencyID="EUR">100.00</cbc:PriceAmount></cac:Price></cac:InvoiceLine></Invoice>`)
const credit = Buffer.from(new TextDecoder().decode(original).replace('<Invoice xmlns=', '<CreditNote xmlns=').replace('</Invoice>', '</CreditNote>').replace('schema:xsd:Invoice-2', 'schema:xsd:CreditNote-2').replace('<cbc:ID>ER-MIXED-E2E</cbc:ID>', '<cbc:ID>GS-MIXED-E2E</cbc:ID><cac:BillingReference><cac:InvoiceDocumentReference><cbc:ID>ER-MIXED-E2E</cbc:ID></cac:InvoiceDocumentReference></cac:BillingReference>').replace('<cbc:InvoiceTypeCode>380</cbc:InvoiceTypeCode>', '<cbc:CreditNoteTypeCode>381</cbc:CreditNoteTypeCode>').replaceAll('InvoiceLine', 'CreditNoteLine').replaceAll('InvoicedQuantity', 'CreditedQuantity'))

test.describe('real incoming supplier credit-note journey', () => {
  test.setTimeout(90_000)
  test('Given a posted domestic mixed-rate UBL payable, when its exact supplier credit is uploaded and explicitly dated, then reversal VAT, debit credit, netting and evidence survive reload', async ({ page }) => {
    const workspace = new DocumentExtractionPage(page); const unique = Date.now()
    await workspace.signUp(`Supplier credit ${unique}`, `supplier-credit-${unique}@example.test`, 'playwright-password-2026')
    await workspace.uploadReviewAndPostStructured({ name: 'original-supplier.xml', mimeType: 'application/xml', buffer: original }, 'ER-MIXED-E2E', '200.00', '26.00')
    await workspace.uploadAndPostSupplierCredit(credit)
    await workspace.proveSupplierCreditAfterReload()
  })
})
