import { beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ user: vi.fn(), ensure: vi.fn(), post: vi.fn() }))
vi.mock('server-only', () => ({})); vi.mock('@/server/authentication', () => ({ getCurrentUser: mocks.user })); vi.mock('@/server/ledger', () => ({ ensureLedger: mocks.ensure })); vi.mock('@/server/fixedAssetsRepository', () => ({ postFixedAssetDepreciation: mocks.post, FixedAssetError: class FixedAssetError extends Error { constructor(message: string, readonly status = 400) { super(message) } } }))
import { POST } from './route'

describe('fixed-asset depreciation API', () => {
  beforeEach(() => vi.clearAllMocks())
  it('Given an accountant in an assigned company, when depreciation is posted, then tenant and human actor remain distinct', async () => { mocks.user.mockResolvedValue({ id: 'tenant-a', actorId: 'accountant-a', role: 'ACCOUNTANT' }); mocks.post.mockResolvedValue({ event: { id: 'event-a' } }); const input = { period: '2026-01', reason: 'Approved' }; const response = await POST(new Request('http://localhost/api/fixed-assets/asset-a/depreciation', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }), { params: Promise.resolve({ id: 'asset-a' }) }); expect(response.status).toBe(200); expect(mocks.ensure).toHaveBeenCalledWith('tenant-a', 2026); expect(mocks.post).toHaveBeenCalledWith('tenant-a', 'accountant-a', 'asset-a', '2026-01', 'Approved') })
  it('Given read-only access, when depreciation is attempted, then it is forbidden before ledger or repository mutation', async () => { mocks.user.mockResolvedValue({ id: 'tenant-a', actorId: 'viewer-a', role: 'READ_ONLY' }); const response = await POST(new Request('http://localhost/api/fixed-assets/asset-a/depreciation', { method: 'POST', body: '{invalid' }), { params: Promise.resolve({ id: 'asset-a' }) }); expect(response.status).toBe(403); expect(mocks.ensure).not.toHaveBeenCalled(); expect(mocks.post).not.toHaveBeenCalled() })
})
