import { describe, expect, it } from 'vitest'
import { AccountingValidationError } from './doubleEntry'
import { consumeDatevRecordBudget, inferDatevAccountCategory, parseCsv, parseDatevFiles } from './datev'

const bookingHeaders = ['Umsatz (ohne Soll/Haben-Kz)', 'Soll/Haben-Kennzeichen', 'Konto', 'Gegenkonto (ohne BU-Schlüssel)', 'BU-Schlüssel', 'Belegdatum', 'Belegfeld 1', 'Buchungstext', 'Buchungs GUID']

describe('DATEV EXTF parser', () => {
  it('parses quoted semicolon CSV and escaped quotes', () => {
    expect(parseCsv('a;"b;c";"d""e"\r\n')).toEqual([['a', 'b;c', 'd"e']])
    expect(() => parseCsv('a\nb\nc\n', 2)).toThrow(/syntaktisch ungültig/)
    expect(consumeDatevRecordBudget(10, 4)).toBe(6)
    expect(() => consumeDatevRecordBudget(2, 3)).toThrow(/höchstens 1500 CSV-Datensätze/)
  })

  it('imports booking rows and debtor/creditor names without fixture data', () => {
    const master = datevFile('master.csv', 'Debitoren/Kreditoren', ['Konto', 'Name (Adressattyp Unternehmen)'], [['10001', 'Kundin Ä']])
    const bookings = datevFile('bookings.csv', 'Buchungsstapel', bookingHeaders, [
      ['12,34', 'S', '10001', '8400', '3', '1707', 'RE-1', 'Erlös; Inland', 'guid-1'],
      ['5,00', 'H', '4970', '1200', '', '1807', '', '', 'guid-2'],
    ])
    const result = parseDatevFiles([master, bookings])
    expect(result.accounts).toContainEqual({ number: 10001, name: 'Kundin Ä', category: 'ASSET' })
    expect(result.chart).toBe('SKR03')
    expect(result.bookings).toMatchObject([
      { bookingDate: '2025-07-17', amountCents: 1234, side: 'S', documentNumber: 'RE-1', taxCode: '3', identity: 'guid-1' },
      { bookingDate: '2025-07-18', amountCents: 500, side: 'H', description: 'DATEV-Import' },
    ])
  })

  it('requires debtor/creditor master rows to use personal accounts', () => {
    const invalid = datevFile('master.csv', 'Debitoren/Kreditoren', ['Konto', 'Name (Adressattyp Unternehmen)'], [['1200', 'Not a customer']])
    const booking = datevFile('booking.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'x', '']])
    expect(() => parseDatevFiles([invalid, booking])).toThrow(/Debitoren\/Kreditoren müssen Personenkonten sein/)
  })

  it('bounds and sanitizes persisted DATEV text fields', () => {
    const longText = datevFile('long.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'x'.repeat(61), '']])
    expect(() => parseDatevFiles([longText])).toThrow(/Buchungstext darf höchstens 60 Zeichen/)
    const control = datevFile('control.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'bad\ttext', '']])
    expect(() => parseDatevFiles([control])).toThrow(/Buchungstext enthält unzulässige Steuerzeichen/)
  })

  it('accepts booking exports generated by DATEV with a DTVF marker', () => {
    const file = datevFile('datev.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'x', '']])
    file.bytes = new TextEncoder().encode(new TextDecoder().decode(file.bytes).replace(/^EXTF/, 'DTVF'))
    expect(parseDatevFiles([file]).bookings).toHaveLength(1)
  })

  it('rejects unsupported files, malformed amounts and non-calendar fiscal years', () => {
    expect(() => parseDatevFiles([])).toThrow(AccountingValidationError)
    const malformed = datevFile('bad.csv', 'Buchungsstapel', bookingHeaders, [['12.34', 'S', '1200', '8400', '', '1707', '1', 'x', '']])
    expect(() => parseDatevFiles([malformed])).toThrow(/Ungültiger Umsatz/)
    const shifted = datevFile('shifted.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'x', '']], '20250701', '20260630')
    expect(() => parseDatevFiles([shifted])).toThrow(/Abweichende Wirtschaftsjahre/)
  })

  it('rejects a header-only booking batch', () => {
    const empty = datevFile('empty.csv', 'Buchungsstapel', bookingHeaders, [])
    expect(() => parseDatevFiles([empty])).toThrow(/enthält keine Buchungen/)
  })

  it('ignores unrelated valid EXTF formats selected with the export folder', () => {
    const booking = datevFile('booking.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'x', '']])
    const accountLabels = datevFile(
      'labels.csv',
      'Kontenbeschriftungen',
      ['Konto', 'Kontenbeschriftung'],
      Array.from({ length: 1_501 }, (_, index) => [String(1200 + index), `Konto ${index}`]),
    )
    expect(parseDatevFiles([accountLabels, booking]).bookings).toHaveLength(1)
  })

  it('rejects files from different DATEV clients', () => {
    const first = datevFile('first.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'x', '']])
    const second = datevFile('second.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '', '1807', '2', 'y', '']], '20250101', '20250101', '20251231', '03', 'export', '4', '2')
    expect(() => parseDatevFiles([first, second])).toThrow(/unterschiedlichen Beratern oder Mandanten/)
  })

  it('accepts partial-period exports using the separate fiscal-year start', () => {
    const monthly = datevFile('july.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'x', '']], '20250101', '20250701', '20250731')
    expect(parseDatevFiles([monthly]).bookings[0].bookingDate).toBe('2025-07-17')
  })

  it('rejects booking dates outside the batch period', () => {
    const inconsistent = datevFile('july.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '', '0101', '1', 'x', '']], '20250101', '20250701', '20250731')
    expect(() => parseDatevFiles([inconsistent])).toThrow(/Belegdatum liegt außerhalb/)
  })

  it('uses declared/detected charts and rejects an ambiguous missing chart', () => {
    const skr04 = datevFile('skr04.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1800', '4400', '', '1707', '1', 'x', '']], '20250101', '20250101', '20251231', '04')
    const result = parseDatevFiles([skr04])
    expect(result.chart).toBe('SKR04')
    expect(result.accounts).toContainEqual({ number: 4400, name: 'DATEV-Konto 4400', category: 'REVENUE' })
    const ambiguous = datevFile('unknown.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1000', '2000', '', '1707', '1', 'x', '']], '20250101', '20250101', '20251231', '')
    expect(() => parseDatevFiles([ambiguous])).toThrow(/Sachkontenrahmen fehlt oder ist nicht eindeutig/)
  })

  it('does not claim a durable identity for GUID-less rows', () => {
    const row = ['1,00', 'S', '1200', '8400', '', '1707', '1', 'x', '']
    const first = datevFile('first.csv', 'Buchungsstapel', bookingHeaders, [row], '20250101', '20250101', '20251231', '03', 'export-1')
    const later = datevFile('later.csv', 'Buchungsstapel', bookingHeaders, [row], '20250101', '20250101', '20251231', '03', 'export-2')
    expect(parseDatevFiles([first]).bookings[0].identity).toBeNull()
    expect(parseDatevFiles([later]).bookings[0].identity).toBeNull()
  })

  it('uses EUR base amounts for foreign-currency rows and rejects missing conversion data', () => {
    const headers = [...bookingHeaders, 'WKZ Umsatz', 'Basis-Umsatz', 'WKZ Basis-Umsatz']
    const converted = datevFile('usd.csv', 'Buchungsstapel', headers, [['10,00', 'S', '1200', '8400', '', '1707', '1', 'x', '', 'USD', '9,25', 'EUR']])
    expect(parseDatevFiles([converted]).bookings[0].amountCents).toBe(925)
    const missing = datevFile('usd-missing.csv', 'Buchungsstapel', headers, [['10,00', 'S', '1200', '8400', '', '1707', '1', 'x', '', 'USD', '', '']])
    expect(() => parseDatevFiles([missing])).toThrow(/Fremdwährungsbuchungen benötigen einen EUR-Basisumsatz/)
  })

  it('expands only supported automatic tax keys and adds their tax account', () => {
    const taxed = datevFile('tax.csv', 'Buchungsstapel', bookingHeaders, [['119,00', 'S', '4930', '70001', '0009', '1707', '1', 'x', '']])
    const parsed = parseDatevFiles([taxed])
    expect(parsed.bookings[0].taxCode).toBe('9')
    expect(parsed.bookings[0].automaticTax).toEqual({ kind: 'INPUT', rate: 19, accountNumber: 1576, splitSide: 'ACCOUNT' })
    expect(parsed.accounts).toContainEqual({ number: 1576, name: 'DATEV Vorsteuer 19 %', category: 'ASSET' })
    const unsupported = datevFile('tax-unknown.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '40', '1707', '1', 'x', '']])
    expect(() => parseDatevFiles([unsupported])).toThrow(/Automatik-Steuerschlüssel 40 wird nicht unterstützt/)
    const exempt = datevFile('tax-exempt.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '8000', '1200', '0001', '1707', '2', 'tax exempt', '']])
    const exemptBooking = parseDatevFiles([exempt]).bookings[0]
    expect(exemptBooking.taxCode).toBe('1')
    expect(exemptBooking.automaticTax).toBeUndefined()
  })

  it('recognizes standard automatic and reverse-charge accounts without an explicit BU key', () => {
    const automatic = datevFile('automatic.csv', 'Buchungsstapel', bookingHeaders, [['119,00', 'S', '10001', '8400', '', '1707', '1', 'x', '']])
    expect(parseDatevFiles([automatic]).bookings[0].automaticTax).toEqual({ kind: 'OUTPUT', rate: 19, accountNumber: 1776, splitSide: 'CONTRA' })
    const automaticInput = datevFile('automatic-input.csv', 'Buchungsstapel', bookingHeaders, [['119,00', 'S', '3400', '70001', '', '1707', '2', 'x', '']])
    expect(parseDatevFiles([automaticInput]).bookings[0].automaticTax).toEqual({ kind: 'INPUT', rate: 19, accountNumber: 1576, splitSide: 'ACCOUNT' })
    const reverse = datevFile('reverse.csv', 'Buchungsstapel', bookingHeaders, [['100,00', 'S', '3123', '70001', '', '1707', '2', 'x', '']])
    expect(parseDatevFiles([reverse]).bookings[0].reverseCharge).toEqual({
      rate: 19, inputTaxAccountNumber: 1577, outputTaxAccountNumber: 1787, baseSide: 'ACCOUNT',
    })
  })

  it('rejects an unknown P&L account whose empty-BU tax behavior is ambiguous', () => {
    const unknown = datevFile('unknown-tax.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '4999', '1200', '', '1707', '1', 'x', '']])
    expect(() => parseDatevFiles([unknown])).toThrow(/Steuerverhalten von Konto 4999.*nicht eindeutig/)
  })

  it('preserves explicit normal and Generalumkehr markers', () => {
    const headers = [...bookingHeaders, 'Generalumkehr (GU)']
    const normal = datevFile('normal.csv', 'Buchungsstapel', headers, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'x', '', '0']])
    expect(parseDatevFiles([normal]).bookings[0].side).toBe('S')
    const reversal = datevFile('reversal.csv', 'Buchungsstapel', headers, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'x', '', '1']])
    expect(parseDatevFiles([reversal]).bookings[0]).toMatchObject({ side: 'S', generalReversal: true })
    const invalid = datevFile('invalid-gu.csv', 'Buchungsstapel', headers, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'x', '', '2']])
    expect(() => parseDatevFiles([invalid])).toThrow(/Generalumkehr muss leer, 0 oder 1 sein/)
  })

  it('rejects cash discounts and account numbers outside the declared length', () => {
    const headers = [...bookingHeaders, 'Skonto']
    const discount = datevFile('discount.csv', 'Buchungsstapel', headers, [['100,00', 'S', '1200', '8400', '', '1707', '1', 'x', '', '5,00']])
    expect(() => parseDatevFiles([discount])).toThrow(/Buchungen mit Skonto/)
    const zero = datevFile('zero.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '0', '8400', '', '1707', '1', 'x', '']])
    expect(() => parseDatevFiles([zero])).toThrow(/Ungültige DATEV-Kontonummer/)
    const oversized = datevFile('oversized.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '123456', '8400', '', '1707', '1', 'x', '']])
    expect(() => parseDatevFiles([oversized])).toThrow(/Ungültige DATEV-Kontonummer/)
  })

  it('rejects tax automation outside the modeled tax period and service-date semantics', () => {
    const historical = datevFile('historical.csv', 'Buchungsstapel', bookingHeaders, [['119,00', 'S', '10001', '8400', '', '1707', '1', 'x', '']], '20200101', '20200101', '20201231')
    expect(() => parseDatevFiles([historical])).toThrow(/nur für 2021 bis 2026/)
    const headers = [...bookingHeaders, 'Leistungsdatum']
    const serviceDate = datevFile('service-date.csv', 'Buchungsstapel', headers, [['119,00', 'S', '10001', '8400', '', '1707', '1', 'x', '', '20250701']])
    expect(() => parseDatevFiles([serviceDate])).toThrow(/Buchungen mit Leistungsdatum/)
  })

  it('rejects unsupported advance-payment semantics', () => {
    const headers = [...bookingHeaders, 'Buchungstyp', 'USt-Schlüssel (Anzahlungen)']
    const advance = datevFile('advance.csv', 'Buchungsstapel', headers, [['119,00', 'S', '1200', '8400', '', '1707', '1', 'advance', '', '1', '3']])
    expect(() => parseDatevFiles([advance])).toThrow(/Anzahlungsbuchungen werden noch nicht unterstützt/)
  })

  it('requires master and booking files to use the same account length', () => {
    const master = datevFile('master.csv', 'Debitoren/Kreditoren', ['Konto', 'Name (Adressattyp Unternehmen)'], [['10001', 'Customer']], '20250101', '20250101', '20251231', '03', 'export', '5')
    const booking = datevFile('booking.csv', 'Buchungsstapel', bookingHeaders, [['1,00', 'S', '1200', '8400', '', '1707', '1', 'x', '']])
    expect(() => parseDatevFiles([master, booking])).toThrow(/Sachkontenlänge 4/)
  })

  it('infers standard DATEV account classes', () => {
    expect(inferDatevAccountCategory(500, 'SKR03')).toBe('ASSET')
    expect(inferDatevAccountCategory(730, 'SKR03')).toBe('LIABILITY')
    expect(inferDatevAccountCategory(800, 'SKR03')).toBe('EQUITY')
    expect(inferDatevAccountCategory(855, 'SKR03')).toBe('EQUITY')
    expect(() => inferDatevAccountCategory(801, 'SKR03')).toThrow(/keiner.*sicher zugeordnet/)
    expect(inferDatevAccountCategory(1200, 'SKR03')).toBe('ASSET')
    expect(inferDatevAccountCategory(1600, 'SKR03')).toBe('LIABILITY')
    expect(inferDatevAccountCategory(2900, 'SKR03')).toBe('EQUITY')
    expect(inferDatevAccountCategory(1900, 'SKR03')).toBe('EQUITY')
    expect(inferDatevAccountCategory(4930, 'SKR03')).toBe('EXPENSE')
    expect(inferDatevAccountCategory(8400, 'SKR03')).toBe('REVENUE')
    expect(inferDatevAccountCategory(70001, 'SKR03')).toBe('LIABILITY')
    expect(inferDatevAccountCategory(4400, 'SKR04')).toBe('REVENUE')
    expect(inferDatevAccountCategory(6815, 'SKR04')).toBe('EXPENSE')
    expect(inferDatevAccountCategory(84000, 'SKR03', 5)).toBe('REVENUE')
    expect(() => inferDatevAccountCategory(7000, 'SKR04')).toThrow(/keiner.*sicher zugeordnet/)
  })
})

function datevFile(name: string, format: string, headers: string[], rows: string[][], fiscalStart = '20250101', periodStart = fiscalStart, periodEnd = '20251231', chart = '03', generated = 'export-1', accountLength = '4', client = '1') {
  const metadata = ['EXTF', '700', '21', format, '13', generated, '', 'BH', '', '', '1', client, fiscalStart, accountLength, periodStart, periodEnd, '', '', '', '', '', 'EUR', '', '', '', '', chart, '']
  const text = [metadata, headers, ...rows].map(row => row.map(csvCell).join(';')).join('\r\n')
  return { name, bytes: new TextEncoder().encode(text) }
}

function csvCell(value: string) { return value.includes(';') || value.includes('"') ? `"${value.replaceAll('"', '""')}"` : value }
