import { createHash } from 'node:crypto'
import { canonicalJson } from './auditExport'
import { hasDenseNonblankStrings, hasDenseOwnElements } from './validation'

export type CompanySize = 'MICRO' | 'SMALL' | 'MEDIUM' | 'LARGE'
export type IncomeStatementMethod = 'GKV' | 'UKV'
export interface AnnualAccountLine { code: string; label: string; amountCents: number; comparativeCents: number; accountIds: readonly string[] }
export interface AnnualCompanyProfile { tenantId: string; legalName: string; legalForm: string; registerCourt: string; registerNumber: string; registeredOffice: string; size: CompanySize; currency: 'EUR'; language: 'de' }
export interface AnnualPackageInput { profile: AnnualCompanyProfile; fiscalYear: number; previousFiscalYear: number; previousFiscalPeriodStart: string; previousFiscalPeriodEnd: string; previousFiscalPeriodId: string; fiscalPeriodStart: string; fiscalPeriodEnd: string; fiscalTimeZone: string; method: IncomeStatementMethod; balanceSheet: readonly AnnualAccountLine[]; incomeStatement: readonly AnnualAccountLine[]; policies: readonly string[]; notes: readonly string[]; managementReport?: string; otherReports?: readonly string[]; checks: { nonOffsetting: boolean; accrual: boolean; provisions: boolean; valuation: boolean; continuity: boolean }; preparedBy: string; preparedAt: string }
export interface Approval { approvedBy: readonly string[]; approvedAt: string; establishedAt: string; signatures: readonly { signer: string; role: string; signedAt: string }[] }
export interface AnnualAccountsPackage { id: string; version: number; status: 'PREPARED' | 'APPROVED' | 'SUPERSEDED'; immutablePayload: string; checksum: string; approval?: Approval; supersedesId?: string }
export interface AnnualApprovalAuthority { readonly __annualApprovalAuthority: unique symbol }
export interface AnnualApprovalStateAuthenticator { keyId: string; sign(payload: string): string; verify(payload: string, signature: string, keyId: string): boolean }
export interface AnnualApprovalRevisionStore { currentRevision(keyId: string): number; commitSnapshot(keyId: string, expectedRevision: number, snapshot: AnnualApprovalStateSnapshot): boolean }
export interface AnnualApprovalStateSnapshot { version: 1; revision: number; packages: readonly AnnualAccountsPackage[]; activePackageIds: readonly string[]; authenticity: { keyId: string; signature: string } }
interface AnnualApprovalState { revision: number; packages: Map<string, AnnualAccountsPackage>; activeByChain: Map<string, string>; packageByChainVersion: Map<string, string> }
const annualApprovalStores = new WeakMap<object, AnnualApprovalState>()
export function createAnnualApprovalAuthority(snapshot?: AnnualApprovalStateSnapshot, authenticator?: AnnualApprovalStateAuthenticator, revisionStore?: AnnualApprovalRevisionStore): AnnualApprovalAuthority { const authority = Object.freeze(Object.create(null)) as AnnualApprovalAuthority; annualApprovalStores.set(authority, snapshot === undefined ? emptyAnnualApprovalState() : hydrateAnnualApprovalState(authenticateAnnualApprovalState(snapshot, authenticator, revisionStore))); return authority }
export function exportAnnualApprovalState(authority: AnnualApprovalAuthority, authenticator: AnnualApprovalStateAuthenticator, revisionStore: AnnualApprovalRevisionStore): AnnualApprovalStateSnapshot { const state = requireAnnualApprovalStore(authority); const adapter = captureAnnualStateAuthenticator(authenticator, 'sign'); const revisions = captureAnnualRevisionStore(revisionStore); const revision = state.revision + 1; if (!Number.isSafeInteger(revision)) throw new Error('Annual approval state revision exceeds safe integer limits.'); const payload = { version: 1 as const, revision, packages: [...state.packages.values()].sort((left, right) => left.id < right.id ? -1 : left.id > right.id ? 1 : 0).map(pkg => structuredClone(pkg)), activePackageIds: [...state.activeByChain.values()].sort() }; const signature = adapter.sign.call(authenticator, canonicalJson(payload)); if (typeof signature !== 'string' || !signature.trim()) throw new Error('Annual approval state authenticator returned a blank signature.'); const snapshot: AnnualApprovalStateSnapshot = { ...payload, authenticity: { keyId: adapter.keyId, signature } }; if (revisions.commitSnapshot.call(revisionStore, adapter.keyId, state.revision, snapshot) !== true) throw new Error('Annual approval state snapshot commit was rejected as stale.'); state.revision = revision; return deepFreeze(snapshot) }

export const MICRO_BALANCE_SHEET_ORDER = ['A.ASSETS', 'A.FIXED', 'A.CURRENT', 'A.PREPAID', 'A.DEFERRED_TAX', 'A.PENSION_DIFFERENCE', 'B.EQUITY_LIABILITIES', 'B.EQUITY', 'B.PROVISIONS', 'B.LIABILITIES', 'B.DEFERRED', 'B.DEFERRED_TAX'] as const
export const SMALL_BALANCE_SHEET_ORDER = ['A.ASSETS', 'A.FIXED', 'A.INTANGIBLE', 'A.TANGIBLE', 'A.FINANCIAL', 'A.CURRENT', 'A.INVENTORIES', 'A.RECEIVABLES', 'A.SECURITIES', 'A.CASH', 'A.PREPAID', 'A.DEFERRED_TAX', 'A.PENSION_DIFFERENCE', 'B.EQUITY_LIABILITIES', 'B.EQUITY', 'B.SUBSCRIBED_CAPITAL', 'B.CAPITAL_RESERVE', 'B.REVENUE_RESERVES', 'B.CARRYFORWARD', 'B.NET_INCOME', 'B.PROVISIONS', 'B.LIABILITIES', 'B.DEFERRED', 'B.DEFERRED_TAX'] as const
export const BALANCE_SHEET_ORDER = ['A.ASSETS', 'A.FIXED', 'A.INTANGIBLE', 'A.INTANGIBLE_RIGHTS', 'A.GOODWILL', 'A.INTANGIBLE_ADVANCES', 'A.TANGIBLE', 'A.LAND_BUILDINGS', 'A.TECHNICAL_MACHINERY', 'A.OTHER_EQUIPMENT', 'A.TANGIBLE_ADVANCES', 'A.FINANCIAL', 'A.AFFILIATED_SHARES', 'A.AFFILIATED_LOANS', 'A.PARTICIPATIONS', 'A.PARTICIPATION_LOANS', 'A.INVESTMENTS', 'A.OTHER_LOANS', 'A.CURRENT', 'A.INVENTORIES', 'A.RAW_MATERIALS', 'A.WIP', 'A.FINISHED_GOODS', 'A.INVENTORY_ADVANCES', 'A.RECEIVABLES', 'A.TRADE_RECEIVABLES', 'A.AFFILIATED_RECEIVABLES', 'A.PARTICIPATION_RECEIVABLES', 'A.OTHER_RECEIVABLES', 'A.SECURITIES', 'A.AFFILIATED_SECURITIES', 'A.OTHER_SECURITIES', 'A.CASH', 'A.PREPAID', 'A.DEFERRED_TAX', 'A.PENSION_DIFFERENCE', 'B.EQUITY_LIABILITIES', 'B.EQUITY', 'B.SUBSCRIBED_CAPITAL', 'B.CAPITAL_RESERVE', 'B.REVENUE_RESERVES', 'B.LEGAL_RESERVE', 'B.TREASURY_RESERVE', 'B.STATUTORY_RESERVES', 'B.OTHER_RESERVES', 'B.CARRYFORWARD', 'B.NET_INCOME', 'B.PROVISIONS', 'B.PENSION_PROVISIONS', 'B.TAX_PROVISIONS', 'B.OTHER_PROVISIONS', 'B.LIABILITIES', 'B.BONDS', 'B.BANK_LIABILITIES', 'B.ADVANCES', 'B.TRADE_LIABILITIES', 'B.BILLS', 'B.AFFILIATED_LIABILITIES', 'B.PARTICIPATION_LIABILITIES', 'B.OTHER_LIABILITIES', 'B.DEFERRED', 'B.DEFERRED_TAX'] as const
export const GKV_ORDER = ['REVENUE', 'INVENTORY_CHANGE', 'OWN_WORK', 'OTHER_INCOME', 'MATERIAL_RAW', 'MATERIAL_SERVICES', 'GROSS_PROFIT', 'PERSONNEL_WAGES', 'PERSONNEL_SOCIAL', 'DEPRECIATION_FIXED', 'DEPRECIATION_CURRENT', 'OTHER_EXPENSE', 'PARTICIPATION_INCOME', 'AFFILIATED_INCOME', 'INTEREST_INCOME', 'FINANCIAL_DEPRECIATION', 'INTEREST_EXPENSE', 'INCOME_TAX', 'RESULT_AFTER_TAX', 'OTHER_TAX', 'NET_INCOME'] as const
export const UKV_ORDER = ['REVENUE', 'COST_OF_SALES', 'GROSS_SALES_PROFIT', 'DISTRIBUTION', 'ADMINISTRATION', 'OTHER_INCOME', 'OTHER_EXPENSE', 'PARTICIPATION_INCOME', 'AFFILIATED_INCOME', 'INTEREST_INCOME', 'FINANCIAL_DEPRECIATION', 'INTEREST_EXPENSE', 'INCOME_TAX', 'RESULT_AFTER_TAX', 'OTHER_TAX', 'NET_INCOME'] as const
export const COMPACT_UKV_ORDER = ['GROSS_PROFIT_RELIEF', 'DISTRIBUTION', 'ADMINISTRATION', 'OTHER_EXPENSE', 'PARTICIPATION_INCOME', 'AFFILIATED_INCOME', 'INTEREST_INCOME', 'FINANCIAL_DEPRECIATION', 'INTEREST_EXPENSE', 'INCOME_TAX', 'RESULT_AFTER_TAX', 'OTHER_TAX', 'NET_INCOME'] as const
const GKV_REPLACED_CODES = ['REVENUE', 'INVENTORY_CHANGE', 'OWN_WORK', 'OTHER_INCOME', 'MATERIAL_RAW', 'MATERIAL_SERVICES'] as const
const DETAILED_GKV_ORDER = GKV_ORDER.filter(code => code !== 'GROSS_PROFIT')
const COMPACT_GKV_ORDER = GKV_ORDER.filter(code => code === 'GROSS_PROFIT' || !GKV_REPLACED_CODES.includes(code as typeof GKV_REPLACED_CODES[number]))
const UKV_REPLACED_CODES = ['REVENUE', 'COST_OF_SALES', 'GROSS_SALES_PROFIT', 'OTHER_INCOME'] as const
const DETAILED_UKV_ORDER = UKV_ORDER

export function validateAnnualAccounts(input: AnnualPackageInput): string[] {
  const issues: string[] = []
  if (!isRecord(input)) return ['Annual accounts input must be a structured object.']
  try { input = captureAnnualInput(input) } catch { return ['Annual accounts input contains malformed runtime fields or collections.'] }
  if (!hasAnnualTraversalShape(input as unknown as Record<string, unknown>)) return ['Annual accounts input contains malformed runtime fields or collections.']
  const usesCompactGkv = input.method === 'GKV' && input.incomeStatement.some(line => line.code === 'GROSS_PROFIT'); const usesCompactUkv = input.method === 'UKV' && input.incomeStatement.some(line => line.code === 'GROSS_PROFIT_RELIEF'); const incomeOrder = input.method === 'GKV' ? (usesCompactGkv ? COMPACT_GKV_ORDER : DETAILED_GKV_ORDER) : usesCompactUkv ? COMPACT_UKV_ORDER : DETAILED_UKV_ORDER
  if (!['GKV', 'UKV'].includes(input.method) || !['MICRO', 'SMALL', 'MEDIUM', 'LARGE'].includes(input.profile?.size) || input.profile?.currency !== 'EUR' || input.profile?.language !== 'de') issues.push('Annual package contains an unsupported method or rule-driving profile enum.')
  if (!Number.isSafeInteger(input.fiscalYear) || !Number.isSafeInteger(input.previousFiscalYear)) issues.push('Fiscal years must be safe integers.')
  const validPeriod = validDateOnly(input.fiscalPeriodStart) && validDateOnly(input.fiscalPeriodEnd) && input.fiscalPeriodStart <= input.fiscalPeriodEnd
  if (!validPeriod) issues.push('Authoritative fiscal period is invalid or reversed.')
  else {
    const anniversary = new Date(`${input.fiscalPeriodStart}T00:00:00.000Z`); anniversary.setUTCFullYear(anniversary.getUTCFullYear() + 1)
    if (Date.parse(`${input.fiscalPeriodEnd}T00:00:00.000Z`) >= anniversary.getTime()) issues.push('Annual fiscal period may not exceed twelve months.')
    if (input.fiscalYear !== Number(input.fiscalPeriodEnd.slice(0, 4))) issues.push('Fiscal year must use the authoritative period-end year naming convention.')
  }
  const previousPeriod = resolvePreviousPeriod(input)
  if (!previousPeriod || !validDateOnly(previousPeriod.start) || !validDateOnly(previousPeriod.end) || previousPeriod.start > previousPeriod.end || periodExceedsTwelveMonths(previousPeriod.start, previousPeriod.end) || nextDate(previousPeriod.end) !== input.fiscalPeriodStart || !previousPeriod.id.trim()) issues.push('Comparative period identity and boundaries must be valid, ordered and contiguous with the current period.')
  else if (input.previousFiscalYear !== Number(previousPeriod.end.slice(0, 4))) issues.push('Previous fiscal year must use the authoritative comparative period-end year naming convention.')
  const allCodes = [...input.balanceSheet, ...input.incomeStatement].map(line => line.code); if (new Set(allCodes).size !== allCodes.length) issues.push('Annual statement line codes must be unique.')
  validateOrder(input.balanceSheet, BALANCE_SHEET_ORDER, 'balance sheet', issues); validateOrder(input.incomeStatement, incomeOrder, 'income statement', issues)
  if (usesCompactGkv && input.incomeStatement.some(line => GKV_REPLACED_CODES.includes(line.code as typeof GKV_REPLACED_CODES[number]))) issues.push('GKV Rohergebnis is an alternative replacement for detailed positions 1-5 and cannot be combined with them.')
  if (usesCompactGkv && input.profile.size === 'LARGE') issues.push('LARGE/GKV annual accounts require the detailed positions 1-5 instead of compact Rohergebnis.')
  const suppliedDetailedUkv = input.incomeStatement.filter(line => UKV_REPLACED_CODES.includes(line.code as typeof UKV_REPLACED_CODES[number])).length
  if (usesCompactUkv && suppliedDetailedUkv > 0) issues.push('UKV Rohergebnis relief is an alternative replacement for detailed positions 1-3 and 6 and cannot be combined with them.')
  if (!usesCompactUkv && input.method === 'UKV' && suppliedDetailedUkv > 0 && suppliedDetailedUkv < UKV_REPLACED_CODES.length) issues.push('Detailed UKV requires the complete revenue, cost-of-sales, gross-sales-profit subtotal and other-income position set.')
  if (usesCompactUkv && input.profile.size === 'LARGE') issues.push('LARGE/UKV annual accounts require detailed positions instead of compact Rohergebnis.')
  const detailed = input.profile.size === 'MEDIUM' || input.profile.size === 'LARGE'
  const requiredBalance = detailed ? BALANCE_SHEET_ORDER : input.profile.size === 'SMALL' ? SMALL_BALANCE_SHEET_ORDER : MICRO_BALANCE_SHEET_ORDER
  const requiredIncome = input.method === 'GKV' ? (usesCompactGkv ? COMPACT_GKV_ORDER : DETAILED_GKV_ORDER) : usesCompactUkv ? COMPACT_UKV_ORDER : DETAILED_UKV_ORDER
  for (const code of requiredBalance) if (!input.balanceSheet.some(line => line.code === code)) issues.push(`Missing ${input.profile.size} balance-sheet line: ${code}`)
  for (const code of requiredIncome) if (!input.incomeStatement.some(line => line.code === code)) issues.push(`Missing ${input.profile.size}/${input.method} income-statement line: ${code}`)
  if (input.profile.currency !== 'EUR' || input.profile.language !== 'de') issues.push('The immutable package must be German and denominated in EUR.')
  if (input.profile.tenantId !== input.profile.tenantId.trim()) issues.push('Company tenant identity must use canonical trimmed form.')
  if (!input.profile.tenantId.trim() || !input.profile.legalName.trim() || !input.profile.legalForm.trim() || !input.profile.registerCourt.trim() || !input.profile.registerNumber.trim() || !input.profile.registeredOffice.trim()) issues.push('Company identity is incomplete.')
  if ([...input.balanceSheet, ...input.incomeStatement].some(line => typeof line.label !== 'string' || !line.label.trim() || !hasDenseNonblankStrings(line.accountIds, true))) issues.push('Statement lines require nonblank labels and an account ID array containing only nonblank IDs.')
  if ([...input.balanceSheet, ...input.incomeStatement].some(line => !Number.isSafeInteger(line.amountCents) || !Number.isSafeInteger(line.comparativeCents))) issues.push('Current and comparative-period statement data is incomplete.')
  if (!hasDenseNonblankStrings(input.policies) || !hasDenseNonblankStrings(input.notes)) issues.push('Accounting policies and notes must contain nonblank entries.')
  if (input.otherReports !== undefined && !hasDenseNonblankStrings(input.otherReports, true)) issues.push('Other annual reports must be a dense array containing only nonblank entries.')
  if ((input.profile.size === 'MEDIUM' || input.profile.size === 'LARGE') && !input.managementReport?.trim()) issues.push('A management report is required for this company size.')
  for (const name of ['nonOffsetting', 'accrual', 'provisions', 'valuation', 'continuity'] as const) if (input.checks?.[name] !== true) issues.push(`Failed annual-accounts check: ${name}`)
  const assetTotals = input.balanceSheet.filter(line => line.code === 'A.ASSETS'); const equityLiabilityTotals = input.balanceSheet.filter(line => line.code === 'B.EQUITY_LIABILITIES')
  if (assetTotals.length !== 1 || equityLiabilityTotals.length !== 1) issues.push('Balance sheet requires exactly one assets total and one equity/liabilities total.')
  else {
    if (assetTotals[0].amountCents !== equityLiabilityTotals[0].amountCents) issues.push('Current-year balance sheet totals do not balance.')
    if (assetTotals[0].comparativeCents !== equityLiabilityTotals[0].comparativeCents) issues.push('Prior-year balance sheet totals do not balance.')
  }
  const incomeTotal = input.incomeStatement.filter(line => line.code === 'NET_INCOME')
  if (incomeTotal.length !== 1) issues.push('Income statement requires exactly one net-income total.')
  if ([...input.balanceSheet, ...input.incomeStatement].every(line => Number.isSafeInteger(line.amountCents) && Number.isSafeInteger(line.comparativeCents))) validateStatementArithmetic(input, issues)
  if (!input.preparedBy.trim() || !validTimestamp(input.preparedAt)) issues.push('Preparer identity and a real preparation timestamp are required.')
  else if (validPeriod) { const exclusiveEnd = fiscalPeriodExclusiveEnd(input.fiscalPeriodEnd, input.fiscalTimeZone); if (exclusiveEnd === null) issues.push('Authoritative fiscal timezone is invalid.'); else if (Date.parse(input.preparedAt) < exclusiveEnd) issues.push('Annual accounts cannot be prepared before the full authoritative fiscal closing day ends.') }
  return issues
}

export function prepareAnnualAccounts(input: AnnualPackageInput, version: number, supersedesId?: string): AnnualAccountsPackage {
  if (!Number.isSafeInteger(version) || version <= 0) throw new Error('Annual package version must be a positive safe integer.')
  if (supersedesId !== undefined && (typeof supersedesId !== 'string' || !supersedesId.trim())) throw new Error('Annual package supersedesId must be a nonblank primitive string when supplied.')
  const capturedInput = captureAnnualInput(input)
  const inputIssues = validateAnnualAccounts(capturedInput); if (inputIssues.length) throw new Error(inputIssues.join('; '))
  const normalizedInput = normalizeAnnualInput(capturedInput)
  const immutablePayload = canonicalJson({ ...normalizedInput, ...(supersedesId !== undefined ? { supersedesId } : {}) }); const checksum = createHash('sha256').update(immutablePayload).digest('hex')
  return { id: `${normalizedInput.profile.tenantId}:${normalizedInput.fiscalPeriodStart}:${normalizedInput.fiscalPeriodEnd}:v${version}:${checksum}`, version, status: 'PREPARED', immutablePayload, checksum, ...(supersedesId ? { supersedesId } : {}) }
}

export function approveAnnualAccounts(pkg: AnnualAccountsPackage, approval: Approval, authority: AnnualApprovalAuthority): AnnualAccountsPackage {
  const state = requireAnnualApprovalStore(authority)
  const packageSnapshot = captureAnnualPackage(pkg)
  const input = verifyAnnualPackage(packageSnapshot)
  if (packageSnapshot.status !== 'PREPARED') throw new Error('Only a prepared annual package can be approved.')
  const approvalSnapshot = captureApproval(approval); validateApproval(approvalSnapshot, input.preparedAt)
  const approved: AnnualAccountsPackage = { id: packageSnapshot.id, version: packageSnapshot.version, status: 'APPROVED', immutablePayload: packageSnapshot.immutablePayload, checksum: packageSnapshot.checksum, ...(packageSnapshot.supersedesId === undefined ? {} : { supersedesId: packageSnapshot.supersedesId }), approval: normalizeApproval(approvalSnapshot) }
  const chain = annualChainKey(input); const chainVersion = canonicalJson([chain, approved.version]); const conflictingId = state.packageByChainVersion.get(chainVersion); if (conflictingId && conflictingId !== approved.id) throw new Error('Trusted annual approval state already contains a different package for this tenant, fiscal period and version.')
  const activeId = state.activeByChain.get(chain); if (!activeId && approved.supersedesId !== undefined) throw new Error('An initial annual package cannot reserve trusted state with an orphan supersession target.'); if (activeId && activeId !== approved.id) { const active = state.packages.get(activeId)!; if (approved.supersedesId !== active.id || approved.version !== active.version + 1) throw new Error('Annual approval must extend the single active tenant and fiscal-period chain sequentially.'); const activeFinalizedAt = approvalFinalizationInstant(active.approval!); const replacementLifecycle = [Date.parse(input.preparedAt), ...approvalLifecycleInstants(approved.approval!)]; if (replacementLifecycle.some(instant => instant <= activeFinalizedAt)) throw new Error('Replacement preparation and approval lifecycle must occur strictly after the superseded package finalization.') }
  const existing = state.packages.get(approved.id); if (existing && canonicalJson(existing) !== canonicalJson(approved)) throw new Error('Trusted annual approval state already contains a different approval for this package identity.')
  state.packages.set(approved.id, structuredClone(approved)); state.packageByChainVersion.set(chainVersion, approved.id); if (!activeId && approved.supersedesId === undefined) state.activeByChain.set(chain, approved.id); return approved
}

export function supersedeAnnualAccounts(previous: AnnualAccountsPackage, replacement: AnnualAccountsPackage, authority: AnnualApprovalAuthority) {
  const state = requireAnnualApprovalStore(authority)
  const previousSnapshot = captureAnnualPackage(previous); const replacementSnapshot = captureAnnualPackage(replacement)
  verifyAnnualPackage(previousSnapshot); verifyAnnualPackage(replacementSnapshot)
  const trustedPrevious = verifyApprovedPackage(previousSnapshot, authority); const trustedReplacement = verifyAttestedApprovedPackage(replacementSnapshot, authority).trusted
  if (trustedReplacement.supersedesId !== trustedPrevious.id || trustedReplacement.version !== trustedPrevious.version + 1) throw new Error('Replacement must explicitly supersede the previous sequential version.')
  const previousInput = JSON.parse(trustedPrevious.immutablePayload) as AnnualPackageInput; const replacementInput = JSON.parse(trustedReplacement.immutablePayload) as AnnualPackageInput
  if (previousInput.profile.tenantId !== replacementInput.profile.tenantId || previousInput.fiscalPeriodStart !== replacementInput.fiscalPeriodStart || previousInput.fiscalPeriodEnd !== replacementInput.fiscalPeriodEnd) throw new Error('Replacement tenant and fiscal period must match the superseded package.')
  const previousFinalizedAt = approvalFinalizationInstant(trustedPrevious.approval!)
  const replacementLifecycle = [Date.parse(replacementInput.preparedAt), ...approvalLifecycleInstants(trustedReplacement.approval!)]
  if (replacementLifecycle.some(instant => instant <= previousFinalizedAt)) throw new Error('Replacement preparation and approval lifecycle must occur strictly after the superseded package finalization.')
  const superseded = { ...trustedPrevious, status: 'SUPERSEDED' as const }; const chain = annualChainKey(previousInput); if (state.activeByChain.get(chain) !== trustedPrevious.id) throw new Error('Superseded annual accounts are not the single active tenant and fiscal-period version.'); state.packages.set(trustedPrevious.id, structuredClone(superseded)); state.activeByChain.set(chain, trustedReplacement.id); return { previous: superseded, replacement: structuredClone(trustedReplacement) }
}

export function createDisclosurePackage(pkg: AnnualAccountsPackage, options: { deadline: string; generatedAt: string; reliefs: readonly string[] }, authority: AnnualApprovalAuthority) {
  const packageSnapshot = captureAnnualPackage(pkg)
  const capturedOptions = captureDisclosureOptions(options)
  verifyAnnualPackage(packageSnapshot)
  const trustedPackage = verifyApprovedPackage(packageSnapshot, authority)
  if (!hasDenseNonblankStrings(capturedOptions.reliefs, true)) throw new Error('Disclosure reliefs must be a dense array containing only nonblank strings.')
  if (!validDateOnly(capturedOptions.deadline) || !validDate(capturedOptions.generatedAt)) throw new Error('Disclosure deadline must be a date-only statutory boundary and generation date must be valid.')
  if (Date.parse(capturedOptions.generatedAt) < approvalFinalizationInstant(trustedPackage.approval!)) throw new Error('Disclosure package cannot be generated before approval, establishment or signatures.')
  const payload = canonicalJson({ destination: 'Unternehmensregister', annualAccountsId: trustedPackage.id, annualAccountsChecksum: trustedPackage.checksum, deadline: capturedOptions.deadline, generatedAt: capturedOptions.generatedAt, reliefs: capturedOptions.reliefs, package: trustedPackage })
  return { status: germanCalendarDate(capturedOptions.generatedAt) > germanCalendarDate(capturedOptions.deadline) ? 'OVERDUE' as const : 'READY' as const, deadline: capturedOptions.deadline, payload, checksum: createHash('sha256').update(payload).digest('hex') }
}

function validateOrder(lines: readonly AnnualAccountLine[], allowed: readonly string[], label: string, issues: string[]) { let last = -1; for (const line of lines) { const index = allowed.indexOf(line.code as never); if (index < 0) issues.push(`Unknown ${label} line: ${line.code}`); else if (index < last) issues.push(`Incorrect prescribed ${label} order.`); else last = index } }
function normalizeAnnualInput(input: AnnualPackageInput): AnnualPackageInput { return { profile: { tenantId: input.profile.tenantId, legalName: input.profile.legalName, legalForm: input.profile.legalForm, registerCourt: input.profile.registerCourt, registerNumber: input.profile.registerNumber, registeredOffice: input.profile.registeredOffice, size: input.profile.size, currency: input.profile.currency, language: input.profile.language }, fiscalYear: input.fiscalYear, previousFiscalYear: input.previousFiscalYear, previousFiscalPeriodStart: input.previousFiscalPeriodStart, previousFiscalPeriodEnd: input.previousFiscalPeriodEnd, previousFiscalPeriodId: input.previousFiscalPeriodId, fiscalPeriodStart: input.fiscalPeriodStart, fiscalPeriodEnd: input.fiscalPeriodEnd, fiscalTimeZone: input.fiscalTimeZone, method: input.method, balanceSheet: input.balanceSheet.map(normalizeAnnualLine), incomeStatement: input.incomeStatement.map(normalizeAnnualLine), policies: [...input.policies], notes: [...input.notes], ...(input.managementReport === undefined ? {} : { managementReport: input.managementReport }), ...(input.otherReports === undefined ? {} : { otherReports: [...input.otherReports] }), checks: { nonOffsetting: input.checks.nonOffsetting, accrual: input.checks.accrual, provisions: input.checks.provisions, valuation: input.checks.valuation, continuity: input.checks.continuity }, preparedBy: input.preparedBy, preparedAt: input.preparedAt } }
function normalizeAnnualLine(line: AnnualAccountLine): AnnualAccountLine { return { code: line.code, label: line.label, amountCents: line.amountCents, comparativeCents: line.comparativeCents, accountIds: [...line.accountIds] } }
function captureAnnualInput(value: unknown): AnnualPackageInput { try { return captureAnnualValue(value) as AnnualPackageInput } catch { throw new Error('Annual accounts input must use inert own enumerable data fields and dense arrays.') } }
function captureAnnualValue(value: unknown): unknown { if (value === null || typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' || value === undefined) return value; if (Array.isArray(value)) { if (!hasDenseOwnElements(value)) return { malformedArray: true }; const snapshot: unknown[] = []; for (let index = 0; index < value.length; index++) snapshot.push(captureAnnualValue(Object.getOwnPropertyDescriptor(value, String(index))!.value)); return snapshot } if (!isRecord(value)) throw new Error('unsupported value'); const snapshot = Object.create(null) as Record<string, unknown>; for (const key of Object.keys(value)) { const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor?.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error('accessor field'); snapshot[key] = captureAnnualValue(descriptor.value) } return snapshot }
function resolvePreviousPeriod(input: AnnualPackageInput) { const supplied = [input.previousFiscalPeriodStart, input.previousFiscalPeriodEnd, input.previousFiscalPeriodId]; return supplied.every(value => typeof value === 'string') ? { start: supplied[0], end: supplied[1], id: supplied[2] } : null }
function nextDate(value: string) { if (!validDateOnly(value)) return ''; const date = new Date(`${value}T00:00:00.000Z`); date.setUTCDate(date.getUTCDate() + 1); return date.toISOString().slice(0, 10) }
function periodExceedsTwelveMonths(start: string, end: string) { const anniversary = new Date(`${start}T00:00:00.000Z`); anniversary.setUTCFullYear(anniversary.getUTCFullYear() + 1); return Date.parse(`${end}T00:00:00.000Z`) >= anniversary.getTime() }
function validateStatementArithmetic(input: AnnualPackageInput, issues: string[]) {
  const values = (lines: readonly AnnualAccountLine[], codes: readonly string[], field: 'amountCents' | 'comparativeCents') => { let total = 0; for (const code of codes) { const line = lines.find(value => value.code === code); if (!line) return null; total += line[field]; if (!Number.isSafeInteger(total)) { issues.push('Annual statement component arithmetic exceeds safe integer limits.'); return null } } return total }
  const check = (lines: readonly AnnualAccountLine[], totalCode: string, componentCodes: readonly string[], label: string) => { const total = lines.find(line => line.code === totalCode); if (!total) return; const suppliedComponents = componentCodes.filter(code => lines.some(line => line.code === code)); if (suppliedComponents.length === 0) return; if (suppliedComponents.length !== componentCodes.length) { issues.push(`${label} optional breakdown must be complete when any component is supplied.`); return } for (const field of ['amountCents', 'comparativeCents'] as const) { const componentTotal = values(lines, componentCodes, field); if (componentTotal !== null && total[field] !== componentTotal) issues.push(`${label} components do not reconcile for ${field === 'amountCents' ? 'current' : 'comparative'} period.`) } }
  check(input.balanceSheet, 'A.ASSETS', ['A.FIXED', 'A.CURRENT', 'A.PREPAID', 'A.DEFERRED_TAX', 'A.PENSION_DIFFERENCE'], 'Asset total')
  check(input.balanceSheet, 'A.FIXED', ['A.INTANGIBLE', 'A.TANGIBLE', 'A.FINANCIAL'], 'Fixed-asset total')
  check(input.balanceSheet, 'A.INTANGIBLE', ['A.INTANGIBLE_RIGHTS', 'A.GOODWILL', 'A.INTANGIBLE_ADVANCES'], 'Intangible-asset total')
  check(input.balanceSheet, 'A.TANGIBLE', ['A.LAND_BUILDINGS', 'A.TECHNICAL_MACHINERY', 'A.OTHER_EQUIPMENT', 'A.TANGIBLE_ADVANCES'], 'Tangible-asset total')
  check(input.balanceSheet, 'A.FINANCIAL', ['A.AFFILIATED_SHARES', 'A.AFFILIATED_LOANS', 'A.PARTICIPATIONS', 'A.PARTICIPATION_LOANS', 'A.INVESTMENTS', 'A.OTHER_LOANS'], 'Financial-asset total')
  check(input.balanceSheet, 'A.CURRENT', ['A.INVENTORIES', 'A.RECEIVABLES', 'A.SECURITIES', 'A.CASH'], 'Current-asset total')
  check(input.balanceSheet, 'A.INVENTORIES', ['A.RAW_MATERIALS', 'A.WIP', 'A.FINISHED_GOODS', 'A.INVENTORY_ADVANCES'], 'Inventory total')
  check(input.balanceSheet, 'A.RECEIVABLES', ['A.TRADE_RECEIVABLES', 'A.AFFILIATED_RECEIVABLES', 'A.PARTICIPATION_RECEIVABLES', 'A.OTHER_RECEIVABLES'], 'Receivables total')
  check(input.balanceSheet, 'A.SECURITIES', ['A.AFFILIATED_SECURITIES', 'A.OTHER_SECURITIES'], 'Securities total')
  check(input.balanceSheet, 'B.EQUITY_LIABILITIES', ['B.EQUITY', 'B.PROVISIONS', 'B.LIABILITIES', 'B.DEFERRED', 'B.DEFERRED_TAX'], 'Equity/liabilities total')
  check(input.balanceSheet, 'B.EQUITY', ['B.SUBSCRIBED_CAPITAL', 'B.CAPITAL_RESERVE', 'B.REVENUE_RESERVES', 'B.CARRYFORWARD', 'B.NET_INCOME'], 'Equity total')
  check(input.balanceSheet, 'B.REVENUE_RESERVES', ['B.LEGAL_RESERVE', 'B.TREASURY_RESERVE', 'B.STATUTORY_RESERVES', 'B.OTHER_RESERVES'], 'Revenue-reserve total')
  check(input.balanceSheet, 'B.PROVISIONS', ['B.PENSION_PROVISIONS', 'B.TAX_PROVISIONS', 'B.OTHER_PROVISIONS'], 'Provisions total')
  check(input.balanceSheet, 'B.LIABILITIES', ['B.BONDS', 'B.BANK_LIABILITIES', 'B.ADVANCES', 'B.TRADE_LIABILITIES', 'B.BILLS', 'B.AFFILIATED_LIABILITIES', 'B.PARTICIPATION_LIABILITIES', 'B.OTHER_LIABILITIES'], 'Liabilities total')
  if (input.method === 'GKV') {
    const resultComponents = input.incomeStatement.some(line => line.code === 'GROSS_PROFIT')
      ? COMPACT_GKV_ORDER.filter(code => !['RESULT_AFTER_TAX', 'OTHER_TAX', 'NET_INCOME'].includes(code))
      : DETAILED_GKV_ORDER.filter(code => !['RESULT_AFTER_TAX', 'OTHER_TAX', 'NET_INCOME'].includes(code))
    check(input.incomeStatement, 'RESULT_AFTER_TAX', resultComponents, 'GKV result after tax')
  } else {
    const usesCompactUkv = input.incomeStatement.some(line => line.code === 'GROSS_PROFIT_RELIEF')
    if (!usesCompactUkv) check(input.incomeStatement, 'GROSS_SALES_PROFIT', ['REVENUE', 'COST_OF_SALES'], 'UKV gross sales profit')
    const resultComponents = usesCompactUkv
      ? COMPACT_UKV_ORDER.filter(code => !['RESULT_AFTER_TAX', 'OTHER_TAX', 'NET_INCOME'].includes(code))
      : DETAILED_UKV_ORDER.filter(code => !['REVENUE', 'COST_OF_SALES', 'RESULT_AFTER_TAX', 'OTHER_TAX', 'NET_INCOME'].includes(code))
    check(input.incomeStatement, 'RESULT_AFTER_TAX', resultComponents, 'UKV result after tax')
  }
  check(input.incomeStatement, 'NET_INCOME', ['RESULT_AFTER_TAX', 'OTHER_TAX'], `${input.method} net income`)
  const balanceNetIncome = input.balanceSheet.find(line => line.code === 'B.NET_INCOME')
  const incomeNetIncome = input.incomeStatement.find(line => line.code === 'NET_INCOME')
  if (balanceNetIncome && incomeNetIncome) {
    if (balanceNetIncome.amountCents !== incomeNetIncome.amountCents) issues.push('Balance-sheet net income does not match the income statement for current period.')
    if (balanceNetIncome.comparativeCents !== incomeNetIncome.comparativeCents) issues.push('Balance-sheet net income does not match the income statement for comparative period.')
  }
}
function validTimestamp(value: string) { return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(value) && validDateOnly(value.slice(0, 10)) && !Number.isNaN(Date.parse(value)) }
function validDate(value: string) { return validDateOnly(value) || validTimestamp(value) }
function fiscalPeriodExclusiveEnd(end: string, timeZone: string) { if (!timeZone?.trim()) return null; const next = new Date(`${end}T00:00:00.000Z`); next.setUTCDate(next.getUTCDate() + 1); const target = next.toISOString().slice(0, 10); const targetUtc = Date.parse(`${target}T00:00:00.000Z`); let candidate = targetUtc; try { const formatter = new Intl.DateTimeFormat('en-CA', { timeZone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }); for (let attempt = 0; attempt < 4; attempt++) { const parts = formatter.formatToParts(new Date(candidate)); const get = (type: string) => Number(parts.find(part => part.type === type)?.value); const represented = Date.UTC(get('year'), get('month') - 1, get('day'), get('hour'), get('minute'), get('second')); candidate += targetUtc - represented } const parts = formatter.formatToParts(new Date(candidate)); const text = `${parts.find(part => part.type === 'year')?.value}-${parts.find(part => part.type === 'month')?.value}-${parts.find(part => part.type === 'day')?.value}T${parts.find(part => part.type === 'hour')?.value}:${parts.find(part => part.type === 'minute')?.value}:${parts.find(part => part.type === 'second')?.value}`; return text === `${target}T00:00:00` ? candidate : null } catch { return null } }
function germanCalendarDate(value: string) { if (validDateOnly(value)) return value; const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Europe/Berlin', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date(value)); const get = (type: string) => parts.find(part => part.type === type)?.value; return `${get('year')}-${get('month')}-${get('day')}` }
function verifyAnnualPackage(pkg: AnnualAccountsPackage) { if (!Number.isSafeInteger(pkg.version) || pkg.version <= 0) throw new Error('Annual package version is invalid.'); const checksum = createHash('sha256').update(pkg.immutablePayload).digest('hex'); if (checksum !== pkg.checksum) throw new Error('Annual package payload checksum is invalid.'); let payload: unknown; try { payload = JSON.parse(pkg.immutablePayload) } catch { throw new Error('Annual package payload is invalid JSON.') } if (pkg.immutablePayload !== canonicalJson(payload)) throw new Error('Annual package immutable payload must use canonical JSON bytes.'); if (!isRecord(payload)) { const issues = validateAnnualAccounts(payload as never); throw new Error(`Annual package payload is semantically invalid: ${issues.join('; ')}`) } const { supersedesId: boundSupersedesId, ...untrustedInput } = payload; if ((boundSupersedesId !== undefined && (typeof boundSupersedesId !== 'string' || !boundSupersedesId.trim())) || boundSupersedesId !== pkg.supersedesId) throw new Error('Annual package supersession identity is not bound to its immutable payload.'); const input = untrustedInput as unknown as AnnualPackageInput; const issues = validateAnnualAccounts(input); if (issues.length) throw new Error(`Annual package payload is semantically invalid: ${issues.join('; ')}`); const normalizedInput = normalizeAnnualInput(input); if (canonicalJson(normalizedInput) !== canonicalJson(input)) throw new Error('Annual package payload contains undeclared or noncanonical DTO fields.'); const expectedId = `${normalizedInput.profile.tenantId}:${normalizedInput.fiscalPeriodStart}:${normalizedInput.fiscalPeriodEnd}:v${pkg.version}:${checksum}`; if (pkg.id !== expectedId) throw new Error('Annual package derived identity is invalid.'); return normalizedInput }
function captureAnnualPackage(value: unknown): AnnualAccountsPackage { if (!isRecord(value) || Array.isArray(value)) throw new Error('Annual package must be a structured object.'); const snapshot = {} as Record<string, unknown>; for (const field of ['id', 'version', 'status', 'immutablePayload', 'checksum'] as const) { const descriptor = Object.getOwnPropertyDescriptor(value, field); if (!descriptor?.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error('Annual package fields must be own enumerable data properties without accessors.'); snapshot[field] = descriptor.value } for (const field of ['approval', 'supersedesId'] as const) { const descriptor = Object.getOwnPropertyDescriptor(value, field); if (descriptor !== undefined) { if (!descriptor.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error('Annual package optional fields must be own enumerable data properties without accessors.'); snapshot[field] = descriptor.value } } return snapshot as unknown as AnnualAccountsPackage }
function captureDisclosureOptions(value: unknown) { if (!isRecord(value)) throw new Error('Disclosure options require valid deadline and generation fields.'); const deadline = ownEnumerableDataValue(value, 'deadline'); const generatedAt = ownEnumerableDataValue(value, 'generatedAt'); const reliefs = ownEnumerableDataValue(value, 'reliefs'); if (typeof deadline !== 'string' || typeof generatedAt !== 'string' || !hasDenseOwnElements(reliefs)) throw new Error('Disclosure options must use inert own data fields and a dense array of reliefs.'); const capturedReliefs: unknown[] = []; for (let index = 0; index < reliefs.length; index++) capturedReliefs.push(Object.getOwnPropertyDescriptor(reliefs, String(index))!.value); return { deadline, generatedAt, reliefs: capturedReliefs as readonly string[] } }
function captureApproval(value: unknown): Approval { if (!isRecord(value)) throw new Error('Approval must be an inert structured record.'); const approvedByValue = ownEnumerableDataValue(value, 'approvedBy'); const approvedAt = ownEnumerableDataValue(value, 'approvedAt'); const establishedAt = ownEnumerableDataValue(value, 'establishedAt'); const signaturesValue = ownEnumerableDataValue(value, 'signatures'); if (!hasDenseOwnElements(approvedByValue) || !hasDenseOwnElements(signaturesValue)) throw new Error('Approval identities and signatures must be dense inert arrays.'); const approvedBy: unknown[] = []; for (let index = 0; index < approvedByValue.length; index++) approvedBy.push(Object.getOwnPropertyDescriptor(approvedByValue, String(index))!.value); const signatures: Record<string, unknown>[] = []; for (let index = 0; index < signaturesValue.length; index++) { const signatureValue = Object.getOwnPropertyDescriptor(signaturesValue, String(index))!.value; if (!isRecord(signatureValue)) throw new Error('Approval signatures must be inert structured records.'); const signature: Record<string, unknown> = {}; for (const field of ['signer', 'role', 'signedAt']) { const descriptor = Object.getOwnPropertyDescriptor(signatureValue, field); if (!descriptor?.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error('Approval signature fields must be own enumerable data properties.'); signature[field] = descriptor.value } signatures.push(signature) } return { approvedBy: approvedBy as readonly string[], approvedAt: approvedAt as string, establishedAt: establishedAt as string, signatures: signatures as unknown as Approval['signatures'] } }
function validDateOnly(value: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const parsed = new Date(`${value}T00:00:00.000Z`); return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value }
function validateApproval(approval: Approval | undefined, preparedAt: string): asserts approval is Approval { if (!isRecord(approval)) throw new Error('Approval, establishment and required signatures are incomplete.'); const approvedBy = ownEnumerableDataValue(approval, 'approvedBy'); const approvedAt = ownEnumerableDataValue(approval, 'approvedAt'); const establishedAt = ownEnumerableDataValue(approval, 'establishedAt'); const signatures = ownEnumerableDataValue(approval, 'signatures'); if (!hasDenseNonblankStrings(approvedBy) || typeof approvedAt !== 'string' || !validTimestamp(approvedAt) || typeof establishedAt !== 'string' || !validTimestamp(establishedAt) || !hasDenseOwnElements(signatures) || signatures.length === 0) throw new Error('Approval, establishment and required signatures are incomplete.'); for (let index = 0; index < signatures.length; index++) { const signature = Object.getOwnPropertyDescriptor(signatures, String(index))!.value; if (!isRecord(signature) || !isOwnNonblankString(signature, 'signer') || !isOwnNonblankString(signature, 'role') || !isOwnNonblankString(signature, 'signedAt') || !validTimestamp(signature.signedAt as string)) throw new Error('A signature is invalid.') } const prepared = Date.parse(preparedAt); if (Date.parse(approvedAt) < prepared || Date.parse(establishedAt) < prepared || signatures.some(signature => Date.parse((signature as { signedAt: string }).signedAt) < prepared)) throw new Error('Approval, establishment and signatures cannot predate preparation.') }
function normalizeApproval(approval: Approval): Approval { return { approvedBy: [...approval.approvedBy], approvedAt: approval.approvedAt, establishedAt: approval.establishedAt, signatures: approval.signatures.map(signature => ({ signer: signature.signer, role: signature.role, signedAt: signature.signedAt })) } }
function approvalLifecycleInstants(approval: Approval) { return [approval.approvedAt, approval.establishedAt, ...approval.signatures.map(signature => signature.signedAt)].map(Date.parse) }
function approvalFinalizationInstant(approval: Approval) { return Math.max(...approvalLifecycleInstants(approval)) }
function requireAnnualApprovalStore(authority: AnnualApprovalAuthority) { const store = annualApprovalStores.get(authority); if (!store) throw new Error('A trusted annual approval authority is required.'); return store }
function emptyAnnualApprovalState(): AnnualApprovalState { return { revision: 0, packages: new Map(), activeByChain: new Map(), packageByChainVersion: new Map() } }
function captureAnnualStateAuthenticator(authenticator: unknown, operation: 'sign'): { keyId: string; sign: AnnualApprovalStateAuthenticator['sign'] }
function captureAnnualStateAuthenticator(authenticator: unknown, operation: 'verify'): { keyId: string; verify: AnnualApprovalStateAuthenticator['verify'] }
function captureAnnualStateAuthenticator(authenticator: unknown, operation: 'sign' | 'verify') { if (!isRecord(authenticator)) throw new Error('Annual approval state requires a trusted external authenticator.'); const keyId = ownEnumerableDataValue(authenticator, 'keyId'); const adapter = ownEnumerableDataValue(authenticator, operation); if (typeof keyId !== 'string' || !keyId.trim() || typeof adapter !== 'function') throw new Error('Annual approval state requires a trusted external authenticator.'); return { keyId, [operation]: adapter } }
function captureAnnualRevisionStore(value: unknown): { currentRevision: AnnualApprovalRevisionStore['currentRevision']; commitSnapshot: AnnualApprovalRevisionStore['commitSnapshot'] } { if (!isRecord(value)) throw new Error('Annual approval state requires a trusted durable revision store.'); const currentRevision = ownEnumerableDataValue(value, 'currentRevision'); const commitSnapshot = ownEnumerableDataValue(value, 'commitSnapshot'); if (typeof currentRevision !== 'function' || typeof commitSnapshot !== 'function') throw new Error('Annual approval state requires a trusted durable revision store.'); return { currentRevision: currentRevision as AnnualApprovalRevisionStore['currentRevision'], commitSnapshot: commitSnapshot as AnnualApprovalRevisionStore['commitSnapshot'] } }
function authenticateAnnualApprovalState(value: unknown, authenticator: AnnualApprovalStateAuthenticator | undefined, revisionStore: AnnualApprovalRevisionStore | undefined): AnnualApprovalStateSnapshot { let captured: unknown; try { captured = captureAnnualValue(value) } catch { throw new Error('Annual approval state snapshot must use inert own data fields.') } if (!isRecord(captured)) throw new Error('Annual approval state snapshot must be a structured object.'); const authenticity = captured.authenticity; if (!isRecord(authenticity) || typeof authenticity.keyId !== 'string' || !authenticity.keyId.trim() || typeof authenticity.signature !== 'string' || !authenticity.signature.trim()) throw new Error('Annual approval state snapshot authenticity is incomplete.'); const adapter = captureAnnualStateAuthenticator(authenticator, 'verify'); const revisions = captureAnnualRevisionStore(revisionStore); if (authenticity.keyId !== adapter.keyId) throw new Error('Annual approval state snapshot authenticity is not verified by the trusted external anchor.'); const { authenticity: _authenticity, ...payload } = captured; if (adapter.verify.call(authenticator, canonicalJson(payload), authenticity.signature, authenticity.keyId) !== true) throw new Error('Annual approval state snapshot authenticity is not verified by the trusted external anchor.'); if (!Number.isSafeInteger(captured.revision) || Number(captured.revision) <= 0 || revisions.currentRevision.call(revisionStore, authenticity.keyId) !== captured.revision) throw new Error('Annual approval state snapshot revision is stale or not committed in trusted durable storage.'); return captured as unknown as AnnualApprovalStateSnapshot }
function hydrateAnnualApprovalState(value: unknown): AnnualApprovalState {
  if (!isRecord(value) || ownEnumerableDataValue(value, 'version') !== 1) throw new Error('Annual approval state snapshot requires protocol version 1.')
  const packagesValue = ownEnumerableDataValue(value, 'packages'); if (!hasDenseOwnElements(packagesValue)) throw new Error('Annual approval state snapshot packages must be a dense inert array.')
  const activePackageIdsValue = ownEnumerableDataValue(value, 'activePackageIds'); if (!hasDenseNonblankStrings(activePackageIdsValue, true)) throw new Error('Annual approval state snapshot active package IDs must be a dense string array.')
  const activePackageIdSnapshot: string[] = []; for (let index = 0; index < activePackageIdsValue.length; index++) activePackageIdSnapshot.push(Object.getOwnPropertyDescriptor(activePackageIdsValue, String(index))!.value)
  const activePackageIds = new Set(activePackageIdSnapshot); if (activePackageIds.size !== activePackageIdSnapshot.length) throw new Error('Annual approval state snapshot active package IDs must be unique.')
  const state = emptyAnnualApprovalState(); state.revision = Number(ownEnumerableDataValue(value, 'revision')); const byChain = new Map<string, { pkg: AnnualAccountsPackage; input: AnnualPackageInput }[]>()
  for (let index = 0; index < packagesValue.length; index++) {
    const pkg = captureAnnualPackage(Object.getOwnPropertyDescriptor(packagesValue, String(index))!.value); const input = verifyAnnualPackage(pkg)
    if (!['APPROVED', 'SUPERSEDED'].includes(pkg.status)) throw new Error('Hydrated annual approval packages must be approved or superseded.')
    const approval = captureApproval(pkg.approval); validateApproval(approval, input.preparedAt); const normalized: AnnualAccountsPackage = { ...pkg, approval: normalizeApproval(approval) }
    if (state.packages.has(pkg.id)) throw new Error('Annual approval state snapshot contains duplicate package identities.')
    state.packages.set(pkg.id, structuredClone(normalized)); const chain = annualChainKey(input); byChain.set(chain, [...(byChain.get(chain) ?? []), { pkg: normalized, input }])
  }
  for (const [chain, members] of byChain) {
    members.sort((left, right) => left.pkg.version - right.pkg.version)
    const activeIndex = members.findIndex(member => activePackageIds.has(member.pkg.id)); if (activeIndex < 0 || members.some((member, index) => index !== activeIndex && activePackageIds.has(member.pkg.id))) throw new Error('Annual approval state snapshot must identify exactly one active package per chain.')
    for (let index = 0; index < members.length; index++) {
      const current = members[index]; const prior = members[index - 1]; const chainVersion = canonicalJson([chain, current.pkg.version])
      if (state.packageByChainVersion.has(chainVersion)) throw new Error('Annual approval state snapshot contains a duplicate tenant, fiscal-period and version reservation.')
      if ((!prior && current.pkg.supersedesId !== undefined) || (prior && (current.pkg.version !== prior.pkg.version + 1 || current.pkg.supersedesId !== prior.pkg.id))) throw new Error('Annual approval state snapshot contains a broken supersession chain.')
      if (prior) { const finalized = approvalFinalizationInstant(prior.pkg.approval!); if ([Date.parse(current.input.preparedAt), ...approvalLifecycleInstants(current.pkg.approval!)].some(instant => instant <= finalized)) throw new Error('Annual approval state snapshot contains nonchronological lifecycle transitions.') }
      const isPendingReplacement = index === activeIndex + 1
      const expectedStatus = index < activeIndex ? 'SUPERSEDED' : index === activeIndex || isPendingReplacement ? 'APPROVED' : null
      if (expectedStatus === null || current.pkg.status !== expectedStatus) throw new Error('Annual approval state snapshot contains invalid active, pending or superseded lifecycle state.')
      state.packageByChainVersion.set(chainVersion, current.pkg.id)
    }
    state.activeByChain.set(chain, members[activeIndex].pkg.id); activePackageIds.delete(members[activeIndex].pkg.id)
  }
  if (activePackageIds.size) throw new Error('Annual approval state snapshot contains orphan active package IDs.')
  return state
}
function verifyAttestedApprovedPackage(pkg: AnnualAccountsPackage, authority: AnnualApprovalAuthority) { if (pkg.status !== 'APPROVED') throw new Error('Only genuinely approved annual accounts can transition.'); const input = verifyAnnualPackage(pkg); const approval = captureApproval(pkg.approval); validateApproval(approval, input.preparedAt); const normalizedPackage = { ...pkg, approval: normalizeApproval(approval) }; const trusted = requireAnnualApprovalStore(authority).packages.get(pkg.id); if (!trusted || canonicalJson(trusted) !== canonicalJson(normalizedPackage)) throw new Error('Annual approval is not attested by exact trusted package identity, checksum and lifecycle state.'); return { trusted, input } }
function verifyApprovedPackage(pkg: AnnualAccountsPackage, authority: AnnualApprovalAuthority) { const verified = verifyAttestedApprovedPackage(pkg, authority); const state = requireAnnualApprovalStore(authority); if (state.activeByChain.get(annualChainKey(verified.input)) !== pkg.id) throw new Error('Annual accounts are approved but not the single active tenant and fiscal-period version.'); return verified.trusted }
function annualChainKey(input: AnnualPackageInput) { return canonicalJson([input.profile.tenantId, input.fiscalPeriodStart, input.fiscalPeriodEnd]) }
function deepFreeze<T>(value: T): T { if (value && typeof value === 'object' && !Object.isFrozen(value)) { for (const nested of Object.values(value)) deepFreeze(nested); Object.freeze(value) } return value }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value) }
function ownEnumerableDataValue(record: Record<string, unknown>, field: string): unknown { const descriptor = Object.getOwnPropertyDescriptor(record, field); return descriptor && descriptor.enumerable && Object.hasOwn(descriptor, 'value') ? descriptor.value : undefined }
function isOwnNonblankString(record: Record<string, unknown>, field: string) { const value = ownEnumerableDataValue(record, field); return typeof value === 'string' && Boolean(value.trim()) }
function hasDenseRecordArray(value: unknown): value is readonly Record<string, unknown>[] { if (!hasDenseOwnElements(value)) return false; for (let index = 0; index < value.length; index++) { const descriptor = Object.getOwnPropertyDescriptor(value, String(index))!; if (!isRecord(descriptor.value)) return false } return true }
function hasAnnualTraversalShape(value: Record<string, unknown>): boolean { const profile = value.profile; if (!isRecord(profile) || !['tenantId', 'legalName', 'legalForm', 'registerCourt', 'registerNumber', 'registeredOffice', 'size', 'currency', 'language'].every(field => typeof profile[field] === 'string')) return false; if (!hasDenseRecordArray(value.balanceSheet) || !hasDenseRecordArray(value.incomeStatement) || [...value.balanceSheet, ...value.incomeStatement].some(line => typeof line.code !== 'string')) return false; if (!hasDenseOwnElements(value.policies) || !hasDenseOwnElements(value.notes) || !isRecord(value.checks)) return false; if (!['method', 'fiscalPeriodStart', 'fiscalPeriodEnd', 'fiscalTimeZone', 'preparedBy', 'preparedAt'].every(field => typeof value[field] === 'string')) return false; if (value.managementReport !== undefined && typeof value.managementReport !== 'string') return false; return true }
