import { createHash } from 'node:crypto'
import { canonicalJson } from './auditExport'
import { compareCanonicalText } from './deterministicOrder'
import { hasDenseOwnElements, hasStrictEvidenceIds } from './validation'

export type DepreciationMethod = 'STRAIGHT_LINE' | 'NO_DEPRECIATION'
export interface FixedAsset { id: string; tenantId: string; description: string; costCents: number; acquisitionDate: string; availableForUseDate: string; location: string; usefulLifeMonths: number; method: DepreciationMethod; taxUsefulLifeMonths: number; taxMethod: DepreciationMethod; componentOf?: string; evidenceIds: readonly string[] }
export interface AssetEvent { id: string; assetId: string; sequence: number; type: 'DEPRECIATION' | 'IMPAIRMENT' | 'REVERSAL' | 'DISPOSAL' | 'TRANSFER'; effectiveDate: string; amountCents: number; bookAmountCents?: number; taxAmountCents?: number; reversesEventId?: string; fromLocation?: string; toLocation?: string; approvedBy: string; approvedAt: string; postingId: string; evidenceIds: readonly string[] }

export function calculatePartialYearDepreciation(asset: FixedAsset, period: { start: string; end: string }, basis: 'BOOK' | 'TAX') {
  if (basis !== 'BOOK' && basis !== 'TAX') throw new Error('Depreciation basis must be BOOK or TAX.')
  asset = normalizeAssetMaster(captureAssetMaster(asset))
  const normalizedPeriod = captureAssetPeriod(period)
  validateAsset(asset); validateFiscalPeriod(normalizedPeriod)
  if (!normalizedPeriod.start.endsWith('-01') || normalizedPeriod.end !== monthEnd(normalizedPeriod.end)) throw new Error('Depreciation periods must use whole-month boundaries.')
  const method = basis === 'BOOK' ? asset.method : asset.taxMethod; if (method === 'NO_DEPRECIATION') return 0
  const beforeStart = previousMonthEnd(normalizedPeriod.start)
  return depreciationCumulative(asset, normalizedPeriod.end, basis) - depreciationCumulative(asset, beforeStart, basis)
}

export function applyAssetEvents(asset: FixedAsset, events: readonly AssetEvent[], through: string) {
  asset = normalizeAssetMaster(captureAssetMaster(asset))
  validateAsset(asset); if (!validDateOnly(through)) throw new Error('Asset lifecycle dates or reporting date are invalid.')
  const capturedEvents = captureDenseArray(events, 'Asset events', captureAssetEvent)
  const normalizedAsset = asset
  if (through < asset.acquisitionDate) throw new Error('Asset as-of date cannot precede acquisition.')
  const assetEvents = capturedEvents.filter(event => event.assetId === asset.id)
  if (new Set(assetEvents.map(event => event.id)).size !== assetEvents.length) throw new Error('Asset event IDs must be unique per asset.')
  const orderKeys = assetEvents.map(event => `${event.effectiveDate}\u0000${event.sequence}`); if (new Set(orderKeys).size !== orderKeys.length) throw new Error('Asset events require a unique explicit sequence per effective date.')
  for (const event of assetEvents) { validateAssetEvent(event); if (!validDateOnly(event.effectiveDate) || event.effectiveDate < asset.acquisitionDate) throw new Error('Asset event effective date is invalid or precedes acquisition.') }
  const ordered = assetEvents.filter(event => event.effectiveDate <= through).sort((a, b) => compareCanonicalText(a.effectiveDate, b.effectiveDate) || a.sequence - b.sequence)
  let bookValue = asset.costCents; let taxValue = asset.costCents; let bookDepreciation = 0; let taxDepreciation = 0; let location = normalizedAsset.location; let disposed = false
  const reversible = new Map<string, { type: 'DEPRECIATION' | 'IMPAIRMENT'; bookRemaining: number; taxRemaining: number }>()
  for (const event of ordered) {
    if (disposed) throw new Error('No asset events are allowed after disposal.')
    if (event.type === 'DEPRECIATION' || event.type === 'IMPAIRMENT') {
      const bookAmount = event.bookAmountCents ?? event.amountCents; const taxAmount = event.taxAmountCents ?? event.amountCents
      if (event.type === 'DEPRECIATION') {
        if ((asset.method === 'NO_DEPRECIATION' && bookAmount !== 0) || (asset.taxMethod === 'NO_DEPRECIATION' && taxAmount !== 0)) throw new Error('Depreciation event is incompatible with the configured book/tax method.')
        bookDepreciation = addCents(bookDepreciation, bookAmount); taxDepreciation = addCents(taxDepreciation, taxAmount)
        const bookAllowance = asset.method === 'STRAIGHT_LINE' ? depreciationCumulative(asset, event.effectiveDate, 'BOOK') : 0
        const taxAllowance = asset.taxMethod === 'STRAIGHT_LINE' ? depreciationCumulative(asset, event.effectiveDate, 'TAX') : 0
        if (bookDepreciation > bookAllowance || taxDepreciation > taxAllowance) throw new Error('Cumulative depreciation exceeds the scheduled book/tax allowance as of the event effective date.')
      }
      bookValue -= bookAmount; taxValue -= taxAmount
      reversible.set(event.id, { type: event.type, bookRemaining: bookAmount, taxRemaining: taxAmount })
    }
    if (event.type === 'REVERSAL') {
      const target = reversible.get(event.reversesEventId!); const bookReversal = event.bookAmountCents ?? event.amountCents; const taxReversal = event.taxAmountCents ?? event.amountCents
      if (!target) throw new Error('Reversal must identify a prior depreciation or impairment event for this asset.')
      if (bookReversal > target.bookRemaining || taxReversal > target.taxRemaining || bookValue + bookReversal > asset.costCents || taxValue + taxReversal > asset.costCents) throw new Error('Reversal exceeds the identified event\'s previously recognized depreciation or impairment.')
      target.bookRemaining -= bookReversal; target.taxRemaining -= taxReversal
      if (target.type === 'DEPRECIATION') { bookDepreciation -= bookReversal; taxDepreciation -= taxReversal }
      bookValue += bookReversal; taxValue += taxReversal
    }
    if (event.type === 'TRANSFER') { const fromLocation = event.fromLocation!.trim(); const toLocation = event.toLocation!.trim(); if (fromLocation !== location) throw new Error('Transfer location chain is invalid.'); location = toLocation }
    if (event.type === 'DISPOSAL') { bookValue = 0; taxValue = 0; disposed = true }
    if (bookValue < 0 || taxValue < 0) throw new Error('An asset value cannot become negative.')
  }
  return { assetId: asset.id, bookValueCents: bookValue, taxValueCents: taxValue, bookTaxDifferenceCents: bookValue - taxValue, location, disposed, eventIds: ordered.map(event => event.id) }
}

export function createAssetSchedules(tenantId: string, assets: readonly FixedAsset[], events: readonly AssetEvent[], period: { start: string; end: string }) {
  if (typeof tenantId !== 'string' || !tenantId.trim()) throw new Error('Asset schedules require a nonblank authoritative tenant identity.')
  const normalizedPeriod = captureAssetPeriod(period)
  validateFiscalPeriod(normalizedPeriod)
  const capturedAssets = captureDenseArray(assets, 'Asset masters', captureAssetMaster)
  const capturedEvents = captureDenseArray(events, 'Asset events', captureAssetEvent)
  for (const asset of capturedAssets) validateAsset(asset)
  const normalizedAssets = capturedAssets.map(normalizeAssetMaster)
  if (new Set(normalizedAssets.map(asset => asset.id)).size !== normalizedAssets.length) throw new Error('Asset master IDs must be unique in exported schedules.')
  if (normalizedAssets.some(asset => asset.tenantId !== tenantId)) throw new Error('Asset masters must match the authoritative schedule tenant identity.')
  const byAsset = new Map(normalizedAssets.map(asset => [asset.id, asset] as const))
  for (const event of capturedEvents) { const master = byAsset.get(event.assetId); if (!master) throw new Error('Asset schedules contain an event for an unknown asset.'); validateAssetEvent(event); if (!validDateOnly(event.effectiveDate) || event.effectiveDate < master.acquisitionDate) throw new Error('Asset event effective date is invalid or precedes acquisition.') }
  const rows = [...normalizedAssets].sort((left, right) => compareCanonicalText(left.id, right.id)).filter(asset => asset.acquisitionDate <= normalizedPeriod.end).map(asset => {
    const status = applyAssetEvents(asset, capturedEvents, normalizedPeriod.end)
    const assetEvents = capturedEvents.filter(event => event.assetId === asset.id).sort((left, right) => compareCanonicalText(left.effectiveDate, right.effectiveDate) || left.sequence - right.sequence)
    const disposedBeforePeriod = assetEvents.some(event => event.type === 'DISPOSAL' && event.effectiveDate < normalizedPeriod.start)
    const disposedInPeriod = assetEvents.some(event => event.type === 'DISPOSAL' && normalizedPeriod.start <= event.effectiveDate && event.effectiveDate <= normalizedPeriod.end)
    const openingCostCents = asset.acquisitionDate < normalizedPeriod.start && !disposedBeforePeriod ? asset.costCents : 0
    const additionsCents = normalizedPeriod.start <= asset.acquisitionDate && asset.acquisitionDate <= normalizedPeriod.end ? asset.costCents : 0
    const disposalsCents = disposedInPeriod ? asset.costCents : 0
    const costCents = openingCostCents + additionsCents
    const openingBookValueCents = openingCostCents ? applyAssetEvents(asset, assetEvents, previousDay(normalizedPeriod.start)).bookValueCents : 0
    const openingAccumulatedDepreciationCents = openingCostCents - openingBookValueCents
    const movements = assetEvents.filter(event => normalizedPeriod.start <= event.effectiveDate && event.effectiveDate <= normalizedPeriod.end)
    const bookAmount = (event: AssetEvent) => event.bookAmountCents ?? event.amountCents
    const currentDepreciationCents = movements.filter(event => event.type === 'DEPRECIATION').reduce((sum, event) => addCents(sum, bookAmount(event)), 0)
    const impairmentsCents = movements.filter(event => event.type === 'IMPAIRMENT').reduce((sum, event) => addCents(sum, bookAmount(event)), 0)
    const reversalsCents = movements.filter(event => event.type === 'REVERSAL').reduce((sum, event) => addCents(sum, bookAmount(event)), 0)
    const depreciationBeforeDisposal = addCents(addCents(addCents(openingAccumulatedDepreciationCents, currentDepreciationCents), impairmentsCents), -reversalsCents)
    const depreciationRemovedOnDisposalCents = disposedInPeriod ? depreciationBeforeDisposal : 0
    const closingCostCents = addCents(costCents, -disposalsCents)
    const closingAccumulatedDepreciationCents = addCents(depreciationBeforeDisposal, -depreciationRemovedOnDisposalCents)
    if (addCents(closingCostCents, -closingAccumulatedDepreciationCents) !== status.bookValueCents) throw new Error(`Asset movement schedule ${asset.id} does not reconcile to its event-stream carrying value.`)
    const transferEventIds = movements.filter(event => event.type === 'TRANSFER').map(event => event.id)
    return { asset, status, openingCostCents, additionsCents, costCents, disposalsCents, closingCostCents, acquisitionCostTransfersCents: 0, transferEventIds, openingAccumulatedDepreciationCents, currentDepreciationCents, impairmentsCents, reversalsCents, accumulatedDepreciationTransfersCents: 0, depreciationRemovedOnDisposalCents, closingAccumulatedDepreciationCents, accumulatedDepreciationCents: closingAccumulatedDepreciationCents }
  })
  const hgbAnlagenspiegel = rows.map(row => ({ assetId: row.asset.id, description: row.asset.description, openingCostCents: row.openingCostCents, additionsCents: row.additionsCents, acquisitionCostTransfersCents: row.acquisitionCostTransfersCents, disposalsCents: row.disposalsCents, closingCostCents: row.closingCostCents, costCents: row.costCents, openingAccumulatedDepreciationCents: row.openingAccumulatedDepreciationCents, currentDepreciationCents: row.currentDepreciationCents, impairmentsCents: row.impairmentsCents, reversalsCents: row.reversalsCents, accumulatedDepreciationTransfersCents: row.accumulatedDepreciationTransfersCents, depreciationRemovedOnDisposalCents: row.depreciationRemovedOnDisposalCents, closingAccumulatedDepreciationCents: row.closingAccumulatedDepreciationCents, accumulatedDepreciationCents: row.closingAccumulatedDepreciationCents, carryingAmountCents: row.status.bookValueCents, transferEventIds: row.transferEventIds, location: row.status.location }))
  const eBalanceAssetSchedule = hgbAnlagenspiegel.map(row => ({ ...row, costCents: row.closingCostCents }))
  const eBilanzAnlagenverzeichnis = rows.map(row => ({ assetId: row.asset.id, acquisitionDate: row.asset.acquisitionDate, taxValueCents: row.status.taxValueCents, bookTaxDifferenceCents: row.status.bookTaxDifferenceCents, evidenceIds: row.asset.evidenceIds }))
  const envelope = { tenantId, fiscalPeriodStart: normalizedPeriod.start, fiscalPeriodEnd: normalizedPeriod.end }
  return { tenantId, period: normalizedPeriod, hgbAnlagenspiegel, eBilanzAnlagenverzeichnis, eBalanceAttachments: { assetSchedule: { ...envelope, rows: eBalanceAssetSchedule }, assetRegister: { ...envelope, rows: eBilanzAnlagenverzeichnis } } }
}

export interface InventoryItem { id: string; tenantId: string; sku: string; description: string; location: string; quantity: number; unitCostCents: number }
export interface InventoryCount { itemId: string; countedQuantity: number; countedBy: string; countedAt: string; evidenceIds: readonly string[]; approvedBy: string; approvedAt: string }
export interface InventoryPeriod { start: string; end: string; timeZone: string }
export function closePhysicalInventory(tenantId: string, period: InventoryPeriod, items: readonly InventoryItem[], counts: readonly InventoryCount[], closedAt: string) {
  if (typeof tenantId !== 'string' || !tenantId.trim()) throw new Error('Inventory tenantId must be nonblank.')
  const normalizedTenantId = tenantId.trim()
  const normalizedPeriod = captureInventoryPeriod(period)
  const capturedItems = captureDenseArray(items, 'Inventory items', captureInventoryItem)
  const capturedCounts = captureDenseArray(counts, 'Inventory counts', captureInventoryCount)
  if (capturedItems.some(item => typeof item.tenantId !== 'string' || !item.tenantId.trim() || item.tenantId !== normalizedTenantId)) throw new Error('Inventory items contain a blank or mismatched tenantId.')
  validateFiscalPeriod(normalizedPeriod)
  validateTimeZone(normalizedPeriod.timeZone)
  if (!validInstant(closedAt)) throw new Error('Inventory close timestamp is invalid.')
  const closeDate = localDate(closedAt, normalizedPeriod.timeZone); if (closeDate < normalizedPeriod.end) throw new Error('Inventory close cannot precede the authoritative period balance date in its timezone.')
  const itemIds = new Set(capturedItems.map(item => item.id)); if (itemIds.size !== capturedItems.length) throw new Error('Inventory item IDs must be unique.'); if (capturedCounts.some(count => !itemIds.has(count.itemId))) throw new Error('Inventory counts contain an unknown or foreign item.')
  const rows = [...capturedItems].sort((left, right) => compareCanonicalText(left.id, right.id)).map(item => { if (![item.id, item.sku, item.description, item.location].every(value => typeof value === 'string' && value.trim())) throw new Error('Inventory item identifying master fields must be nonblank.'); if (!nonnegativeSafeInteger(item.quantity) || !nonnegativeSafeInteger(item.unitCostCents)) throw new Error(`Inventory item ${item.id} has invalid quantity or unit cost.`); const matching = capturedCounts.filter(value => value.itemId === item.id); if (matching.length !== 1) throw new Error(`Inventory item ${item.id} requires exactly one physical count.`); const count = matching[0]; if (!nonnegativeSafeInteger(count.countedQuantity) || !hasStrictEvidenceIds(count.evidenceIds) || typeof count.countedBy !== 'string' || !count.countedBy.trim() || typeof count.approvedBy !== 'string' || !count.approvedBy.trim() || !validInstant(count.countedAt) || !validInstant(count.approvedAt)) throw new Error(`Inventory count ${item.id} lacks valid quantities, evidence or approval.`); const countDate = localDate(count.countedAt, normalizedPeriod.timeZone); if (countDate !== normalizedPeriod.end || Date.parse(count.countedAt) > Date.parse(count.approvedAt) || Date.parse(count.approvedAt) > Date.parse(closedAt)) throw new Error(`Inventory count ${item.id} must occur on the period balance date in its timezone with ordered approval and closure.`); const adjustmentCents = (count.countedQuantity - item.quantity) * item.unitCostCents; const closingValueCents = count.countedQuantity * item.unitCostCents; if (!Number.isSafeInteger(adjustmentCents) || !Number.isSafeInteger(closingValueCents)) throw new Error(`Inventory valuation ${item.id} exceeds safe integer limits.`); return { id: item.id, tenantId: normalizedTenantId, sku: item.sku, description: item.description, location: item.location, quantity: item.quantity, unitCostCents: item.unitCostCents, itemId: count.itemId, countedQuantity: count.countedQuantity, countedBy: count.countedBy, countedAt: count.countedAt, evidenceIds: [...count.evidenceIds], approvedBy: count.approvedBy, approvedAt: count.approvedAt, expectedQuantity: item.quantity, differenceQuantity: count.countedQuantity - item.quantity, adjustmentCents, closingValueCents } })
  const payload = canonicalJson({ tenantId: normalizedTenantId, period: normalizedPeriod, closedAt, rows }); return deepFreeze({ tenantId: normalizedTenantId, period: normalizedPeriod, closedAt, rows, checksum: createHash('sha256').update(payload).digest('hex'), immutablePayload: payload })
}
export function reconcileSubledgers(assetBookValueCents: number, assetGlCents: number, inventoryValueCents: number, inventoryGlCents: number, explanations: readonly { ledger: 'ASSETS' | 'INVENTORY'; amountCents: number; explanation: string; approvedBy: string }[] = []) {
  const capturedExplanations = captureDenseArray(explanations, 'Reconciliation explanations', value => captureStructuredRecord(value, ['ledger', 'amountCents', 'explanation', 'approvedBy'], [], 'Reconciliation explanation') as unknown as { ledger: 'ASSETS' | 'INVENTORY'; amountCents: number; explanation: string; approvedBy: string })
  for (const value of [assetBookValueCents, assetGlCents, inventoryValueCents, inventoryGlCents]) if (!Number.isSafeInteger(value)) throw new Error('Subledger reconciliation values must be safe integer cents.'); for (const explanation of capturedExplanations) if (!Number.isSafeInteger(explanation.amountCents)) throw new Error('Reconciliation explanation amounts must be safe integer cents.')
  const assetDifference = addCents(assetBookValueCents, -assetGlCents); const inventoryDifference = addCents(inventoryValueCents, -inventoryGlCents)
  const explained = (ledger: 'ASSETS' | 'INVENTORY', amount: number) => { let total = 0; for (const item of capturedExplanations) if (item.ledger === ledger && typeof item.explanation === 'string' && item.explanation.trim() && typeof item.approvedBy === 'string' && item.approvedBy.trim()) total = addCents(total, item.amountCents); return total === amount }
  const issues = [...(assetDifference && !explained('ASSETS', assetDifference) ? [`Unexplained asset/GL difference: ${assetDifference}`] : []), ...(inventoryDifference && !explained('INVENTORY', inventoryDifference) ? [`Unexplained inventory/GL difference: ${inventoryDifference}`] : [])]
  return { assetDifferenceCents: assetDifference, inventoryDifferenceCents: inventoryDifference, canClose: issues.length === 0, issues }
}
function validateAssetEvent(event: AssetEvent) { if (typeof event.id !== 'string' || !event.id.trim()) throw new Error('Asset event ID must be nonblank.'); if (!['DEPRECIATION', 'IMPAIRMENT', 'REVERSAL', 'DISPOSAL', 'TRANSFER'].includes(event.type)) throw new Error('Asset event type is invalid.'); if (!Number.isSafeInteger(event.sequence) || event.sequence <= 0 || typeof event.approvedBy !== 'string' || !event.approvedBy.trim() || !validInstant(event.approvedAt) || typeof event.postingId !== 'string' || !event.postingId.trim()) throw new Error('Asset events require explicit sequence, approval and a posted journal reference.'); if (validDateOnly(event.effectiveDate) && localDate(event.approvedAt, 'Europe/Berlin') < event.effectiveDate) throw new Error('Asset event approval cannot predate its effective business date in the authoritative German timezone.'); for (const amount of [event.amountCents, event.bookAmountCents, event.taxAmountCents]) if (amount !== undefined && !nonnegativeSafeInteger(amount)) throw new Error('Asset event amounts must be nonnegative safe integer cents.'); if (event.type === 'REVERSAL' ? typeof event.reversesEventId !== 'string' || !event.reversesEventId.trim() : event.reversesEventId !== undefined) throw new Error('Only a reversal may identify the nonblank prior event it reverses.'); if ((event.type === 'IMPAIRMENT' || event.type === 'DISPOSAL') && !hasStrictEvidenceIds(event.evidenceIds)) throw new Error('Impairment and disposal require nonblank evidence IDs.'); if (event.type === 'TRANSFER' && (typeof event.fromLocation !== 'string' || !event.fromLocation.trim() || typeof event.toLocation !== 'string' || !event.toLocation.trim())) throw new Error('Transfers require nonblank source and destination locations.'); if ((event.type === 'TRANSFER' || event.type === 'DISPOSAL') && [event.amountCents, event.bookAmountCents, event.taxAmountCents].some(amount => amount !== undefined && amount !== 0)) throw new Error(`${event.type === 'TRANSFER' ? 'Location-only transfers' : 'Disposals'} require zero monetary amounts because carrying values are derecognized in full.`) }
function captureDenseArray<T>(value: unknown, label: string, capture: (entry: unknown) => T): readonly T[] { if (!hasDenseOwnElements(value)) throw new Error(`${label} must be a dense array of own data elements.`); const snapshot: T[] = []; for (let index = 0; index < value.length; index++) snapshot.push(capture(Object.getOwnPropertyDescriptor(value, String(index))!.value)); return snapshot }
function captureAssetMaster(value: unknown): FixedAsset { return captureStructuredRecord(value, ['id', 'tenantId', 'description', 'costCents', 'acquisitionDate', 'availableForUseDate', 'location', 'usefulLifeMonths', 'method', 'taxUsefulLifeMonths', 'taxMethod', 'evidenceIds'], ['componentOf'], 'Asset master') as unknown as FixedAsset }
function captureAssetEvent(value: unknown): AssetEvent { return captureStructuredRecord(value, ['id', 'assetId', 'sequence', 'type', 'effectiveDate', 'amountCents', 'approvedBy', 'approvedAt', 'postingId', 'evidenceIds'], ['bookAmountCents', 'taxAmountCents', 'reversesEventId', 'fromLocation', 'toLocation'], 'Asset event') as unknown as AssetEvent }
function captureInventoryItem(value: unknown): InventoryItem { const item = captureStructuredRecord(value, ['id', 'tenantId', 'sku', 'description', 'location', 'quantity', 'unitCostCents'], [], 'Inventory item') as unknown as InventoryItem; if (![item.id, item.tenantId, item.sku, item.description, item.location].every(field => typeof field === 'string')) throw new Error('Inventory item identifying master fields must be strings.'); return item }
function captureInventoryCount(value: unknown): InventoryCount { const count = captureStructuredRecord(value, ['itemId', 'countedQuantity', 'countedBy', 'countedAt', 'evidenceIds', 'approvedBy', 'approvedAt'], [], 'Inventory count') as unknown as InventoryCount; if (typeof count.itemId !== 'string') throw new Error('Inventory count itemId must be a string.'); let evidenceIds: readonly string[]; try { evidenceIds = captureDenseArray(count.evidenceIds, 'Inventory count evidence IDs', entry => entry as string) } catch { throw new Error(`Inventory count ${count.itemId} lacks valid quantities, evidence or approval.`) } return { ...count, evidenceIds } }
function captureStructuredRecord(value: unknown, requiredFields: readonly string[], optionalFields: readonly string[], label: string): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${label} must be a structured record with own data fields.`); const source = value as Record<string, unknown>; const snapshot: Record<string, unknown> = {}; for (const field of requiredFields) { const descriptor = Object.getOwnPropertyDescriptor(source, field); if (!descriptor?.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error(`${label} must use own enumerable data fields.`); snapshot[field] = descriptor.value } for (const field of optionalFields) { const descriptor = Object.getOwnPropertyDescriptor(source, field); if (!descriptor) { if (field in source) throw new Error(`${label} optional fields must use own enumerable data fields.`); continue } if (!descriptor.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error(`${label} optional fields must use own enumerable data fields.`); if (descriptor.value !== undefined) snapshot[field] = descriptor.value } return snapshot }
function captureInventoryPeriod(value: unknown): InventoryPeriod { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Inventory period must be a structured object.'); const source = value as Record<string, unknown>; const snapshot: Record<string, unknown> = {}; for (const field of ['start', 'end', 'timeZone'] as const) { const descriptor = Object.getOwnPropertyDescriptor(source, field); if (!descriptor?.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error('Inventory period must expose start, end and timeZone as own enumerable data fields.'); snapshot[field] = descriptor.value } return { start: snapshot.start as string, end: snapshot.end as string, timeZone: snapshot.timeZone as string } }
function captureAssetPeriod(value: unknown): { start: string; end: string } { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Asset schedule period must be a structured object.'); const source = value as Record<string, unknown>; const snapshot: Record<string, unknown> = {}; for (const field of ['start', 'end'] as const) { const descriptor = Object.getOwnPropertyDescriptor(source, field); if (!descriptor?.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error('Asset schedule period must expose start and end as own enumerable data fields.'); snapshot[field] = descriptor.value } return { start: snapshot.start as string, end: snapshot.end as string } }
function deepFreeze<T>(value: T): T { if (value && typeof value === 'object' && !Object.isFrozen(value)) { for (const nested of Object.values(value)) deepFreeze(nested); Object.freeze(value) } return value }
function nonnegativeSafeInteger(value: number) { return Number.isSafeInteger(value) && value >= 0 }
function validInstant(value: unknown): value is string { return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(value) && validDateOnly(value.slice(0, 10)) && !Number.isNaN(Date.parse(value)) }
function validDateOnly(value: unknown): value is string { if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const parsed = new Date(`${value}T00:00:00.000Z`); return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value }
function validateTimeZone(value: string) { if (typeof value !== 'string' || !value.trim()) throw new Error('Inventory period timezone is invalid.'); try { new Intl.DateTimeFormat('en-US', { timeZone: value }).format(new Date(0)) } catch { throw new Error('Inventory period timezone is invalid.') } }
function localDate(instant: string, timeZone: string) { const parts = new Intl.DateTimeFormat('en-US', { timeZone, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date(instant)); const get = (type: string) => parts.find(part => part.type === type)?.value ?? ''; return `${get('year')}-${get('month')}-${get('day')}` }
function validateAsset(asset: FixedAsset) { if (!['STRAIGHT_LINE', 'NO_DEPRECIATION'].includes(asset.method) || !['STRAIGHT_LINE', 'NO_DEPRECIATION'].includes(asset.taxMethod) || ![asset.id, asset.tenantId, asset.description, asset.location].every(value => typeof value === 'string' && value.trim()) || !hasStrictEvidenceIds(asset.evidenceIds) || !nonnegativeSafeInteger(asset.costCents) || !Number.isSafeInteger(asset.usefulLifeMonths) || asset.usefulLifeMonths <= 0 || !Number.isSafeInteger(asset.taxUsefulLifeMonths) || asset.taxUsefulLifeMonths <= 0 || !validDateOnly(asset.acquisitionDate) || !validDateOnly(asset.availableForUseDate) || asset.availableForUseDate < asset.acquisitionDate) throw new Error('Asset master data, acquisition evidence, depreciation methods, useful lives, cost or lifecycle dates are invalid.') }
function normalizeAssetMaster(asset: FixedAsset): FixedAsset { if (typeof asset.location !== 'string') throw new Error('Asset master data, acquisition evidence, depreciation methods, useful lives, cost or lifecycle dates are invalid.'); let evidenceIds: readonly string[]; try { evidenceIds = captureDenseArray(asset.evidenceIds, 'Asset evidence IDs', value => value as string) } catch { throw new Error('Asset master data, acquisition evidence, depreciation methods, useful lives, cost or lifecycle dates are invalid.') } return { ...asset, location: asset.location.trim(), evidenceIds } }
function validateFiscalPeriod(period: { start: string; end: string }) { if (!validDateOnly(period.start) || !validDateOnly(period.end) || period.start > period.end) throw new Error('Authoritative fiscal period is invalid.'); const anniversary = new Date(`${period.start}T00:00:00.000Z`); anniversary.setUTCFullYear(anniversary.getUTCFullYear() + 1); if (Date.parse(`${period.end}T00:00:00.000Z`) >= anniversary.getTime()) throw new Error('Asset and inventory fiscal periods may not exceed twelve months.') }
function depreciationCumulative(asset: FixedAsset, through: string, basis: 'BOOK' | 'TAX') { const life = basis === 'BOOK' ? asset.usefulLifeMonths : asset.taxUsefulLifeMonths; if (through < asset.availableForUseDate) return 0; const start = new Date(`${asset.availableForUseDate}T00:00:00Z`); const end = new Date(`${through}T00:00:00Z`); const months = Math.min(life, Math.max(0, (end.getUTCFullYear() - start.getUTCFullYear()) * 12 + end.getUTCMonth() - start.getUTCMonth() + 1)); const numerator = BigInt(asset.costCents) * BigInt(months); const denominator = BigInt(life); const quotient = numerator / denominator; const rounded = quotient + ((numerator % denominator) * BigInt(2) >= denominator ? BigInt(1) : BigInt(0)); return Number(rounded > BigInt(asset.costCents) ? BigInt(asset.costCents) : rounded) }
function previousMonthEnd(value: string) { const date = new Date(`${value.slice(0, 7)}-01T00:00:00.000Z`); date.setUTCDate(0); return date.toISOString().slice(0, 10) }
function previousDay(value: string) { const date = new Date(`${value}T00:00:00.000Z`); date.setUTCDate(date.getUTCDate() - 1); return date.toISOString().slice(0, 10) }
function monthEnd(value: string) { const date = new Date(`${value.slice(0, 7)}-01T00:00:00.000Z`); date.setUTCMonth(date.getUTCMonth() + 1); date.setUTCDate(0); return date.toISOString().slice(0, 10) }
function addCents(left: number, right: number) { const value = left + right; if (!Number.isSafeInteger(value)) throw new Error('Subledger reconciliation arithmetic exceeds safe integer limits.'); return value }
