import { createHash } from 'node:crypto'
import { canonicalJson } from './auditExport'
import { hasStrictEvidenceIds } from './validation'
import { compareCanonicalText } from './deterministicOrder'

export interface CashBook { id: string; tenantId: string; location: string; register: string; timeZone: string; currency: 'EUR'; glAccountId: string; retainedThrough: string; entries: readonly CashEntry[]; closes: readonly DailyCashClose[] }
export interface CashEntry { id: string; sequence: number; journalEntryId: string; occurredAt: string; businessDate: string; type: 'RECEIPT' | 'PAYMENT' | 'STORNO'; amountCents: number; description: string; evidenceIds: readonly string[]; createdAt: string; createdBy: string; source: 'MANUAL' | 'POS_IMPORT'; externalId?: string; correctsEntryId?: string; replacementEntryId?: string }
export interface DailyCashClose { bookId: string; businessDate: string; openingBalanceCents: number; receiptsCents: number; paymentsCents: number; expectedBalanceCents: number; countedBalanceCents: number; differenceCents: number; resolution?: string; resolutionJournalEntryId?: string; signedBy: string; signedAt: string; approvedBy: string; approvedAt: string; entrySequenceThrough: number; entryChecksum: string; checksum: string }
export interface CashAuditFiscalYear { id: string; startDate: string; endDate: string }
type PosImportRow = { externalId: string; journalEntryId?: string; occurredAt: string; businessDate: string; type: 'RECEIPT' | 'PAYMENT'; amountCents: number; description: string; evidenceId: string }

export function addCashEntry(book: CashBook, input: Omit<CashEntry, 'id' | 'sequence'>): { book: CashBook; warnings: readonly string[]; entry: CashEntry } {
  return appendCashEntry(book, input, 'NORMAL')
}
function appendCashEntry(book: CashBook, input: Omit<CashEntry, 'id' | 'sequence'>, relation: 'NORMAL' | 'STORNO' | 'REPLACEMENT'): { book: CashBook; warnings: readonly string[]; entry: CashEntry } {
  book = snapshotCashBook(book)
  validateCloseChain(book)
  if (Object.hasOwn(input, 'externalId') && (typeof input.externalId !== 'string' || !input.externalId.trim())) throw new Error('Cash external ID must be a nonblank string when supplied.')
  const normalized = omitUndefined({ ...input, occurredAt: canonicalInstant(input.occurredAt), createdAt: canonicalInstant(input.createdAt), externalId: typeof input.externalId === 'string' ? input.externalId.trim() : input.externalId }) as Omit<CashEntry, 'id' | 'sequence'>
  validateEntry(normalized); if (!validDateOnly(normalized.businessDate) || localDate(normalized.occurredAt, book.timeZone) !== normalized.businessDate) throw new Error('Cash business date must match the source instant in the register timezone.'); if (normalized.businessDate > book.retainedThrough) throw new Error('Cash entries cannot exceed the declared retention horizon.'); if (book.closes.some(close => close.businessDate >= normalized.businessDate)) throw new Error('Closed cash days cannot be silently backdated or changed.')
  if (relation === 'NORMAL' && (Object.hasOwn(normalized, 'correctsEntryId') || Object.hasOwn(normalized, 'replacementEntryId') || normalized.type === 'STORNO')) throw new Error('Normal cash entries cannot forge correction relationship fields.')
  if (relation === 'STORNO') {
    if (normalized.replacementEntryId) throw new Error('Caller cannot preassign a Storno replacement link.')
    const original = book.entries.find(entry => entry.id === normalized.correctsEntryId)
    if (!original || original.type === 'STORNO') throw new Error('A Storno must target an existing receipt or payment in this cash book.')
    if (book.entries.some(entry => entry.type === 'STORNO' && entry.correctsEntryId === original.id)) throw new Error('The original cash entry is already cancelled.')
    if (normalized.amountCents !== original.amountCents) throw new Error('A Storno must reverse the exact original amount.')
  }
  if (relation === 'REPLACEMENT') { const original = book.entries.find(entry => entry.id === normalized.correctsEntryId); const storno = book.entries.find(entry => entry.type === 'STORNO' && entry.correctsEntryId === original?.id); if (!original || !storno || normalized.type === 'STORNO' || normalized.replacementEntryId || storno.replacementEntryId) throw new Error('Replacement must link to the matching correction workflow.') }
  const latest = book.entries.at(-1); if (latest && (Date.parse(normalized.occurredAt) < Date.parse(latest.occurredAt) || Date.parse(normalized.createdAt) < Date.parse(latest.createdAt))) throw new Error('Cash entries must be chronological and preserve append chronology without renumbering.')
  if (normalized.externalId && book.entries.some(entry => entry.source === normalized.source && entry.externalId === normalized.externalId)) throw new Error('Duplicate external POS entry.')
  const sequence = (latest?.sequence ?? 0) + 1; const id = `${book.id}:${sequence}`; const entry = deepFreeze({ ...structuredClone(normalized), id, sequence })
  const balance = calculateCashBalance({ ...book, entries: [...book.entries, entry] }); const warnings = balance < 0 ? [`Impossible negative cash balance after entry ${id}: ${balance}`] : []
  return { book: deepFreeze({ ...book, entries: [...book.entries, entry] }), warnings, entry }
}
export function correctCashEntry(book: CashBook, originalId: string, correction: Omit<CashEntry, 'id' | 'sequence' | 'type' | 'amountCents' | 'correctsEntryId' | 'replacementEntryId'>, replacement?: Omit<CashEntry, 'id' | 'sequence' | 'correctsEntryId' | 'replacementEntryId'>) {
  book = snapshotCashBook(book)
  const original = book.entries.find(entry => entry.id === originalId); if (!original || original.type === 'STORNO') throw new Error('Original cash entry does not exist or is already a cancellation.'); if (book.entries.some(entry => entry.correctsEntryId === originalId)) throw new Error('Cash entry was already corrected.')
  let result = appendCashEntry(book, { ...correction, businessDate: correction.businessDate, type: 'STORNO', amountCents: original.amountCents, correctsEntryId: original.id }, 'STORNO')
  if (!replacement) return { book: result.book, storno: result.entry, warnings: result.warnings }
  const replacementResult = appendCashEntry(result.book, { ...replacement, correctsEntryId: original.id }, 'REPLACEMENT'); const entries = replacementResult.book.entries.map(entry => entry.id === result.entry.id ? { ...entry, replacementEntryId: replacementResult.entry.id } : entry)
  const correctedBook = deepFreeze({ ...replacementResult.book, entries }); return { book: correctedBook, storno: correctedBook.entries.find(entry => entry.id === result.entry.id)!, replacement: replacementResult.entry, warnings: [...result.warnings, ...replacementResult.warnings] }
}
export function closeCashDay(book: CashBook, input: { businessDate: string; countedBalanceCents: number; resolution?: string; resolutionJournalEntryId?: string; signedBy: string; signedAt: string; approvedBy: string; approvedAt: string }) {
  book = snapshotCashBook(book)
  validateCloseChain(book)
  if (Object.hasOwn(input, 'resolution') && (typeof input.resolution !== 'string' || !input.resolution.trim())) throw new Error('Cash close resolution must be a nonblank string when supplied.')
  const normalized = omitUndefined({ businessDate: input.businessDate, countedBalanceCents: input.countedBalanceCents, resolution: input.resolution, resolutionJournalEntryId: input.resolutionJournalEntryId, signedBy: input.signedBy, signedAt: canonicalInstant(input.signedAt), approvedBy: input.approvedBy, approvedAt: canonicalInstant(input.approvedAt) }) as typeof input
  if (!validDateOnly(normalized.businessDate)) throw new Error('Cash close business date is invalid.')
  if (normalized.businessDate > book.retainedThrough) throw new Error('Cash closes cannot exceed the declared retention horizon.')
  if (book.closes.some(close => close.businessDate === normalized.businessDate)) throw new Error('Cash day is already closed.'); const prior = [...book.closes].filter(close => close.businessDate < normalized.businessDate).sort((a, b) => compareCanonicalText(b.businessDate, a.businessDate))[0]
  if (book.closes.some(close => close.businessDate > normalized.businessDate)) throw new Error('Cash days must be closed chronologically.')
  const closedDates = new Set(book.closes.map(close => close.businessDate)); const unclosedEarlierMovement = book.entries.find(entry => entry.businessDate < normalized.businessDate && !closedDates.has(entry.businessDate)); if (unclosedEarlierMovement) throw new Error(`Cash day ${unclosedEarlierMovement.businessDate} has unclosed movements and must be closed first.`)
  const openingBalanceCents = prior?.countedBalanceCents ?? 0; const entries = book.entries.filter(entry => entry.businessDate === normalized.businessDate); const receiptsCents = entries.filter(entry => entry.type === 'RECEIPT').reduce((sum, entry) => addSafe(sum, entry.amountCents), 0); const paymentsCents = entries.filter(entry => entry.type === 'PAYMENT').reduce((sum, entry) => addSafe(sum, entry.amountCents), 0); const stornoCents = entries.filter(entry => entry.type === 'STORNO').reduce((sum, entry) => { const original = book.entries.find(value => value.id === entry.correctsEntryId)!; return addSafe(sum, original.type === 'RECEIPT' ? -entry.amountCents : entry.amountCents) }, 0); const expectedBalanceCents = addSafe(addSafe(addSafe(openingBalanceCents, receiptsCents), -paymentsCents), stornoCents); const differenceCents = addSafe(normalized.countedBalanceCents, -expectedBalanceCents)
  const lastCoveredInstant = entries.reduce((latest, entry) => Math.max(latest, Date.parse(entry.occurredAt), Date.parse(entry.createdAt)), Number.NEGATIVE_INFINITY)
  const priorFinalization = prior ? closeFinalizationInstant(prior) : Number.NEGATIVE_INFINITY
  const hasResolution = Object.hasOwn(normalized, 'resolution')
  if (hasResolution && (typeof normalized.resolution !== 'string' || !normalized.resolution.trim())) throw new Error('Cash close resolution must be a nonblank string when supplied.')
  if (!Number.isSafeInteger(normalized.countedBalanceCents) || normalized.countedBalanceCents < 0) throw new Error('Counted cash must be nonnegative safe integer cents.'); if (expectedBalanceCents < 0) throw new Error('Cash day cannot close with an impossible negative expected balance.'); if (differenceCents !== 0 && (!hasResolution || typeof normalized.resolutionJournalEntryId !== 'string' || !normalized.resolutionJournalEntryId.trim())) throw new Error('Count differences require a documented resolution and posted journal reference.'); if (differenceCents === 0 && Object.hasOwn(normalized, 'resolutionJournalEntryId')) throw new Error('A matching cash count cannot claim a resolution journal reference.'); if (typeof normalized.signedBy !== 'string' || typeof normalized.approvedBy !== 'string' || !normalized.signedBy.trim() || !normalized.approvedBy.trim() || localDate(normalized.signedAt, book.timeZone) < normalized.businessDate || Date.parse(normalized.signedAt) < lastCoveredInstant || Date.parse(normalized.signedAt) > Date.parse(normalized.approvedAt) || Date.parse(normalized.signedAt) < priorFinalization || Date.parse(normalized.approvedAt) < priorFinalization) throw new Error('Cash close requires primitive signer identities and ordered signature and approval timestamps after every covered entry, business-day boundary and prior close finalization.')
  const unsigned = { ...normalized, bookId: book.id, openingBalanceCents, receiptsCents, paymentsCents, expectedBalanceCents, differenceCents, entrySequenceThrough: entries.at(-1)?.sequence ?? prior?.entrySequenceThrough ?? 0, entryChecksum: createHash('sha256').update(canonicalJson(entries.map(canonicalCashEntry))).digest('hex') }; const checksum = createHash('sha256').update(canonicalJson(unsigned)).digest('hex'); const close = deepFreeze({ ...unsigned, checksum })
  return { book: deepFreeze({ ...book, closes: [...book.closes, close] }), close }
}
export function importPosEntries(book: CashBook, rows: readonly PosImportRow[], actorId: string, importedAt: string) { const capturedRows = captureDenseRecords(rows, 'POS import rows', snapshotPosRow); let current = book; const imported: CashEntry[] = []; const warnings: string[] = []; for (const row of capturedRows) { const result = addCashEntry(current, { externalId: row.externalId, journalEntryId: row.journalEntryId ?? `cash-${row.businessDate}`, occurredAt: row.occurredAt, businessDate: row.businessDate, type: row.type, amountCents: row.amountCents, description: row.description, evidenceIds: [row.evidenceId], createdAt: importedAt, createdBy: actorId, source: 'POS_IMPORT' }); current = result.book; imported.push(result.entry); warnings.push(...result.warnings) } return { book: current, imported, warnings, scopeNotice: 'POS data import only. This cash book is not a TSE system and does not claim §146a AO/KassenSichV compliance.' } }
export function reconcileCashToGl(book: CashBook, throughDate: string, glBalanceCents: number, resolution?: { explanation: string; approvedBy: string }) { book = snapshotCashBook(book); validateCloseChain(book); if (!validDateOnly(throughDate) || !Number.isSafeInteger(glBalanceCents)) throw new Error('Cash reconciliation date or GL balance is invalid.'); const latest = [...book.closes].filter(close => close.businessDate <= throughDate).sort((a, b) => compareCanonicalText(b.businessDate, a.businessDate))[0]; if (book.entries.some(entry => entry.businessDate <= throughDate && entry.sequence > (latest?.entrySequenceThrough ?? 0))) throw new Error('Cash reconciliation requires every movement through the date to be daily closed.'); const cashBookBalanceCents = latest?.countedBalanceCents ?? 0; const differenceCents = addSafe(cashBookBalanceCents, -glBalanceCents); return { cashBookBalanceCents, glBalanceCents, differenceCents, reconciled: differenceCents === 0 || Boolean(typeof resolution?.explanation === 'string' && resolution.explanation.trim() && typeof resolution.approvedBy === 'string' && resolution.approvedBy.trim()), resolution } }
export function exportCashAudit(book: CashBook, fiscalYears?: readonly CashAuditFiscalYear[]) {
  book = snapshotCashBook(book)
  validateCloseChain(book)
  const entries = book.entries.map(canonicalCashEntry)
  const closes = book.closes.map(canonicalDailyClose)
  const payload = canonicalJson({ book: { id: book.id, tenantId: book.tenantId, location: book.location, register: book.register, timeZone: book.timeZone, currency: book.currency, glAccountId: book.glAccountId, retainedThrough: book.retainedThrough }, entries, closes, scopeNotice: 'Cash ledger; not a TSE.' })
  const resolveFiscalYear = fiscalYears === undefined ? undefined : cashFiscalYearResolver(fiscalYears)
  const records = resolveFiscalYear === undefined ? undefined : {
    cashBooks: [{ version: 1, id: book.id, tenantId: book.tenantId, location: book.location, register: book.register, timeZone: book.timeZone, currency: book.currency, glAccountId: book.glAccountId, retainedThrough: book.retainedThrough }],
    cashBookEntries: entries.map(entry => ({ tenantId: book.tenantId, cashBookId: book.id, fiscalYearId: resolveFiscalYear(entry.businessDate), ...entry })),
    cashDailyCloses: closes.map(close => ({ tenantId: book.tenantId, id: `${book.id}:${close.businessDate}`, fiscalYearId: resolveFiscalYear(close.businessDate), ...close })),
  }
  return { payload, checksum: createHash('sha256').update(payload).digest('hex'), ...(records ? { records } : {}) }
}
function canonicalCashEntry(entry: CashEntry): CashEntry { return { id: entry.id, sequence: entry.sequence, journalEntryId: entry.journalEntryId, occurredAt: entry.occurredAt, businessDate: entry.businessDate, type: entry.type, amountCents: entry.amountCents, description: entry.description, evidenceIds: [...entry.evidenceIds], createdAt: entry.createdAt, createdBy: entry.createdBy, source: entry.source, ...(entry.externalId !== undefined ? { externalId: entry.externalId } : {}), ...(entry.correctsEntryId !== undefined ? { correctsEntryId: entry.correctsEntryId } : {}), ...(entry.replacementEntryId !== undefined ? { replacementEntryId: entry.replacementEntryId } : {}) } }
function canonicalDailyClose(close: DailyCashClose): DailyCashClose { return { bookId: close.bookId, businessDate: close.businessDate, openingBalanceCents: close.openingBalanceCents, receiptsCents: close.receiptsCents, paymentsCents: close.paymentsCents, expectedBalanceCents: close.expectedBalanceCents, countedBalanceCents: close.countedBalanceCents, differenceCents: close.differenceCents, ...(close.resolution !== undefined ? { resolution: close.resolution } : {}), ...(close.resolutionJournalEntryId !== undefined ? { resolutionJournalEntryId: close.resolutionJournalEntryId } : {}), signedBy: close.signedBy, signedAt: close.signedAt, approvedBy: close.approvedBy, approvedAt: close.approvedAt, entrySequenceThrough: close.entrySequenceThrough, entryChecksum: close.entryChecksum, checksum: close.checksum } }
function snapshotCashBook(value: unknown): CashBook { const book = captureFields(value, ['id', 'tenantId', 'location', 'register', 'timeZone', 'currency', 'glAccountId', 'retainedThrough', 'entries', 'closes'], [], 'Cash book'); return { id: book.id as string, tenantId: book.tenantId as string, location: book.location as string, register: book.register as string, timeZone: book.timeZone as string, currency: book.currency as 'EUR', glAccountId: book.glAccountId as string, retainedThrough: book.retainedThrough as string, entries: captureDenseRecords(book.entries, 'Cash entries', snapshotCashEntry), closes: captureDenseRecords(book.closes, 'Cash closes', snapshotCashClose) } }
function snapshotCashEntry(value: unknown): CashEntry { const entry = captureFields(value, ['id', 'sequence', 'journalEntryId', 'occurredAt', 'businessDate', 'type', 'amountCents', 'description', 'evidenceIds', 'createdAt', 'createdBy', 'source'], ['externalId', 'correctsEntryId', 'replacementEntryId'], 'Cash entry'); let evidenceIds: readonly unknown[]; try { evidenceIds = captureDenseRecords(entry.evidenceIds, 'Cash evidence IDs', value => value) } catch { throw new Error('Cash entry requires description, actor and nonblank evidence IDs.') } return { ...entry, evidenceIds } as unknown as CashEntry }
function snapshotCashClose(value: unknown): DailyCashClose { return captureFields(value, ['bookId', 'businessDate', 'openingBalanceCents', 'receiptsCents', 'paymentsCents', 'expectedBalanceCents', 'countedBalanceCents', 'differenceCents', 'signedBy', 'signedAt', 'approvedBy', 'approvedAt', 'entrySequenceThrough', 'entryChecksum', 'checksum'], ['resolution', 'resolutionJournalEntryId'], 'Cash close') as unknown as DailyCashClose }
function snapshotPosRow(value: unknown): PosImportRow { return captureFields(value, ['externalId', 'occurredAt', 'businessDate', 'type', 'amountCents', 'description', 'evidenceId'], ['journalEntryId'], 'POS import row') as unknown as PosImportRow }
function snapshotCashFiscalYear(value: unknown): CashAuditFiscalYear { return captureFields(value, ['id', 'startDate', 'endDate'], [], 'Cash audit fiscal year') as unknown as CashAuditFiscalYear }
function captureFields(value: unknown, required: readonly string[], optional: readonly string[], label: string) { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${label} must be a structured object.`); const source = value as Record<string, unknown>; const snapshot: Record<string, unknown> = {}; for (const field of required) { const descriptor = Object.getOwnPropertyDescriptor(source, field); if (!descriptor?.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error(`${label} fields must be own enumerable data properties without accessors.`); snapshot[field] = descriptor.value } for (const field of optional) { const descriptor = Object.getOwnPropertyDescriptor(source, field); if (descriptor !== undefined) { if (!descriptor.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error(`${label} fields must be own enumerable data properties without accessors.`); snapshot[field] = descriptor.value } } return snapshot }
function captureDenseRecords<T>(value: unknown, label: string, capture: (value: unknown) => T): readonly T[] { if (!Array.isArray(value)) throw new Error(`${label} must be a dense array.`); const result: T[] = []; for (let index = 0; index < value.length; index++) { const descriptor = Object.getOwnPropertyDescriptor(value, String(index)); if (!descriptor || !Object.hasOwn(descriptor, 'value')) throw new Error(`${label} must be a dense array of own data elements.`); result.push(capture(descriptor.value)) } return result }
function deepFreeze<T>(value: T): T { if (value && typeof value === 'object' && !Object.isFrozen(value)) { for (const nested of Object.values(value as Record<string, unknown>)) deepFreeze(nested); Object.freeze(value) } return value }
function cashFiscalYearResolver(fiscalYears: readonly CashAuditFiscalYear[]) {
  const capturedFiscalYears = captureDenseRecords(fiscalYears, 'Cash audit fiscal years', snapshotCashFiscalYear); if (capturedFiscalYears.length === 0) throw new Error('Cash audit dataset records require authoritative fiscal years.')
  for (const period of capturedFiscalYears) if (typeof period.id !== 'string' || !period.id.trim() || typeof period.startDate !== 'string' || typeof period.endDate !== 'string' || !validDateOnly(period.startDate) || !validDateOnly(period.endDate) || period.startDate > period.endDate) throw new Error('Cash audit fiscal years must have primitive nonblank IDs and valid non-overlapping periods of at most twelve months.')
  const ordered = [...capturedFiscalYears].sort((left, right) => compareCanonicalText(left.startDate, right.startDate) || compareCanonicalText(left.endDate, right.endDate) || compareCanonicalText(left.id, right.id))
  if (new Set(ordered.map(period => period.id)).size !== ordered.length) throw new Error('Cash audit fiscal years must have unique IDs.')
  for (let index = 0; index < ordered.length; index++) { const period = ordered[index]; const anniversary = new Date(`${period.startDate}T00:00:00.000Z`); anniversary.setUTCFullYear(anniversary.getUTCFullYear() + 1); if (Date.parse(`${period.endDate}T00:00:00.000Z`) >= anniversary.getTime() || (index > 0 && period.startDate <= ordered[index - 1].endDate)) throw new Error('Cash audit fiscal years must have primitive nonblank IDs and valid non-overlapping periods of at most twelve months.') }
  return (businessDate: string) => { const matches = ordered.filter(period => period.startDate <= businessDate && businessDate <= period.endDate); if (matches.length !== 1) throw new Error(`Cash audit business date ${businessDate} is not covered by exactly one authoritative fiscal year.`); return matches[0].id }
}
function calculateCashBalance(book: CashBook) { const latestClose = [...book.closes].sort((a, b) => compareCanonicalText(b.businessDate, a.businessDate) || b.entrySequenceThrough - a.entrySequenceThrough)[0]; return book.entries.filter(entry => entry.sequence > (latestClose?.entrySequenceThrough ?? 0)).reduce((sum, entry) => { if (entry.type === 'RECEIPT') return addSafe(sum, entry.amountCents); if (entry.type === 'PAYMENT') return addSafe(sum, -entry.amountCents); const original = book.entries.find(value => value.id === entry.correctsEntryId); return addSafe(sum, original?.type === 'RECEIPT' ? -entry.amountCents : entry.amountCents) }, latestClose?.countedBalanceCents ?? 0) }
function validateEntry(input: Omit<CashEntry, 'id' | 'sequence'>) { if (!['RECEIPT', 'PAYMENT', 'STORNO'].includes(input.type) || !['MANUAL', 'POS_IMPORT'].includes(input.source)) throw new Error('Cash entry type and source must be supported runtime enum values.'); if (!Number.isSafeInteger(input.amountCents) || input.amountCents <= 0) throw new Error('Cash amount must be positive integer cents.'); if (!validTimestamp(input.occurredAt) || !validTimestamp(input.createdAt) || Date.parse(input.createdAt) < Date.parse(input.occurredAt)) throw new Error('Cash entry has an invalid timestamp or was created before it occurred.'); if (typeof input.journalEntryId !== 'string' || !input.journalEntryId.trim()) throw new Error('Cash entry requires a posted journal reference.'); if (typeof input.description !== 'string' || typeof input.createdBy !== 'string' || !input.description.trim() || !input.createdBy.trim() || !hasStrictEvidenceIds(input.evidenceIds)) throw new Error('Cash entry requires primitive description, actor and nonblank evidence IDs.'); if (Object.hasOwn(input, 'externalId') && (typeof input.externalId !== 'string' || !input.externalId.trim() || input.externalId !== input.externalId.trim())) throw new Error('Cash external ID must be a nonblank canonical string when supplied.'); for (const field of ['correctsEntryId', 'replacementEntryId'] as const) if (Object.hasOwn(input, field) && (typeof input[field] !== 'string' || !input[field].trim())) throw new Error('Cash correction relationship IDs must be nonblank strings when supplied.'); if (input.type === 'STORNO' && !input.correctsEntryId) throw new Error('A Storno must link to its original entry.'); if (input.source === 'POS_IMPORT' && !Object.hasOwn(input, 'externalId')) throw new Error('POS imports require a nonempty external ID.') }
function validTimestamp(value: string) { return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(value) && validDateOnly(value.slice(0, 10)) && !Number.isNaN(Date.parse(value)) }
function canonicalInstant(value: string) { if (!validTimestamp(value)) throw new Error('Timestamp is invalid.'); return new Date(value).toISOString() }
function validDateOnly(value: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const parsed = new Date(`${value}T00:00:00.000Z`); return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value }
function localDate(instant: string, timeZone: string) { try { const parts = new Intl.DateTimeFormat('en-US', { timeZone, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date(instant)); const get = (type: string) => parts.find(part => part.type === type)?.value ?? ''; return `${get('year')}-${get('month')}-${get('day')}` } catch { throw new Error('Cash register timezone is invalid.') } }
function addSafe(left: number, right: number) { const value = left + right; if (!Number.isSafeInteger(value)) throw new Error('Cash arithmetic exceeds safe integer limits.'); return value }
function omitUndefined<T extends Record<string, unknown>>(value: T) { return Object.fromEntries(Object.entries(value).filter(([, nested]) => nested !== undefined)) }
function validateCloseChain(book: CashBook) {
  validateCashBook(book)
  const externalIds = new Set<string>()
  for (let index = 0; index < book.entries.length; index++) {
    const entry = book.entries[index]
    if (!Number.isSafeInteger(entry.sequence) || entry.sequence !== index + 1 || entry.id !== `${book.id}:${entry.sequence}`) throw new Error('Persisted cash entries require positive unique contiguous sequences and derived IDs.')
    if (!['RECEIPT', 'PAYMENT', 'STORNO'].includes(entry.type) || !['MANUAL', 'POS_IMPORT'].includes(entry.source)) throw new Error('Persisted cash entry type or source is invalid.')
    validateEntry(entry)
    if (entry.occurredAt !== canonicalInstant(entry.occurredAt) || entry.createdAt !== canonicalInstant(entry.createdAt) || !validDateOnly(entry.businessDate) || localDate(entry.occurredAt, book.timeZone) !== entry.businessDate) throw new Error('Persisted cash entry timestamps or register business date are invalid.')
    if (index && (Date.parse(entry.occurredAt) < Date.parse(book.entries[index - 1].occurredAt) || Date.parse(entry.createdAt) < Date.parse(book.entries[index - 1].createdAt))) throw new Error('Persisted cash entries do not preserve occurrence and append chronology.')
    if (entry.externalId) { const key = `${entry.source}\u0000${entry.externalId}`; if (externalIds.has(key)) throw new Error('Persisted cash entries contain duplicate source IDs.'); externalIds.add(key) }
    if (entry.type === 'STORNO') {
      const original = book.entries.slice(0, index).find(value => value.id === entry.correctsEntryId)
      if (!original || original.type === 'STORNO' || entry.amountCents !== original.amountCents || book.entries.slice(0, index).some(value => value.type === 'STORNO' && value.correctsEntryId === original.id)) throw new Error('Persisted cash correction links are invalid.')
      if (entry.replacementEntryId) { const replacement = book.entries.slice(index + 1).find(value => value.id === entry.replacementEntryId); if (!replacement || replacement.type === 'STORNO' || replacement.correctsEntryId !== original.id) throw new Error('Persisted cash correction replacement link is invalid.') }
    } else if (entry.correctsEntryId) {
      const original = book.entries.slice(0, index).find(value => value.id === entry.correctsEntryId)
      const storno = book.entries.slice(0, index).find(value => value.type === 'STORNO' && value.correctsEntryId === original?.id)
      if (!original || !storno || storno.replacementEntryId !== entry.id || entry.replacementEntryId) throw new Error('Persisted replacement entry is not bound to its Storno workflow.')
    } else if (entry.replacementEntryId) throw new Error('Persisted normal cash entry cannot carry a replacement link.')
  }
  let priorDate = ''; let priorSequence = 0; let priorClose: DailyCashClose | undefined
  for (const close of book.closes) {
    if (close.bookId !== book.id || !validDateOnly(close.businessDate) || close.businessDate <= priorDate || !Number.isSafeInteger(close.entrySequenceThrough) || close.entrySequenceThrough < priorSequence || close.entrySequenceThrough > book.entries.length) throw new Error('Persisted cash close chain is invalid.')
    const covered = book.entries.filter(entry => entry.sequence > priorSequence && entry.sequence <= close.entrySequenceThrough)
    const dated = book.entries.filter(entry => entry.businessDate === close.businessDate)
    const expectedThrough = dated.at(-1)?.sequence ?? priorSequence
    if (covered.some(entry => entry.businessDate !== close.businessDate) || dated.length !== covered.length || expectedThrough !== close.entrySequenceThrough || dated.some((entry, index) => entry !== covered[index])) throw new Error('Persisted cash close does not cover every dated entry exactly once.')
    const openingBalanceCents = priorClose?.countedBalanceCents ?? 0
    const receiptsCents = covered.filter(entry => entry.type === 'RECEIPT').reduce((sum, entry) => addSafe(sum, entry.amountCents), 0)
    const paymentsCents = covered.filter(entry => entry.type === 'PAYMENT').reduce((sum, entry) => addSafe(sum, entry.amountCents), 0)
    const stornoCents = covered.filter(entry => entry.type === 'STORNO').reduce((sum, entry) => { const original = book.entries.find(value => value.id === entry.correctsEntryId)!; return addSafe(sum, original.type === 'RECEIPT' ? -entry.amountCents : entry.amountCents) }, 0)
    const expectedBalanceCents = addSafe(addSafe(addSafe(openingBalanceCents, receiptsCents), -paymentsCents), stornoCents)
    if (!Number.isSafeInteger(close.countedBalanceCents) || close.countedBalanceCents < 0) throw new Error('Persisted cash close counted balance is invalid.')
    const differenceCents = addSafe(close.countedBalanceCents, -expectedBalanceCents)
    if (close.openingBalanceCents !== openingBalanceCents || close.receiptsCents !== receiptsCents || close.paymentsCents !== paymentsCents || close.expectedBalanceCents !== expectedBalanceCents || close.differenceCents !== differenceCents) throw new Error('Persisted cash close financial totals do not reconcile to covered entries and prior close.')
    const hasResolution = Object.hasOwn(close, 'resolution')
    if (hasResolution && (typeof close.resolution !== 'string' || !close.resolution.trim())) throw new Error('Persisted cash close resolution must be a nonblank string when supplied.')
    if (expectedBalanceCents < 0 || (differenceCents !== 0 && (!hasResolution || typeof close.resolutionJournalEntryId !== 'string' || !close.resolutionJournalEntryId.trim())) || (differenceCents === 0 && close.resolutionJournalEntryId !== undefined)) throw new Error('Persisted cash close has an impossible balance or undocumented/unposted difference.')
    const lastCoveredInstant = covered.reduce((latest, entry) => Math.max(latest, Date.parse(entry.occurredAt), Date.parse(entry.createdAt)), Number.NEGATIVE_INFINITY)
    const priorFinalization = priorClose ? closeFinalizationInstant(priorClose) : Number.NEGATIVE_INFINITY
    if (typeof close.signedBy !== 'string' || typeof close.approvedBy !== 'string' || !close.signedBy.trim() || !close.approvedBy.trim() || !validTimestamp(close.signedAt) || !validTimestamp(close.approvedAt) || close.signedAt !== canonicalInstant(close.signedAt) || close.approvedAt !== canonicalInstant(close.approvedAt) || localDate(close.signedAt, book.timeZone) < close.businessDate || Date.parse(close.signedAt) < lastCoveredInstant || Date.parse(close.signedAt) > Date.parse(close.approvedAt) || Date.parse(close.signedAt) < priorFinalization || Date.parse(close.approvedAt) < priorFinalization) throw new Error('Persisted cash close signature chronology or prior-finalization chronology is invalid.')
    const entryChecksum = createHash('sha256').update(canonicalJson(covered.map(canonicalCashEntry))).digest('hex'); const { checksum, ...unsigned } = canonicalDailyClose(close); const expected = createHash('sha256').update(canonicalJson(unsigned)).digest('hex')
    if (entryChecksum !== close.entryChecksum || checksum !== expected) throw new Error('Persisted cash close or covered-entry checksum is invalid.')
    priorDate = close.businessDate; priorSequence = close.entrySequenceThrough; priorClose = close
  }
  if (priorClose && book.entries.some(entry => entry.sequence > priorSequence && entry.businessDate <= priorDate)) throw new Error('Persisted cash entries after the final close cannot target an already closed business date.')
}
function closeFinalizationInstant(close: Pick<DailyCashClose, 'signedAt' | 'approvedAt'>) { return Math.max(Date.parse(close.signedAt), Date.parse(close.approvedAt)) }
function validateCashBook(book: CashBook) { const nonblank = (value: unknown) => typeof value === 'string' && Boolean(value.trim()); if (!nonblank(book.id) || !nonblank(book.tenantId) || !nonblank(book.location) || !nonblank(book.register) || !nonblank(book.glAccountId) || !nonblank(book.timeZone) || book.currency !== 'EUR' || !validDateOnly(book.retainedThrough)) throw new Error('Cash book metadata, EUR currency, account or retention date is invalid.'); if ([...book.entries, ...book.closes].some(record => record.businessDate > book.retainedThrough)) throw new Error('Cash records exceed the declared retention horizon.'); try { new Intl.DateTimeFormat('en-US', { timeZone: book.timeZone }).format(new Date(0)) } catch { throw new Error('Cash book timezone is invalid.') } }
