import { createHash } from 'node:crypto'
import { canonicalJson } from './auditExport'
import { hasDenseNonblankStrings, hasDenseOwnElements, hasStrictEvidenceIds } from './validation'
import { compareCanonicalText, compareDottedVersions } from './deterministicOrder'

export interface TaxonomyRelease { version: string; validForFiscalPeriodsStartingFrom: string; validForFiscalPeriodsStartingThrough: string; gaapNamespace: string; gcdNamespace: string; entryPoint: string; archiveSha256: string; successorVersion?: string }
export interface EBalanceProfile { tenantId: string; companyName: string; legalForm: string; taxNumber: string; fiscalPeriodStart: string; fiscalPeriodEnd: string; accountingStandard: 'HGB' | 'OTHER'; incomeStatementMethod: 'GKV' | 'UKV'; statementType: 'E' | 'K' | 'PB'; reportStatus: 'E' | 'F'; consolidationRange: 'EA' | 'KA'; incomeClassification: string; specialBalanceRequired?: boolean; supplementaryBalanceRequired?: boolean }
export interface TaxAdjustment { id: string; accountId: string; description: string; type: 'PERMANENT' | 'TEMPORARY'; amountCents: number; evidenceIds: readonly string[] }
export interface EBalanceFact { concept: string; context: 'instant' | 'duration'; amountCents: number | null; unit: 'EUR'; nilReason?: string; accountIds: readonly string[] }
export interface EBalanceSupportingBalance { id: string; kind: 'SPECIAL_BALANCE' | 'SUPPLEMENTARY_BALANCE'; tenantId: string; fiscalPeriodStart: string; fiscalPeriodEnd: string; facts: readonly EBalanceFact[]; reconciliation: readonly { id: string; accountId: string; description: string; commercialAmountCents: number; taxAmountCents: number; differenceCents: number; evidenceIds: readonly string[] }[] }
export interface EBalanceAssetScheduleRow { assetId: string; description: string; openingCostCents: number; additionsCents: number; acquisitionCostTransfersCents: number; disposalsCents: number; closingCostCents: number; costCents: number; openingAccumulatedDepreciationCents: number; currentDepreciationCents: number; impairmentsCents: number; reversalsCents: number; accumulatedDepreciationTransfersCents: number; depreciationRemovedOnDisposalCents: number; closingAccumulatedDepreciationCents: number; accumulatedDepreciationCents: number; carryingAmountCents: number; transferEventIds: readonly string[]; location: string }
export interface EBalanceAssetRegisterRow { assetId: string; acquisitionDate: string; taxValueCents: number; bookTaxDifferenceCents: number; evidenceIds: readonly string[] }
export interface EBalanceAssetEnvelope<Row> { tenantId: string; fiscalPeriodStart: string; fiscalPeriodEnd: string; rows: readonly Row[] }
export interface EBalanceAttachments { assetSchedule: EBalanceAssetEnvelope<EBalanceAssetScheduleRow>; assetRegister: EBalanceAssetEnvelope<EBalanceAssetRegisterRow>; specialBalance?: EBalanceSupportingBalance; supplementaryBalance?: EBalanceSupportingBalance }
export interface EBalanceXmlSerializer { serialize(payload: Readonly<Record<string, unknown>>): string; parseRoot(xml: string): { wellFormed: boolean; localName: string; namespaceUri: string } }
const CANONICAL_PAYLOAD_NAMESPACE = 'urn:sanjo:accounting:e-bilanz:canonical-payload'
export function createEBalancePayloadEvidence(payload: Readonly<Record<string, unknown>>) { return canonicalPayloadEvidence(canonicalJson(payload)) }
export function createEBalanceSemanticFacts(payload: Readonly<Record<string, unknown>>) { const gcd = payload.gcd as Record<string, unknown>; const taxonomy = payload.taxonomy as Record<string, unknown>; const namespaces = taxonomy.namespaces as Record<string, unknown>; const contexts = payload.contexts as Record<string, unknown>; const duration = contexts.duration as Record<string, unknown>; const facts = payload.facts as readonly Record<string, unknown>[]; const schemaRef = `<link:schemaRef xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="${xmlEscape(String(taxonomy.entryPoint))}"/>`; const durationContext = `<xbrli:context xmlns:xbrli="http://www.xbrl.org/2003/instance" id="accounting-duration"><xbrli:entity><xbrli:identifier scheme="urn:sanjo:tenant">${xmlEscape(String(gcd.tenantId))}</xbrli:identifier></xbrli:entity><xbrli:period><xbrli:startDate>${xmlEscape(String(duration.start))}</xbrli:startDate><xbrli:endDate>${xmlEscape(String(duration.end))}</xbrli:endDate></xbrli:period></xbrli:context>`; const instantContext = `<xbrli:context xmlns:xbrli="http://www.xbrl.org/2003/instance" id="accounting-instant"><xbrli:entity><xbrli:identifier scheme="urn:sanjo:tenant">${xmlEscape(String(gcd.tenantId))}</xbrli:identifier></xbrli:entity><xbrli:period><xbrli:instant>${xmlEscape(String(contexts.instant))}</xbrli:instant></xbrli:period></xbrli:context>`; const unit = '<xbrli:unit xmlns:xbrli="http://www.xbrl.org/2003/instance" id="EUR"><xbrli:measure xmlns:iso4217="http://www.xbrl.org/2003/iso4217">iso4217:EUR</xbrli:measure></xbrli:unit>'; const factXml = facts.map(fact => { const concept = String(fact.concept); const attributes = `xmlns:gaap="${xmlEscape(String(namespaces.gaap))}" contextRef="accounting-${xmlEscape(String(fact.context))}" unitRef="EUR" decimals="2" data-account-ids="${Buffer.from(canonicalJson(fact.accountIds), 'utf8').toString('base64')}"`; return fact.amountCents === null ? `<gaap:${concept} ${attributes} xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true" data-nil-reason="${Buffer.from(String(fact.nilReason), 'utf8').toString('base64')}"/>` : `<gaap:${concept} ${attributes}>${centsToEuro(Number(fact.amountCents))}</gaap:${concept}>` }).join(''); const reportPayload = `<accounting:reportPayload xmlns:accounting="${CANONICAL_PAYLOAD_NAMESPACE}" contextRef="accounting-duration" encoding="base64">${Buffer.from(canonicalJson(payload), 'utf8').toString('base64')}</accounting:reportPayload>`; return `${schemaRef}${durationContext}${instantContext}${unit}${factXml}${reportPayload}` }

export function createEBalanceAssetAttachments(profile: Pick<EBalanceProfile, 'tenantId' | 'fiscalPeriodStart' | 'fiscalPeriodEnd'>, assetSchedule: readonly EBalanceAssetScheduleRow[] = [], assetRegister: readonly EBalanceAssetRegisterRow[] = []): Pick<EBalanceAttachments, 'assetSchedule' | 'assetRegister'> {
  const capturedProfile = captureOwnDataRecord(profile, ['tenantId', 'fiscalPeriodStart', 'fiscalPeriodEnd'], [], 'E-Bilanz attachment profile')
  const envelope = { tenantId: capturedProfile.tenantId as string, fiscalPeriodStart: capturedProfile.fiscalPeriodStart as string, fiscalPeriodEnd: capturedProfile.fiscalPeriodEnd as string }
  return { assetSchedule: { ...envelope, rows: assetSchedule }, assetRegister: { ...envelope, rows: assetRegister } }
}

export function selectTaxonomy(registry: readonly TaxonomyRelease[], fiscalPeriodStart: string, requestedVersion?: string) {
  if (!validDateOnly(fiscalPeriodStart)) throw new Error('Fiscal period start must be a strict real date.')
  if (requestedVersion !== undefined && (typeof requestedVersion !== 'string' || !/^\d+(?:\.\d+)+$/.test(requestedVersion.trim()))) throw new Error('Requested taxonomy version must use the numeric dotted grammar when supplied.')
  const normalizedRegistry = validateTaxonomyRegistry(registry)
  const eligible = normalizedRegistry.filter(item => item.validForFiscalPeriodsStartingFrom <= fiscalPeriodStart && fiscalPeriodStart <= item.validForFiscalPeriodsStartingThrough)
  const selected = requestedVersion !== undefined ? eligible.find(item => compareDottedVersions(item.version, requestedVersion.trim()) === 0) : [...eligible].sort((a, b) => compareDottedVersions(b.version, a.version))[0]
  if (!selected) throw new Error(`No effective official taxonomy supports period start ${fiscalPeriodStart}.`)
  return selected
}
export function planTaxonomyUpgrade(registry: readonly TaxonomyRelease[], currentVersion: string) { if (typeof currentVersion !== 'string' || !/^\d+(?:\.\d+)+$/.test(currentVersion.trim())) throw new Error('Current taxonomy version must use the numeric dotted grammar.'); const normalizedRegistry = validateTaxonomyRegistry(registry); const current = normalizedRegistry.find(item => compareDottedVersions(item.version, currentVersion.trim()) === 0); if (!current) throw new Error('Current taxonomy is not registered.'); return current.successorVersion ? normalizedRegistry.find(item => compareDottedVersions(item.version, current.successorVersion!) === 0) ?? (() => { throw new Error('Registered successor is missing.') })() : null }

export function createEBalanceReport(profile: EBalanceProfile, taxonomy: TaxonomyRelease, commercialFacts: readonly EBalanceFact[], adjustments: readonly TaxAdjustment[], attachments: EBalanceAttachments, serializer: EBalanceXmlSerializer) {
  const normalizedProfile = captureEBalanceProfile(profile); const normalizedTaxonomy = normalizeTaxonomy(captureTaxonomy(taxonomy)); const capturedAttachments = captureAttachments(attachments); const capturedFacts = captureArrayValues<EBalanceFact>(commercialFacts, 'E-Bilanz facts'); const capturedAdjustments = captureArrayValues<TaxAdjustment>(adjustments, 'Tax adjustments'); const capturedSerializer = captureOwnDataRecord(serializer, ['serialize', 'parseRoot'], [], 'E-Bilanz serializer') as unknown as EBalanceXmlSerializer
  if (![normalizedProfile.tenantId, normalizedProfile.companyName, normalizedProfile.taxNumber, normalizedProfile.legalForm, normalizedProfile.incomeClassification].every(value => typeof value === 'string' && value.trim())) throw new Error('Authoritative company profile is incomplete.')
  if (!['HGB', 'OTHER'].includes(normalizedProfile.accountingStandard) || !['GKV', 'UKV'].includes(normalizedProfile.incomeStatementMethod) || !['E', 'K', 'PB'].includes(normalizedProfile.statementType) || !['E', 'F'].includes(normalizedProfile.reportStatus) || !['EA', 'KA'].includes(normalizedProfile.consolidationRange)) throw new Error('E-Bilanz profile contains an unsupported runtime enum value.')
  if ((normalizedProfile.specialBalanceRequired !== undefined && typeof normalizedProfile.specialBalanceRequired !== 'boolean') || (normalizedProfile.supplementaryBalanceRequired !== undefined && typeof normalizedProfile.supplementaryBalanceRequired !== 'boolean')) throw new Error('E-Bilanz supporting-balance requirement flags must be strict booleans when defined.')
  if (!validDateOnly(normalizedProfile.fiscalPeriodStart) || !validDateOnly(normalizedProfile.fiscalPeriodEnd) || normalizedProfile.fiscalPeriodStart > normalizedProfile.fiscalPeriodEnd) throw new Error('Fiscal period start/end are invalid or reversed.')
  const periodAnniversary = new Date(`${normalizedProfile.fiscalPeriodStart}T00:00:00.000Z`); periodAnniversary.setUTCFullYear(periodAnniversary.getUTCFullYear() + 1); if (Date.parse(`${normalizedProfile.fiscalPeriodEnd}T00:00:00.000Z`) >= periodAnniversary.getTime()) throw new Error('E-Bilanz fiscal period may not exceed twelve months.')
  validateTaxonomyIdentity(normalizedTaxonomy)
  if (!validDateOnly(normalizedTaxonomy.validForFiscalPeriodsStartingFrom) || !validDateOnly(normalizedTaxonomy.validForFiscalPeriodsStartingThrough) || normalizedTaxonomy.validForFiscalPeriodsStartingFrom > normalizedTaxonomy.validForFiscalPeriodsStartingThrough) throw new Error('Taxonomy effective period is invalid.')
  if (normalizedProfile.fiscalPeriodStart < normalizedTaxonomy.validForFiscalPeriodsStartingFrom || normalizedProfile.fiscalPeriodStart > normalizedTaxonomy.validForFiscalPeriodsStartingThrough) throw new Error(`Taxonomy ${normalizedTaxonomy.version} is not effective for report period start ${normalizedProfile.fiscalPeriodStart}.`)
  if (normalizedProfile.specialBalanceRequired || capturedAttachments.specialBalance !== undefined) validateSupportingBalance(capturedAttachments.specialBalance, 'SPECIAL_BALANCE', normalizedProfile)
  if (normalizedProfile.supplementaryBalanceRequired || capturedAttachments.supplementaryBalance !== undefined) validateSupportingBalance(capturedAttachments.supplementaryBalance, 'SUPPLEMENTARY_BALANCE', normalizedProfile)
  validateAssetAttachments(capturedAttachments, normalizedProfile)
  validateFacts(capturedFacts)
  const normalizedFacts = capturedFacts.map(normalizeFact)
  if (normalizedFacts.filter(fact => fact.concept === 'is.netIncome' && fact.context === 'duration').length !== 1) throw new Error('Exactly one duration net-income fact is required.')
  const normalizedAdjustments = capturedAdjustments.map(normalizeTaxAdjustment)
  if (new Set(normalizedAdjustments.map(adjustment => adjustment.id)).size !== normalizedAdjustments.length) throw new Error('Tax adjustments require nonempty unique IDs and account IDs.')
  const orderedAdjustments = normalizedAdjustments.sort((left, right) => compareCanonicalText(left.id, right.id))
  const permanentAdjustmentsCents = sumSafe(orderedAdjustments.filter(item => item.type === 'PERMANENT').map(item => item.amountCents)); const temporaryAdjustmentsCents = sumSafe(orderedAdjustments.filter(item => item.type === 'TEMPORARY').map(item => item.amountCents)); const totalAdjustmentsCents = addSafe(permanentAdjustmentsCents, temporaryAdjustmentsCents); const commercialNetIncomeCents = normalizedFacts.find(fact => fact.concept === 'is.netIncome' && fact.context === 'duration')!.amountCents; if (!Number.isSafeInteger(commercialNetIncomeCents)) throw new Error('Commercial net income must be a non-nil safe integer for tax reconciliation.'); const taxNetIncomeCents = addSafe(commercialNetIncomeCents!, totalAdjustmentsCents)
  const normalizedAttachments: EBalanceAttachments = { assetSchedule: normalizeAssetScheduleEnvelope(capturedAttachments.assetSchedule), assetRegister: normalizeAssetRegisterEnvelope(capturedAttachments.assetRegister), ...(capturedAttachments.specialBalance !== undefined ? { specialBalance: normalizeSupportingBalance(capturedAttachments.specialBalance) } : {}), ...(capturedAttachments.supplementaryBalance !== undefined ? { supplementaryBalance: normalizeSupportingBalance(capturedAttachments.supplementaryBalance) } : {}) }
  const payload = { taxonomy: { version: normalizedTaxonomy.version, archiveSha256: normalizedTaxonomy.archiveSha256, namespaces: { gaap: normalizedTaxonomy.gaapNamespace, gcd: normalizedTaxonomy.gcdNamespace }, entryPoint: normalizedTaxonomy.entryPoint }, gcd: normalizedProfile, contexts: { duration: { start: normalizedProfile.fiscalPeriodStart, end: normalizedProfile.fiscalPeriodEnd }, instant: normalizedProfile.fiscalPeriodEnd }, facts: normalizedFacts.sort((a, b) => compareCanonicalText(a.concept, b.concept) || compareCanonicalText(a.context, b.context)), taxReconciliation: { method: 'UEBERLEITUNGSRECHNUNG', commercialNetIncomeCents, permanentAdjustmentsCents, temporaryAdjustmentsCents, taxNetIncomeCents, adjustments: orderedAdjustments }, attachments: normalizedAttachments }
  const canonicalPayload = canonicalJson(payload)
  const returnedPayload = deepFreeze(JSON.parse(canonicalPayload)) as typeof payload
  const serializerPayload = deepFreeze(JSON.parse(canonicalPayload)) as Readonly<Record<string, unknown>>
  if (typeof capturedSerializer.serialize !== 'function' || typeof capturedSerializer.parseRoot !== 'function') throw new Error('E-Bilanz serializer must expose own data functions.')
  const content = capturedSerializer.serialize.call(serializer, serializerPayload)
  const parsedRootResponse = typeof content === 'string' ? capturedSerializer.parseRoot.call(serializer, content) : null
  const parsed = parsedRootResponse === null ? null : normalizeParsedRoot(parsedRootResponse)
  if (!parsed || parsed.wellFormed !== true || parsed.localName !== 'xbrl' || parsed.namespaceUri !== 'http://www.xbrl.org/2003/instance') throw new Error('E-Bilanz serializer must return complete parser-verified namespace-valid XBRL XML bytes.')
  const xmlDeclaration = content.match(/^\s*<\?xml\b[^?]*\?>/i)?.[0]; if (xmlDeclaration && !/\bencoding\s*=\s*(["'])UTF-8\1/i.test(xmlDeclaration)) throw new Error('E-Bilanz XML declarations must explicitly declare UTF-8 transmission encoding.')
  const payloadEvidence = canonicalPayloadEvidence(canonicalPayload)
  if (!containsCanonicalPayloadEvidence(content, payloadEvidence)) throw new Error('E-Bilanz serializer output must contain the exact canonical report payload evidence.')
  if (!containsExactCanonicalXbrlBody(content, createEBalanceSemanticFacts(serializerPayload), payloadEvidence)) throw new Error('Serialized XBRL must contain exactly the canonical schema reference, contexts, unit, report facts and payload evidence without additional semantic content.')
  return { payload: returnedPayload, content, transmittedBytes: new TextEncoder().encode(content), checksum: createHash('sha256').update(content, 'utf8').digest('hex') }
}
export interface EBalanceDiagnostic { code: string; severity: string; message: string; path?: string }
export interface EricValidator { validate(content: string): Promise<{ valid: boolean; diagnostics: readonly EBalanceDiagnostic[]; engineVersion: string }> }
export async function validateWithEric(report: { content: string; transmittedBytes: Uint8Array; checksum: string }, validator: EricValidator, validatedAt: string) { if (!validInstant(validatedAt)) throw new Error('ERIC validation timestamp is invalid.'); const reportSnapshot = captureOwnDataRecord(report, ['content', 'transmittedBytes', 'checksum'], [], 'E-Bilanz report') as unknown as typeof report; const validatorSnapshot = captureOwnDataRecord(validator, ['validate'], [], 'ERIC validation adapter') as unknown as EricValidator; if (typeof reportSnapshot.content !== 'string' || !(reportSnapshot.transmittedBytes instanceof Uint8Array) || typeof reportSnapshot.checksum !== 'string' || typeof validatorSnapshot.validate !== 'function') throw new Error('ERIC validation inputs are malformed.'); const bytes = new TextEncoder().encode(reportSnapshot.content); if (Buffer.compare(Buffer.from(bytes), Buffer.from(reportSnapshot.transmittedBytes)) !== 0 || createHash('sha256').update(bytes).digest('hex') !== reportSnapshot.checksum) throw new Error('E-Bilanz transmitted bytes or checksum do not match report content.'); const adapterValue = await validatorSnapshot.validate.call(validator, reportSnapshot.content); let result: Record<string, unknown>; try { result = captureOwnDataRecord(adapterValue, ['valid', 'engineVersion', 'diagnostics'], [], 'ERIC validation adapter response') } catch { throw new Error('ERIC validation adapter returned a malformed response contract.') } if (typeof result.valid !== 'boolean' || typeof result.engineVersion !== 'string' || !result.engineVersion.trim()) throw new Error('ERIC validation adapter returned a malformed response contract.'); const diagnostics = normalizeDiagnostics(result.diagnostics, 'ERIC validation adapter'); return { reportChecksum: reportSnapshot.checksum, validatedAt: new Date(validatedAt).toISOString(), engineVersion: result.engineVersion, valid: result.valid, diagnostics: diagnostics.map(item => ({ ...item, reportChecksum: reportSnapshot.checksum })) } }
export interface EBalanceSubmissionVersion { id: string; version: number; reportChecksum: string; status: 'PREPARED' | 'ACCEPTED' | 'REJECTED' | 'SUPERSEDED'; supersedesId?: string; immutableReceipt?: string }
interface NormalizedEricReceipt { receivedAt: string; transmissionId: string; reportChecksum: string; status: 'ACCEPTED' | 'REJECTED'; diagnostics: readonly EBalanceDiagnostic[] }
export interface EricSubmissionAuthority { readonly __ericSubmissionAuthority: unique symbol }
interface EricSubmissionState { submissions: Map<string, EBalanceSubmissionVersion>; transmissions: Map<string, string> }
const ericSubmissionStores = new WeakMap<object, EricSubmissionState>()
export function createEricSubmissionAuthority(): EricSubmissionAuthority { const authority = Object.freeze(Object.create(null)) as EricSubmissionAuthority; ericSubmissionStores.set(authority, { submissions: new Map(), transmissions: new Map() }); return authority }
export function createAmendedSubmission(previous: EBalanceSubmissionVersion, reportChecksum: string, authority: EricSubmissionAuthority) { const state = requireEricSubmissionState(authority); const previousSnapshot = normalizeSubmission(previous); verifyAcceptedSubmission(previousSnapshot, authority); if (typeof reportChecksum !== 'string' || !reportChecksum.trim()) throw new Error('Amended report checksum is required.'); const attempts = [...state.submissions.values()].filter(submission => submission.supersedesId === previousSnapshot.id); if (attempts.some(submission => submission.status === 'PREPARED')) throw new Error('A trusted prepared amendment already exists for this accepted submission.'); const latestVersion = attempts.reduce((latest, submission) => Math.max(latest, submission.version), previousSnapshot.version); const nextVersion = nextSubmissionVersion(latestVersion); const amendment = { id: `${previousSnapshot.id}:amendment:${nextVersion}`, version: nextVersion, reportChecksum, status: 'PREPARED' as const, supersedesId: previousSnapshot.id }; if (state.submissions.has(amendment.id)) throw new Error('Trusted ERiC submission state already contains this amendment identity.'); state.submissions.set(amendment.id, structuredClone(amendment)); return { previous: previousSnapshot, amendment } }
export function recordSubmissionReceipt(submission: EBalanceSubmissionVersion, receipt: { receivedAt: string; transmissionId: string; reportChecksum: string; status: 'ACCEPTED' | 'REJECTED'; diagnostics: readonly unknown[] }, authority: EricSubmissionAuthority) { const snapshot = normalizeSubmission(submission); if (snapshot.supersedesId !== undefined) throw new Error('Generic ERiC receipt recording cannot finalize an amendment; use the atomic amendment finalization workflow.'); return recordSubmissionReceiptInState(snapshot, receipt, requireEricSubmissionState(authority)) }
export function finalizeAmendedSubmission(previous: EBalanceSubmissionVersion, amendment: EBalanceSubmissionVersion, receipt: { receivedAt: string; transmissionId: string; reportChecksum: string; status: 'ACCEPTED' | 'REJECTED'; diagnostics: readonly unknown[] }, authority: EricSubmissionAuthority) { const state = requireEricSubmissionState(authority); const previousSnapshot = normalizeSubmission(previous); const amendmentSnapshot = normalizeSubmission(amendment); verifyAcceptedSubmission(previousSnapshot, authority); const normalizedReceipt = normalizeReceipt(receipt); const expectedId = `${previousSnapshot.id}:amendment:${amendmentSnapshot.version}`; if (!Number.isSafeInteger(amendmentSnapshot.version) || amendmentSnapshot.version <= previousSnapshot.version || typeof amendmentSnapshot.reportChecksum !== 'string' || !amendmentSnapshot.reportChecksum.trim() || amendmentSnapshot.id !== expectedId || amendmentSnapshot.supersedesId !== previousSnapshot.id) throw new Error('Amendment supersession chain or derived identity is invalid.'); const trustedAmendment = state.submissions.get(amendmentSnapshot.id); if (!trustedAmendment || canonicalJson(trustedAmendment) !== canonicalJson(amendmentSnapshot) || trustedAmendment.status !== 'PREPARED') throw new Error('Amendment is not the exact prepared submission held in trusted ERiC state.'); if (Date.parse(normalizedReceipt.receivedAt) <= latestPriorReceiptInstant(state, previousSnapshot.id, amendmentSnapshot.id)) throw new Error('Amendment receipt must be received strictly after every prior submission attempt receipt.'); const superseded = normalizedReceipt.status === 'ACCEPTED' ? { ...previousSnapshot, status: 'SUPERSEDED' as const } : previousSnapshot; const trustedSuperseded = structuredClone(superseded); const finalized = recordSubmissionReceiptInState(amendmentSnapshot, normalizedReceipt, state); if (normalizedReceipt.status === 'ACCEPTED') state.submissions.set(previousSnapshot.id, trustedSuperseded); return { previous: superseded, amendment: finalized } }
function recordSubmissionReceiptInState(submission: EBalanceSubmissionVersion, receipt: { receivedAt: string; transmissionId: string; reportChecksum: string; status: 'ACCEPTED' | 'REJECTED'; diagnostics: readonly unknown[] }, state: EricSubmissionState) { const submissionSnapshot = normalizeSubmission(submission); const normalizedReceipt = normalizeReceipt(receipt); if (submissionSnapshot.status !== 'PREPARED') throw new Error('Receipt can only finalize a prepared submission.'); if (!canonicalIdentifier(submissionSnapshot.id) || !Number.isSafeInteger(submissionSnapshot.version) || submissionSnapshot.version <= 0) throw new Error('Prepared submission requires a canonical nonblank ID and positive safe integer version.'); if (typeof submissionSnapshot.reportChecksum !== 'string' || !submissionSnapshot.reportChecksum.trim() || normalizedReceipt.reportChecksum !== submissionSnapshot.reportChecksum) throw new Error('Transmission receipt must identify the exact report checksum, canonical nonblank ID and real received timestamp.'); const trustedPrepared = state.submissions.get(submissionSnapshot.id); if (trustedPrepared && canonicalJson(trustedPrepared) !== canonicalJson(submissionSnapshot)) throw new Error('Prepared submission does not match exact trusted ERiC state.'); if (state.transmissions.has(normalizedReceipt.transmissionId)) { const transmissionOwner = state.transmissions.get(normalizedReceipt.transmissionId)!; if (transmissionOwner !== submissionSnapshot.id) throw new Error('ERiC transmission receipt replay or cross-submission reuse is forbidden.'); throw new Error('ERiC transmission receipt was already recorded.') } const finalized = { ...submissionSnapshot, status: normalizedReceipt.status, immutableReceipt: canonicalJson(normalizedReceipt) }; const trustedFinalized = structuredClone(finalized); state.transmissions.set(normalizedReceipt.transmissionId, submissionSnapshot.id); state.submissions.set(submissionSnapshot.id, trustedFinalized); return finalized }
function validInstant(value: string) { return strictInstant(value) !== null }
function validDateOnly(value: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const parsed = new Date(`${value}T00:00:00.000Z`); return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value }
function validateTaxonomyIdentity(taxonomy: TaxonomyRelease) { if (!taxonomy || typeof taxonomy !== 'object' || typeof taxonomy.version !== 'string' || !/^\d+(?:\.\d+)+$/.test(taxonomy.version) || ![taxonomy.gaapNamespace, taxonomy.gcdNamespace, taxonomy.entryPoint].every(value => typeof value === 'string' && value.trim()) || typeof taxonomy.archiveSha256 !== 'string' || !/^[a-fA-F0-9]{64}$/.test(taxonomy.archiveSha256) || (taxonomy.successorVersion !== undefined && (typeof taxonomy.successorVersion !== 'string' || !/^\d+(?:\.\d+)+$/.test(taxonomy.successorVersion)))) throw new Error('Taxonomy identity metadata, numeric dotted version and archive SHA-256 digest are invalid.') }
function validateTaxonomyEffectivePeriod(taxonomy: TaxonomyRelease) { if (!validDateOnly(taxonomy.validForFiscalPeriodsStartingFrom) || !validDateOnly(taxonomy.validForFiscalPeriodsStartingThrough) || taxonomy.validForFiscalPeriodsStartingFrom > taxonomy.validForFiscalPeriodsStartingThrough) throw new Error('Taxonomy effective period is invalid.') }
function validateTaxonomyRegistry(registry: readonly TaxonomyRelease[]) { const captured = captureArrayValues<TaxonomyRelease>(registry, 'Taxonomy registry'); const normalized = captured.map(value => normalizeTaxonomy(captureTaxonomy(value))); const versions: string[] = []; for (const release of normalized) { validateTaxonomyIdentity(release); validateTaxonomyEffectivePeriod(release); const version = release.version; if (versions.some(registered => compareDottedVersions(registered, version) === 0)) throw new Error(`Taxonomy registry contains duplicate or conflicting version identity: ${version}.`); versions.push(version); if (release.successorVersion !== undefined && compareDottedVersions(release.successorVersion, version) <= 0) throw new Error(`Taxonomy successorVersion must be distinct and strictly newer than ${version}.`) } return normalized }
function validateFacts(facts: readonly EBalanceFact[]) { if (!hasDenseOwnElements(facts)) throw new Error('E-Bilanz facts must be a dense array.'); for (const fact of facts) { if (!hasOwnEnumerableFields(fact, ['concept', 'context', 'amountCents', 'unit', 'accountIds']) || typeof fact.concept !== 'string' || !/^[\p{L}_][\p{L}\p{N}\p{M}._-]*$/u.test(fact.concept) || (fact.context !== 'instant' && fact.context !== 'duration') || fact.unit !== 'EUR' || (!Number.isSafeInteger(fact.amountCents) && fact.amountCents !== null)) throw new Error('Invalid E-Bilanz fact context, taxonomy concept QName, unit, amount or serialization ownership.'); if (!hasDenseNonblankStrings(fact.accountIds, true)) throw new Error('E-Bilanz fact accountIds must be an array with dense own elements containing only nonblank strings.'); const nilDescriptor = Object.getOwnPropertyDescriptor(fact, 'nilReason'); const hasNilReason = nilDescriptor !== undefined; if (hasNilReason && (!nilDescriptor.enumerable || !Object.hasOwn(nilDescriptor, 'value'))) throw new Error('E-Bilanz nilReason must be an own enumerable data property.'); if (fact.amountCents === null ? !hasNilReason || typeof nilDescriptor!.value !== 'string' || !nilDescriptor!.value.trim() : hasNilReason) throw new Error('E-Bilanz nilReason must be a nonblank string exactly for nil facts and absent for numeric facts.') } const factKeys = facts.map(fact => `${fact.concept}\u0000${fact.context}`); if (new Set(factKeys).size !== factKeys.length) throw new Error('E-Bilanz fact concept/context keys must be unique.') }
function validateSupportingBalance(value: EBalanceSupportingBalance | undefined, kind: EBalanceSupportingBalance['kind'], profile: EBalanceProfile) { if (!hasOwnEnumerableFields(value, ['id', 'kind', 'tenantId', 'fiscalPeriodStart', 'fiscalPeriodEnd', 'facts', 'reconciliation']) || typeof value.id !== 'string' || !value.id.trim() || value.kind !== kind || value.tenantId !== profile.tenantId || value.fiscalPeriodStart !== profile.fiscalPeriodStart || value.fiscalPeriodEnd !== profile.fiscalPeriodEnd) throw new Error(`Required ${kind === 'SPECIAL_BALANCE' ? 'special' : 'supplementary'} balance has invalid identity or fiscal period.`); if (!hasDenseOwnElements(value.facts) || value.facts.length === 0) throw new Error(`Required ${kind === 'SPECIAL_BALANCE' ? 'special' : 'supplementary'} balance requires canonical facts.`); validateFacts(value.facts); if (!hasDenseOwnElements(value.reconciliation) || value.reconciliation.length === 0) throw new Error(`Required ${kind === 'SPECIAL_BALANCE' ? 'special' : 'supplementary'} balance requires reconciliation data.`); const ids = new Set<string>(); for (const row of value.reconciliation) { if (!hasOwnEnumerableFields(row, ['id', 'accountId', 'description', 'commercialAmountCents', 'taxAmountCents', 'differenceCents', 'evidenceIds']) || typeof row.id !== 'string' || !row.id.trim() || ids.has(row.id) || typeof row.accountId !== 'string' || !row.accountId.trim() || typeof row.description !== 'string' || !row.description.trim() || !Number.isSafeInteger(row.commercialAmountCents) || !Number.isSafeInteger(row.taxAmountCents) || !Number.isSafeInteger(row.differenceCents) || !hasStrictEvidenceIds(row.evidenceIds) || addSafe(row.taxAmountCents, -row.commercialAmountCents) !== row.differenceCents) throw new Error(`Required ${kind === 'SPECIAL_BALANCE' ? 'special' : 'supplementary'} balance has invalid reconciliation data.`); ids.add(row.id) } }
function validateAssetAttachments(attachments: EBalanceAttachments, profile: EBalanceProfile) {
  if (!validAssetEnvelope(attachments.assetSchedule, profile) || !validAssetEnvelope(attachments.assetRegister, profile)) throw new Error('Asset schedule and asset register require canonical tenant and fiscal-period envelopes with row arrays; explicitly empty row arrays are valid for no-asset companies.')
  const scheduleIds = new Set<string>(); const registerIds = new Set<string>()
  const nonnegativeScheduleAmounts = ['openingCostCents', 'additionsCents', 'disposalsCents', 'closingCostCents', 'costCents', 'openingAccumulatedDepreciationCents', 'currentDepreciationCents', 'impairmentsCents', 'reversalsCents', 'depreciationRemovedOnDisposalCents', 'closingAccumulatedDepreciationCents', 'accumulatedDepreciationCents', 'carryingAmountCents'] as const
  const schedules = new Map<string, EBalanceAssetScheduleRow>()
  for (const row of attachments.assetSchedule!.rows) {
    if (!hasOwnEnumerableFields(row, ['assetId', 'description', 'openingCostCents', 'additionsCents', 'acquisitionCostTransfersCents', 'disposalsCents', 'closingCostCents', 'costCents', 'openingAccumulatedDepreciationCents', 'currentDepreciationCents', 'impairmentsCents', 'reversalsCents', 'accumulatedDepreciationTransfersCents', 'depreciationRemovedOnDisposalCents', 'closingAccumulatedDepreciationCents', 'accumulatedDepreciationCents', 'carryingAmountCents', 'transferEventIds', 'location']) || typeof row.assetId !== 'string' || !row.assetId.trim() || scheduleIds.has(row.assetId) || typeof row.description !== 'string' || !row.description.trim() || typeof row.location !== 'string' || !row.location.trim() || !hasDenseNonblankStrings(row.transferEventIds, true) || nonnegativeScheduleAmounts.some(field => !Number.isSafeInteger(row[field]) || row[field] < 0) || !Number.isSafeInteger(row.acquisitionCostTransfersCents) || !Number.isSafeInteger(row.accumulatedDepreciationTransfersCents)) throw new Error('Asset schedule contains a malformed canonical row.')
    const expectedClosingCost = addSafe(addSafe(addSafe(row.openingCostCents, row.additionsCents), row.acquisitionCostTransfersCents), -row.disposalsCents)
    const expectedClosingDepreciation = addSafe(addSafe(addSafe(addSafe(addSafe(row.openingAccumulatedDepreciationCents, row.currentDepreciationCents), row.impairmentsCents), -row.reversalsCents), row.accumulatedDepreciationTransfersCents), -row.depreciationRemovedOnDisposalCents)
    if (row.costCents !== expectedClosingCost || row.closingCostCents !== expectedClosingCost || row.closingAccumulatedDepreciationCents !== expectedClosingDepreciation || row.accumulatedDepreciationCents !== expectedClosingDepreciation || row.carryingAmountCents !== addSafe(expectedClosingCost, -expectedClosingDepreciation)) throw new Error('Asset schedule movement arithmetic does not reconcile.')
    scheduleIds.add(row.assetId); schedules.set(row.assetId, row)
  }
  for (const row of attachments.assetRegister!.rows) { if (!hasOwnEnumerableFields(row, ['assetId', 'acquisitionDate', 'taxValueCents', 'bookTaxDifferenceCents', 'evidenceIds']) || typeof row.assetId !== 'string' || !row.assetId.trim() || registerIds.has(row.assetId) || !validDateOnly(row.acquisitionDate) || !Number.isSafeInteger(row.taxValueCents) || row.taxValueCents < 0 || !Number.isSafeInteger(row.bookTaxDifferenceCents) || !hasStrictEvidenceIds(row.evidenceIds)) throw new Error('Asset register contains a malformed canonical row.'); if (row.acquisitionDate > profile.fiscalPeriodEnd) throw new Error('Asset register acquisition date cannot be after the report fiscal-period end.'); const schedule = schedules.get(row.assetId); if (schedule && row.bookTaxDifferenceCents !== addSafe(schedule.carryingAmountCents, -row.taxValueCents)) throw new Error('Asset register book/tax difference does not reconcile to the asset schedule.'); registerIds.add(row.assetId) }
  if (scheduleIds.size !== registerIds.size || [...scheduleIds].some(id => !registerIds.has(id))) throw new Error('Asset schedule and asset register must identify the same unique assets.')
}
function validAssetEnvelope(value: unknown, profile: EBalanceProfile) { const envelope = value as EBalanceAssetEnvelope<unknown> | undefined; return hasOwnEnumerableFields(envelope, ['tenantId', 'fiscalPeriodStart', 'fiscalPeriodEnd', 'rows']) && envelope.tenantId === profile.tenantId && envelope.fiscalPeriodStart === profile.fiscalPeriodStart && envelope.fiscalPeriodEnd === profile.fiscalPeriodEnd && hasDenseOwnElements(envelope.rows) }
function normalizeAssetScheduleEnvelope(value: EBalanceAssetEnvelope<EBalanceAssetScheduleRow>): EBalanceAssetEnvelope<EBalanceAssetScheduleRow> { return { tenantId: value.tenantId, fiscalPeriodStart: value.fiscalPeriodStart, fiscalPeriodEnd: value.fiscalPeriodEnd, rows: value.rows.map(normalizeAssetScheduleRow).sort((left, right) => compareCanonicalText(left.assetId, right.assetId)) } }
function normalizeAssetRegisterEnvelope(value: EBalanceAssetEnvelope<EBalanceAssetRegisterRow>): EBalanceAssetEnvelope<EBalanceAssetRegisterRow> { return { tenantId: value.tenantId, fiscalPeriodStart: value.fiscalPeriodStart, fiscalPeriodEnd: value.fiscalPeriodEnd, rows: value.rows.map(row => ({ assetId: row.assetId, acquisitionDate: row.acquisitionDate, taxValueCents: row.taxValueCents, bookTaxDifferenceCents: row.bookTaxDifferenceCents, evidenceIds: captureArrayValues<string>(row.evidenceIds, 'Asset register evidence IDs') })).sort((left, right) => compareCanonicalText(left.assetId, right.assetId)) } }
function normalizeAssetScheduleRow(row: EBalanceAssetScheduleRow): EBalanceAssetScheduleRow { return { assetId: row.assetId, description: row.description, openingCostCents: row.openingCostCents, additionsCents: row.additionsCents, acquisitionCostTransfersCents: row.acquisitionCostTransfersCents, disposalsCents: row.disposalsCents, closingCostCents: row.closingCostCents, costCents: row.costCents, openingAccumulatedDepreciationCents: row.openingAccumulatedDepreciationCents, currentDepreciationCents: row.currentDepreciationCents, impairmentsCents: row.impairmentsCents, reversalsCents: row.reversalsCents, accumulatedDepreciationTransfersCents: row.accumulatedDepreciationTransfersCents, depreciationRemovedOnDisposalCents: row.depreciationRemovedOnDisposalCents, closingAccumulatedDepreciationCents: row.closingAccumulatedDepreciationCents, accumulatedDepreciationCents: row.accumulatedDepreciationCents, carryingAmountCents: row.carryingAmountCents, transferEventIds: captureArrayValues<string>(row.transferEventIds, 'Asset transfer event IDs'), location: row.location } }
function normalizeSupportingBalance(value: EBalanceSupportingBalance): EBalanceSupportingBalance { return { id: value.id, kind: value.kind, tenantId: value.tenantId, fiscalPeriodStart: value.fiscalPeriodStart, fiscalPeriodEnd: value.fiscalPeriodEnd, facts: value.facts.map(normalizeFact).sort((left, right) => compareCanonicalText(left.concept, right.concept) || compareCanonicalText(left.context, right.context)), reconciliation: value.reconciliation.map(row => ({ id: row.id, accountId: row.accountId, description: row.description, commercialAmountCents: row.commercialAmountCents, taxAmountCents: row.taxAmountCents, differenceCents: row.differenceCents, evidenceIds: captureArrayValues<string>(row.evidenceIds, 'Supporting-balance evidence IDs') })).sort((left, right) => compareCanonicalText(left.id, right.id)) } }
function normalizeFact(fact: EBalanceFact): EBalanceFact { const nilDescriptor = Object.getOwnPropertyDescriptor(fact, 'nilReason'); return { concept: fact.concept, context: fact.context, amountCents: fact.amountCents, unit: fact.unit, ...(nilDescriptor ? { nilReason: nilDescriptor.value as string } : {}), accountIds: captureArrayValues<string>(fact.accountIds, 'E-Bilanz fact account IDs') } }
function normalizeTaxAdjustment(adjustment: TaxAdjustment): TaxAdjustment { if (!hasOwnEnumerableFields(adjustment, ['id', 'accountId', 'description', 'type', 'amountCents', 'evidenceIds'])) throw new Error('Tax adjustments require own enumerable canonical fields.'); if (adjustment.type !== 'PERMANENT' && adjustment.type !== 'TEMPORARY') throw new Error('Tax adjustment type must be exactly PERMANENT or TEMPORARY.'); if (typeof adjustment.id !== 'string' || !adjustment.id.trim() || typeof adjustment.accountId !== 'string' || !adjustment.accountId.trim()) throw new Error('Tax adjustments require nonempty unique IDs and account IDs.'); if (typeof adjustment.description !== 'string' || !adjustment.description.trim() || !hasStrictEvidenceIds(adjustment.evidenceIds) || !Number.isSafeInteger(adjustment.amountCents)) throw new Error('Tax adjustments require amount, nonblank evidence IDs and description.'); return { id: adjustment.id, accountId: adjustment.accountId, description: adjustment.description, type: adjustment.type, amountCents: adjustment.amountCents, evidenceIds: captureArrayValues<string>(adjustment.evidenceIds, 'Tax-adjustment evidence IDs') } }
function hasOwnEnumerableFields<T extends object>(value: T | null | undefined, fields: readonly string[]): value is T { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; return fields.every(field => { const descriptor = Object.getOwnPropertyDescriptor(value, field); return Boolean(descriptor?.enumerable && Object.hasOwn(descriptor, 'value')) }) }
function captureOwnDataRecord(value: unknown, requiredFields: readonly string[], optionalFields: readonly string[], label: string): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${label} must be a structured object with own enumerable data properties.`); const source = value as Record<string, unknown>; const snapshot: Record<string, unknown> = {}; for (const field of requiredFields) { const descriptor = Object.getOwnPropertyDescriptor(source, field); if (!descriptor?.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error(`${label} must use own enumerable data properties.`); snapshot[field] = descriptor.value } for (const field of optionalFields) { const descriptor = Object.getOwnPropertyDescriptor(source, field); if (!descriptor) { if (field in source) throw new Error(`${label} optional fields must use own enumerable data properties.`); continue } if (!descriptor.enumerable || !Object.hasOwn(descriptor, 'value')) throw new Error(`${label} optional fields must use own enumerable data properties.`); if (descriptor.value !== undefined) snapshot[field] = descriptor.value } return snapshot }
function captureArrayValues<T>(value: unknown, label: string): readonly T[] { if (!hasDenseOwnElements(value)) throw new Error(`${label} must be a dense array of own data elements.`); const snapshot: T[] = []; for (let index = 0; index < value.length; index++) snapshot.push(Object.getOwnPropertyDescriptor(value, String(index))!.value as T); return snapshot }
function captureEBalanceProfile(value: unknown): EBalanceProfile { return captureOwnDataRecord(value, ['tenantId', 'companyName', 'legalForm', 'taxNumber', 'fiscalPeriodStart', 'fiscalPeriodEnd', 'accountingStandard', 'incomeStatementMethod', 'statementType', 'reportStatus', 'consolidationRange', 'incomeClassification'], ['specialBalanceRequired', 'supplementaryBalanceRequired'], 'E-Bilanz profile') as unknown as EBalanceProfile }
function captureTaxonomy(value: unknown): TaxonomyRelease { return captureOwnDataRecord(value, ['version', 'validForFiscalPeriodsStartingFrom', 'validForFiscalPeriodsStartingThrough', 'gaapNamespace', 'gcdNamespace', 'entryPoint', 'archiveSha256'], ['successorVersion'], 'Taxonomy') as unknown as TaxonomyRelease }
function normalizeTaxonomy(taxonomy: TaxonomyRelease): TaxonomyRelease { return { ...taxonomy, ...(typeof taxonomy.version === 'string' ? { version: taxonomy.version.trim() } : {}), ...(typeof taxonomy.gaapNamespace === 'string' ? { gaapNamespace: taxonomy.gaapNamespace.trim() } : {}), ...(typeof taxonomy.gcdNamespace === 'string' ? { gcdNamespace: taxonomy.gcdNamespace.trim() } : {}), ...(typeof taxonomy.entryPoint === 'string' ? { entryPoint: taxonomy.entryPoint.trim() } : {}), ...(typeof taxonomy.successorVersion === 'string' ? { successorVersion: taxonomy.successorVersion.trim() } : {}) } }
function captureAttachments(value: unknown): EBalanceAttachments { const attachments = captureOwnDataRecord(value, ['assetSchedule', 'assetRegister'], ['specialBalance', 'supplementaryBalance'], 'E-Bilanz attachments structured object'); let assetSchedule: EBalanceAssetEnvelope<EBalanceAssetScheduleRow>; let assetRegister: EBalanceAssetEnvelope<EBalanceAssetRegisterRow>; try { assetSchedule = captureAssetEnvelope<EBalanceAssetScheduleRow>(attachments.assetSchedule, 'Asset schedule'); assetRegister = captureAssetEnvelope<EBalanceAssetRegisterRow>(attachments.assetRegister, 'Asset register') } catch { throw new Error('Asset schedule and asset register require canonical tenant and fiscal-period envelopes with row arrays; explicitly empty row arrays are valid for no-asset companies.') } let specialBalance: EBalanceSupportingBalance | undefined; let supplementaryBalance: EBalanceSupportingBalance | undefined; try { if (attachments.specialBalance !== undefined) specialBalance = captureSupportingBalance(attachments.specialBalance, 'Special balance') } catch { throw new Error('Required special balance has invalid identity or fiscal period.') } try { if (attachments.supplementaryBalance !== undefined) supplementaryBalance = captureSupportingBalance(attachments.supplementaryBalance, 'Supplementary balance') } catch { throw new Error('Required supplementary balance has invalid identity or fiscal period.') } return { assetSchedule, assetRegister, ...(specialBalance !== undefined ? { specialBalance } : {}), ...(supplementaryBalance !== undefined ? { supplementaryBalance } : {}) } }
function captureAssetEnvelope<Row>(value: unknown, label: string): EBalanceAssetEnvelope<Row> { const envelope = captureOwnDataRecord(value, ['tenantId', 'fiscalPeriodStart', 'fiscalPeriodEnd', 'rows'], [], label); return { tenantId: envelope.tenantId as string, fiscalPeriodStart: envelope.fiscalPeriodStart as string, fiscalPeriodEnd: envelope.fiscalPeriodEnd as string, rows: captureArrayValues<Row>(envelope.rows, `${label} rows`) } }
function captureSupportingBalance(value: unknown, label: string): EBalanceSupportingBalance { const balance = captureOwnDataRecord(value, ['id', 'kind', 'tenantId', 'fiscalPeriodStart', 'fiscalPeriodEnd', 'facts', 'reconciliation'], [], label); return { id: balance.id as string, kind: balance.kind as EBalanceSupportingBalance['kind'], tenantId: balance.tenantId as string, fiscalPeriodStart: balance.fiscalPeriodStart as string, fiscalPeriodEnd: balance.fiscalPeriodEnd as string, facts: captureArrayValues<EBalanceFact>(balance.facts, `${label} facts`), reconciliation: captureArrayValues<EBalanceSupportingBalance['reconciliation'][number]>(balance.reconciliation, `${label} reconciliation`) } }
function normalizeParsedRoot(value: unknown): { wellFormed: boolean; localName: string; namespaceUri: string } { const snapshot = captureOwnDataRecord(value, ['wellFormed', 'localName', 'namespaceUri'], [], 'E-Bilanz parsed root'); if (typeof snapshot.wellFormed !== 'boolean' || typeof snapshot.localName !== 'string' || typeof snapshot.namespaceUri !== 'string') throw new Error('E-Bilanz parsed root fields must have exact boolean and string types.'); return { wellFormed: snapshot.wellFormed, localName: snapshot.localName, namespaceUri: snapshot.namespaceUri } }
function canonicalPayloadEvidence(canonicalPayload: string) { return `<accounting:canonicalPayload xmlns:accounting="${CANONICAL_PAYLOAD_NAMESPACE}" encoding="base64">${Buffer.from(canonicalPayload, 'utf8').toString('base64')}</accounting:canonicalPayload>` }
function containsCanonicalPayloadEvidence(content: string, evidence: string) { const withoutDeclaration = content.replace(/^\s*<\?xml\s[^?]*\?>/i, ''); if (/<\?|<!DOCTYPE\b/i.test(withoutDeclaration)) return false; const first = content.indexOf(evidence); if (first < 0 || content.indexOf(evidence, first + evidence.length) >= 0) return false; const rootStartEnd = content.indexOf('>'); const rootClose = content.lastIndexOf('</'); if (first <= rootStartEnd || first + evidence.length > rootClose) return false; const commentsAndCdata = /<!--[^]*?-->|<!\[CDATA\[[^]*?\]\]>/g; for (const match of content.matchAll(commentsAndCdata)) { const start = match.index; if (start !== undefined && start <= first && first < start + match[0].length) return false } return true }
function containsExactCanonicalXbrlBody(content: string, semanticFacts: string, payloadEvidence: string) { const normalized = normalizeXbrlInstancePrefixes(content).replace(/^\s*<\?xml\s[^?]*\?>/i, ''); if (/<\?|<!DOCTYPE\b|<!--|<!\[CDATA\[/i.test(normalized)) return false; const rootStartEnd = normalized.indexOf('>'); const rootClose = normalized.lastIndexOf('</'); if (rootStartEnd < 0 || rootClose <= rootStartEnd) return false; const rootStart = normalized.slice(0, rootStartEnd + 1); const rootEnd = normalized.slice(rootClose); const prefixedRoot = '<xbrli:xbrl xmlns:xbrli="http://www.xbrl.org/2003/instance">'; const defaultRoot = '<xbrl xmlns="http://www.xbrl.org/2003/instance">'; if (!((rootStart === prefixedRoot && rootEnd === '</xbrli:xbrl>') || (rootStart === defaultRoot && rootEnd === '</xbrl>'))) return false; return normalized.slice(rootStartEnd + 1, rootClose) === `${semanticFacts}${payloadEvidence}` }
function normalizeXbrlInstancePrefixes(content: string) { const instanceNamespace = 'http://www.xbrl.org/2003/instance'; const prefixes = [...content.matchAll(new RegExp(`xmlns:([A-Za-z_][A-Za-z0-9_.-]*)=(['"])${instanceNamespace}\\2`, 'g'))].map(match => match[1]).filter(prefix => prefix !== 'xbrli'); return prefixes.reduce((normalized, prefix) => normalized.replaceAll(`xmlns:${prefix}=`, 'xmlns:xbrli=').replaceAll(`<${prefix}:`, '<xbrli:').replaceAll(`</${prefix}:`, '</xbrli:'), content) }
function xmlEscape(value: string) { return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;') }
function centsToEuro(value: number) { const sign = value < 0 ? '-' : ''; const absolute = Math.abs(value); return `${sign}${Math.floor(absolute / 100)}.${String(absolute % 100).padStart(2, '0')}` }
function strictInstant(value: string) { if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(value) || !validDateOnly(value.slice(0, 10))) return null; const parsed = Date.parse(value); return Number.isNaN(parsed) ? null : parsed }
function addSafe(left: number, right: number) { const result = left + right; if (!Number.isSafeInteger(result)) throw new Error('E-Bilanz tax reconciliation exceeds safe integer limits.'); return result }
function deepFreeze<T>(value: T): T { if (value && typeof value === 'object' && !Object.isFrozen(value)) { for (const nested of Object.values(value as Record<string, unknown>)) deepFreeze(nested); Object.freeze(value) } return value }
function sumSafe(values: readonly number[]) { return values.reduce((sum, value) => addSafe(sum, value), 0) }
function requireEricSubmissionState(authority: EricSubmissionAuthority) { const state = ericSubmissionStores.get(authority); if (!state) throw new Error('A trusted ERiC submission authority is required.'); return state }
function canonicalIdentifier(value: unknown): value is string { return typeof value === 'string' && Boolean(value) && value === value.trim() }
function normalizeSubmission(value: unknown): EBalanceSubmissionVersion { const allowed = new Set(['id', 'version', 'reportChecksum', 'status', 'supersedesId', 'immutableReceipt']); if (!value || typeof value !== 'object' || Array.isArray(value) || Reflect.ownKeys(value).some(key => typeof key !== 'string' || !allowed.has(key))) throw new Error('E-Bilanz submission contains undeclared or malformed fields.'); return captureOwnDataRecord(value, ['id', 'version', 'reportChecksum', 'status'], ['supersedesId', 'immutableReceipt'], 'E-Bilanz submission') as unknown as EBalanceSubmissionVersion }
function verifyAcceptedSubmission(submission: EBalanceSubmissionVersion, authority: EricSubmissionAuthority) { const snapshot = normalizeSubmission(submission); if (!canonicalIdentifier(snapshot.id) || !Number.isSafeInteger(snapshot.version) || snapshot.version <= 0) throw new Error('Accepted submission requires a canonical nonblank ID and positive safe integer version.'); if (snapshot.status !== 'ACCEPTED' || typeof snapshot.reportChecksum !== 'string' || !snapshot.reportChecksum.trim() || typeof snapshot.immutableReceipt !== 'string' || !snapshot.immutableReceipt) throw new Error('Only a genuinely accepted report with immutable receipt can be amended.'); let parsedReceipt: unknown; try { parsedReceipt = JSON.parse(snapshot.immutableReceipt) } catch { throw new Error('Accepted submission receipt is malformed.') } let receipt: NormalizedEricReceipt; try { receipt = normalizeReceipt(parsedReceipt) } catch (error) { if (error instanceof Error && error.message.includes('diagnostics')) throw error; throw new Error('Accepted submission receipt is not a well-formed ACCEPTED receipt bound to the report with canonical IDs.') } if (receipt.status !== 'ACCEPTED' || receipt.reportChecksum !== snapshot.reportChecksum) throw new Error('Accepted submission receipt is not a well-formed ACCEPTED receipt bound to the report with canonical IDs.'); const trusted = requireEricSubmissionState(authority).submissions.get(snapshot.id); if (!trusted || canonicalJson(trusted) !== canonicalJson(snapshot)) throw new Error('Accepted submission and receipt are not attested by exact trusted ERiC state.'); return receipt }
function latestPriorReceiptInstant(state: EricSubmissionState, originalId: string, currentAttemptId: string) { let latest = Number.NEGATIVE_INFINITY; for (const submission of state.submissions.values()) { if (submission.id === currentAttemptId || (submission.id !== originalId && submission.supersedesId !== originalId) || typeof submission.immutableReceipt !== 'string') continue; let parsed: unknown; try { parsed = JSON.parse(submission.immutableReceipt) } catch { throw new Error('Trusted ERiC submission receipt is malformed.') } const receipt = normalizeReceipt(parsed); latest = Math.max(latest, Date.parse(receipt.receivedAt)) } return latest }
function normalizeReceipt(value: unknown): NormalizedEricReceipt { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Transmission receipt must be a structured object with own enumerable data properties.'); const record = value as Record<string, unknown>; const receivedAt = ownEnumerableDataValue(record, 'receivedAt'); const transmissionId = ownEnumerableDataValue(record, 'transmissionId'); const reportChecksum = ownEnumerableDataValue(record, 'reportChecksum'); const status = ownEnumerableDataValue(record, 'status'); const diagnosticValue = ownEnumerableDataValue(record, 'diagnostics'); if (status !== 'ACCEPTED' && status !== 'REJECTED') throw new Error('Transmission receipt status must be ACCEPTED or REJECTED.'); if (!canonicalIdentifier(transmissionId) || typeof reportChecksum !== 'string' || !reportChecksum.trim() || typeof receivedAt !== 'string' || !validInstant(receivedAt)) throw new Error('Transmission receipt required fields must be own enumerable data properties identifying a canonical nonblank ID, report checksum and real timestamp.'); return { receivedAt, transmissionId, reportChecksum, status, diagnostics: normalizeDiagnostics(diagnosticValue, 'Transmission receipt') } }
function normalizeDiagnostics(value: unknown, context: string): EBalanceDiagnostic[] { if (!hasDenseOwnElements(value)) throw new Error(`${context} diagnostics must be an array; a dense array of own well-formed diagnostic records is required.`); const normalized: EBalanceDiagnostic[] = []; for (let index = 0; index < value.length; index++) { const diagnostic = Object.getOwnPropertyDescriptor(value, String(index))!.value; if (!diagnostic || typeof diagnostic !== 'object' || Array.isArray(diagnostic)) throw new Error(`${context} diagnostics must be an array of well-formed diagnostic records.`); const record = diagnostic as Record<string, unknown>; const code = ownEnumerableDataValue(record, 'code'); const severity = ownEnumerableDataValue(record, 'severity'); const message = ownEnumerableDataValue(record, 'message'); const pathDescriptor = Object.getOwnPropertyDescriptor(record, 'path'); const hasAnyPath = 'path' in record; if (typeof code !== 'string' || !code.trim() || typeof severity !== 'string' || !severity.trim() || typeof message !== 'string' || !message.trim() || (hasAnyPath && (!pathDescriptor || !pathDescriptor.enumerable || !Object.hasOwn(pathDescriptor, 'value') || typeof pathDescriptor.value !== 'string' || !pathDescriptor.value.trim()))) throw new Error(`${context} diagnostics must be an array of well-formed records using own enumerable data fields.`); normalized.push({ code, severity, message, ...(hasAnyPath ? { path: pathDescriptor!.value as string } : {}) }) } return normalized }
function ownEnumerableDataValue(record: Record<string, unknown>, field: string): unknown { const descriptor = Object.getOwnPropertyDescriptor(record, field); return descriptor && descriptor.enumerable && Object.hasOwn(descriptor, 'value') ? descriptor.value : undefined }
function nextSubmissionVersion(version: number) { const next = version + 1; if (!Number.isSafeInteger(next)) throw new Error('Amended submission version exceeds safe integer limits.'); return next }
