"use client"

import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { useTranslations } from 'next-intl'
import { getJSON } from './Requester'

type Account = { id: string; number: number; name: string; category: 'ASSET' | 'EXPENSE' | 'REVENUE' | 'LIABILITY' }
type Document = { id: string; fileName: string }
type Customer = { id: string; partnerNumber: string; name: string; countryCode: string; paymentTermDays: number }
type AcquisitionCandidate = { id: string; bookingDate: string; documentNumber: string; description: string; debitCents: number; accountId: string; accountNumber: number; accountName: string; documentIds: string[] }
type ScheduleRow = { period: string; postingDate: string; amountCents: number; cumulativeCents: number; carryingAmountCents: number; status: 'SCHEDULED' | 'POSTED' | 'REVERSED'; eventId?: string }
type Asset = { id: string; description: string; costCents: number; acquisitionDate: string; availableForUseDate: string; usefulLifeMonths: number; location: string; sourceDocumentId: string; schedule: ScheduleRow[]; lifecycle: { disposed: boolean; disposedOn: string | null; disposalKind: 'RETIREMENT' | 'SALE' | null; carryingAmountCents: number; netProceedsCents?: number; outputVatCents?: number; gainLossCents?: number; result?: 'GAIN' | 'LOSS' } }
type Workspace = { assets: Asset[]; accounts: Account[]; documents: Document[]; acquisitionCandidates: AcquisitionCandidate[]; customers: Customer[] }

export function FixedAssetsWorkspace() {
  const t = useTranslations('FixedAssets')
  const [workspace, setWorkspace] = useState<Workspace | null>(null); const [error, setError] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false)
  const [form, setForm] = useState({ requestKey: browserRequestKey(), description: '', cost: '', acquisitionDate: `${new Date().getFullYear()}-01-01`, availableForUseDate: `${new Date().getFullYear()}-01-01`, location: '', usefulLifeMonths: '36', assetAccountId: '', depreciationExpenseAccountId: '', sourceDocumentId: '', acquisitionJournalLineId: '' })
  const [retirement, setRetirement] = useState({ requestKey: browserRequestKey(), effectiveDate: `${new Date().getFullYear()}-01-01`, evidenceDocumentId: '', disposalExpenseAccountId: '', reason: '' })
  const [sale, setSale] = useState({ requestKey: browserRequestKey(), effectiveDate: `${new Date().getFullYear()}-01-01`, evidenceDocumentId: '', businessPartnerId: '', invoiceNumber: '', netProceeds: '', reason: '' })
  const load = useCallback(async () => { setError(''); const response = await fetch('/api/fixed-assets'); const body = await getJSON(response); if (!response.ok) throw new Error(body?.error || t('loadFailed')); setWorkspace(body.data); setForm(current => ({ ...current, assetAccountId: current.assetAccountId || body.data.accounts.find((account: Account) => account.category === 'ASSET')?.id || '', depreciationExpenseAccountId: current.depreciationExpenseAccountId || body.data.accounts.find((account: Account) => account.category === 'EXPENSE' && !account.name.includes('Anlagenabgänge'))?.id || '', sourceDocumentId: current.sourceDocumentId || body.data.documents[0]?.id || '', acquisitionJournalLineId: current.acquisitionJournalLineId || body.data.acquisitionCandidates[0]?.id || '' })); setRetirement(current => ({ ...current, disposalExpenseAccountId: current.disposalExpenseAccountId || body.data.accounts.find((account: Account) => account.category === 'EXPENSE' && account.name.includes('Anlagenabgänge Sachanlagen'))?.id || '' })); setSale(current => ({ ...current, businessPartnerId: current.businessPartnerId || body.data.customers[0]?.id || '' })) }, [t])
  useEffect(() => { void load().catch(reason => setError(reason instanceof Error ? reason.message : t('loadFailed'))) }, [load])

  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); setStatus(''); try { const response = await fetch('/api/fixed-assets', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, costCents: Math.round(Number(form.cost) * 100), usefulLifeMonths: Number(form.usefulLifeMonths), taxUsefulLifeMonths: Number(form.usefulLifeMonths), method: 'STRAIGHT_LINE', taxMethod: 'STRAIGHT_LINE' }) }); const body = await getJSON(response); if (!response.ok) throw new Error(body?.error || t('createFailed')); setStatus(t('created')); setForm(current => ({ ...current, requestKey: browserRequestKey(), description: '', cost: '', location: '' })); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : t('createFailed')) } finally { setBusy(false) } }
  async function post(asset: Asset, row: ScheduleRow) { setBusy(true); setError(''); setStatus(''); try { const response = await fetch(`/api/fixed-assets/${encodeURIComponent(asset.id)}/depreciation`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ period: row.period, reason: 'Monthly straight-line depreciation explicitly approved' }) }); const body = await getJSON(response); if (!response.ok) throw new Error(body?.error || t('postFailed')); setStatus(t('posted', { period: row.period, asset: asset.description })); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : t('postFailed')) } finally { setBusy(false) } }
  async function reverse(asset: Asset, row: ScheduleRow) { if (!row.eventId) return; setBusy(true); setError(''); setStatus(''); try { const response = await fetch(`/api/fixed-assets/${encodeURIComponent(asset.id)}/depreciation/${encodeURIComponent(row.eventId)}/reversal`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ effectiveDate: row.postingDate, reason: 'Explicit correction of posted depreciation' }) }); const body = await getJSON(response); if (!response.ok) throw new Error(body?.error || t('reverseFailed')); setStatus(t('reversed', { period: row.period, asset: asset.description })); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : t('reverseFailed')) } finally { setBusy(false) } }
  async function retire(asset: Asset, event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); setStatus(''); try { const response = await fetch(`/api/fixed-assets/${encodeURIComponent(asset.id)}/disposals`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(retirement) }); const body = await getJSON(response); if (!response.ok) throw new Error(body?.error || t('retireFailed')); setStatus(t('retired', { asset: asset.description, amount: money(body.data.event.carryingAmountCents) })); setRetirement(current => ({ ...current, requestKey: browserRequestKey(), reason: '' })); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : t('retireFailed')) } finally { setBusy(false) } }
  async function sell(asset: Asset, event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); setStatus(''); try { const accounts = saleAccounts(workspace!, asset, sale.netProceeds); if (!accounts) throw new Error(t('saleAccountsMissing')); const response = await fetch(`/api/fixed-assets/${encodeURIComponent(asset.id)}/sales`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...sale, netProceedsCents: Math.round(Number(sale.netProceeds) * 100), vatRateBasisPoints: 1900, receivableAccountId: accounts.receivable.id, proceedsAccountId: accounts.proceeds.id, carryingValueAccountId: accounts.carrying.id, outputVatAccountId: accounts.outputVat.id }) }); const body = await getJSON(response); if (!response.ok) throw new Error(body?.error || t('saleFailed')); setStatus(t(body.data.event.result === 'GAIN' ? 'soldGain' : 'soldLoss', { asset: asset.description, gross: money(body.data.event.grossProceedsCents), result: money(Math.abs(body.data.event.gainLossCents)) })); setSale(current => ({ ...current, requestKey: browserRequestKey(), invoiceNumber: '', netProceeds: '', reason: '' })); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : t('saleFailed')) } finally { setBusy(false) } }
  if (!workspace) return <div>{error ? <div className="alert alert-danger">{error}</div> : t('loading')}</div>
  const assets = workspace.accounts.filter(account => account.category === 'ASSET' && account.name.includes('Andere Anlagen')); const expenses = workspace.accounts.filter(account => account.category === 'EXPENSE' && account.name.includes('Abschreibungen auf Sachanlagen')); const retirementExpenses = workspace.accounts.filter(account => account.category === 'EXPENSE' && account.name.includes('Anlagenabgänge Sachanlagen') && account.name.includes('Buchverlust'))
  return <div className="container-fluid px-0"><header className="mb-4"><h1>{t('title')}</h1><p className="text-muted">{t('subtitle')}</p></header>{error && <div className="alert alert-danger" role="alert">{error}</div>}{status && <div className="alert alert-success" role="status">{status}</div>}
    <section className="card mb-4"><div className="card-body"><h2 className="h4">{t('register')}</h2><p className="small text-muted">{t('supportedScope')}</p><div className="alert alert-info">{t('registrationBoundary')}</div><form onSubmit={create}><div className="form-grid">
      <label>{t('description')}<input className="form-control" required value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></label>
      <label>{t('cost')}<input className="form-control" required min="0.01" step="0.01" type="number" value={form.cost} onChange={event => setForm({ ...form, cost: event.target.value })} /></label>
      <label>{t('acquisitionDate')}<input className="form-control" required type="date" value={form.acquisitionDate} onChange={event => setForm({ ...form, acquisitionDate: event.target.value })} /></label>
      <label>{t('availableDate')}<input className="form-control" required type="date" value={form.availableForUseDate} onChange={event => setForm({ ...form, availableForUseDate: event.target.value })} /></label>
      <label>{t('usefulLife')}<input className="form-control" required min="1" max="1200" type="number" value={form.usefulLifeMonths} onChange={event => setForm({ ...form, usefulLifeMonths: event.target.value })} /></label>
      <label>{t('location')}<input className="form-control" required value={form.location} onChange={event => setForm({ ...form, location: event.target.value })} /></label>
      <label>{t('assetAccount')}<select className="form-select" required value={form.assetAccountId} onChange={event => setForm({ ...form, assetAccountId: event.target.value })}>{assets.map(account => <option value={account.id} key={account.id}>{String(account.number).padStart(4, '0')} {account.name}</option>)}</select></label>
      <label>{t('expenseAccount')}<select className="form-select" required value={form.depreciationExpenseAccountId} onChange={event => setForm({ ...form, depreciationExpenseAccountId: event.target.value })}>{expenses.map(account => <option value={account.id} key={account.id}>{String(account.number).padStart(4, '0')} {account.name}</option>)}</select></label>
      <label>{t('sourceDocument')}<select className="form-select" required value={form.sourceDocumentId} onChange={event => setForm({ ...form, sourceDocumentId: event.target.value })}><option value="">{t('chooseDocument')}</option>{workspace.documents.map(document => <option value={document.id} key={document.id}>{document.fileName}</option>)}</select></label>
      <label>{t('acquisitionPosting')}<select className="form-select" required value={form.acquisitionJournalLineId} onChange={event => setForm({ ...form, acquisitionJournalLineId: event.target.value })}><option value="">{t('chooseAcquisitionPosting')}</option>{workspace.acquisitionCandidates.map(candidate => <option value={candidate.id} key={candidate.id}>{candidate.bookingDate} · {candidate.documentNumber} · {String(candidate.accountNumber).padStart(4, '0')} · {money(candidate.debitCents)}</option>)}</select></label>
    </div><button className="btn btn-primary mt-3" disabled={busy || !workspace.documents.length || !workspace.acquisitionCandidates.length}>{busy ? t('saving') : t('create')}</button>{!workspace.documents.length && <p className="text-danger small mt-2">{t('uploadFirst')}</p>}{workspace.documents.length > 0 && !workspace.acquisitionCandidates.length && <p className="text-danger small mt-2">{t('postAcquisitionFirst')}</p>}</form></div></section>
    {workspace.assets.map(asset => {
      const selectedSaleAccounts = saleAccounts(workspace, asset, sale.netProceeds)
      const netCents = Math.round(Number(sale.netProceeds || '0') * 100); const vatCents = Math.round(netCents * 0.19); const resultCents = netCents - asset.lifecycle.carryingAmountCents
      return <section className="card mb-4" key={asset.id}><div className="card-body"><h2 className="h4">{asset.description}</h2><p>{money(asset.costCents)} · {t('months', { count: asset.usefulLifeMonths })} · {asset.location}</p>
        {asset.lifecycle.disposed && <div className="alert alert-secondary" role="status">{asset.lifecycle.disposalKind === 'SALE' ? t(asset.lifecycle.result === 'GAIN' ? 'soldStateGain' : 'soldStateLoss', { date: asset.lifecycle.disposedOn ?? '', net: money(asset.lifecycle.netProceedsCents ?? 0), vat: money(asset.lifecycle.outputVatCents ?? 0), result: money(Math.abs(asset.lifecycle.gainLossCents ?? 0)) }) : t('disposedState', { date: asset.lifecycle.disposedOn ?? '', amount: money(asset.lifecycle.carryingAmountCents) })}</div>}
        <div className="table-responsive"><table className="table"><thead><tr><th>{t('period')}</th><th>{t('postingDate')}</th><th>{t('depreciation')}</th><th>{t('cumulative')}</th><th>{t('carrying')}</th><th>{t('statusLabel')}</th><th>{t('action')}</th></tr></thead><tbody>{asset.schedule.map(row => <tr key={row.period}><td>{row.period}</td><td>{row.postingDate}</td><td>{money(row.amountCents)}</td><td>{money(row.cumulativeCents)}</td><td>{money(row.carryingAmountCents)}</td><td>{t(`status.${row.status}`)}</td><td>{asset.lifecycle.disposed ? t('noFurtherPosting') : row.status === 'SCHEDULED' || row.status === 'REVERSED' ? <button className="btn btn-sm btn-outline-primary" disabled={busy} onClick={() => void post(asset, row)}>{t('post')}</button> : <button className="btn btn-sm btn-outline-danger" disabled={busy} onClick={() => void reverse(asset, row)}>{t('reverse')}</button>}</td></tr>)}</tbody></table></div>
        {!asset.lifecycle.disposed && <><form className="border-top pt-3 mt-3 asset-sale-form" onSubmit={event => void sell(asset, event)}><h3 className="h5">{t('saleTitle')}</h3><p className="small text-muted">{t('saleBoundary')}</p><div className="form-grid">
          <label>{t('saleDate')}<input className="form-control" required type="date" value={sale.effectiveDate} onChange={event => setSale({ ...sale, effectiveDate: event.target.value })} /></label>
          <label>{t('saleEvidence')}<select className="form-select" required value={sale.evidenceDocumentId} onChange={event => setSale({ ...sale, evidenceDocumentId: event.target.value })}><option value="">{t('chooseSaleEvidence')}</option>{workspace.documents.map(document => <option value={document.id} key={document.id}>{document.fileName}</option>)}</select></label>
          <label>{t('saleCustomer')}<select className="form-select" required value={sale.businessPartnerId} onChange={event => setSale({ ...sale, businessPartnerId: event.target.value })}><option value="">{t('chooseSaleCustomer')}</option>{workspace.customers.map(customer => <option value={customer.id} key={customer.id}>{customer.partnerNumber} · {customer.name} · {customer.paymentTermDays} {t('days')}</option>)}</select></label>
          <label>{t('saleInvoiceNumber')}<input className="form-control" required maxLength={80} value={sale.invoiceNumber} onChange={event => setSale({ ...sale, invoiceNumber: event.target.value })} /></label>
          <label>{t('netProceeds')}<input className="form-control" required min="0.01" step="0.01" type="number" value={sale.netProceeds} onChange={event => setSale({ ...sale, netProceeds: event.target.value })} /></label>
          <label>{t('vatRate')}<input className="form-control" readOnly value="19 %" /></label>
          <label>{t('receivableAccount')}<input className="form-control" readOnly value={accountLabel(selectedSaleAccounts?.receivable)} /></label>
          <label>{t('saleProceedsAccount')}<input className="form-control" readOnly value={accountLabel(selectedSaleAccounts?.proceeds)} /></label>
          <label>{t('saleCarryingAccount')}<input className="form-control" readOnly value={accountLabel(selectedSaleAccounts?.carrying)} /></label>
          <label>{t('saleVatAccount')}<input className="form-control" readOnly value={accountLabel(selectedSaleAccounts?.outputVat)} /></label>
          <label>{t('saleReason')}<input className="form-control" required value={sale.reason} onChange={event => setSale({ ...sale, reason: event.target.value })} /></label>
        </div>{netCents > 0 && <div className="alert alert-info mt-3" role="note">{t(resultCents >= 0 ? 'salePreviewGain' : 'salePreviewLoss', { carrying: money(asset.lifecycle.carryingAmountCents), net: money(netCents), vat: money(vatCents), gross: money(netCents + vatCents), result: money(Math.abs(resultCents)) })}</div>}<button className="btn btn-primary mt-3" disabled={busy || !selectedSaleAccounts || !workspace.customers.length}>{busy ? t('saving') : t('sell')}</button>{!workspace.customers.length && <p className="text-danger small mt-2">{t('createCustomerFirst')}</p>}</form>
          <form className="border-top pt-3 mt-3" onSubmit={event => void retire(asset, event)}><h3 className="h5">{t('retireTitle')}</h3><p className="small text-muted">{t('retireBoundary')}</p><div className="form-grid"><label>{t('retirementDate')}<input className="form-control" required type="date" value={retirement.effectiveDate} onChange={event => setRetirement({ ...retirement, effectiveDate: event.target.value })} /></label><label>{t('retirementEvidence')}<select className="form-select" required value={retirement.evidenceDocumentId} onChange={event => setRetirement({ ...retirement, evidenceDocumentId: event.target.value })}><option value="">{t('chooseRetirementEvidence')}</option>{workspace.documents.map(document => <option value={document.id} key={document.id}>{document.fileName}</option>)}</select></label><label>{t('retirementExpenseAccount')}<select className="form-select" required value={retirement.disposalExpenseAccountId} onChange={event => setRetirement({ ...retirement, disposalExpenseAccountId: event.target.value })}><option value="">{t('chooseRetirementExpense')}</option>{retirementExpenses.map(account => <option value={account.id} key={account.id}>{String(account.number).padStart(4, '0')} {account.name}</option>)}</select></label><label>{t('retirementReason')}<input className="form-control" required value={retirement.reason} onChange={event => setRetirement({ ...retirement, reason: event.target.value })} /></label></div><button className="btn btn-outline-danger mt-3" disabled={busy || !retirementExpenses.length}>{busy ? t('saving') : t('retire')}</button></form></>}
      </div></section>
    })}
  </div>
}

function money(cents: number) { return new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(cents / 100) }
function accountLabel(account?: Account) { return account ? `${String(account.number).padStart(4, '0')} ${account.name}` : '' }
function saleAccounts(workspace: Workspace, asset: Asset, netProceeds: string) {
  const result = Math.round(Number(netProceeds || '0') * 100) >= asset.lifecycle.carryingAmountCents ? 'Buchgewinn' : 'Buchverlust'
  const category = result === 'Buchgewinn' ? 'REVENUE' : 'EXPENSE'
  const find = (categoryValue: Account['category'], ...parts: string[]) => workspace.accounts.find(account => account.category === categoryValue && parts.every(part => account.name.includes(part)))
  const receivable = find('ASSET', 'Forderungen aus Lieferungen und Leistungen'); const outputVat = find('LIABILITY', 'Umsatzsteuer 19 %')
  const proceeds = find(category, 'Erlöse aus Verkäufen Sachanlagevermögen 19 % USt', result); const carrying = find(category, 'Anlagenabgänge Sachanlagen', `Restbuchwert bei ${result}`)
  return receivable && outputVat && proceeds && carrying ? { receivable, outputVat, proceeds, carrying } : undefined
}
function browserRequestKey() { return typeof crypto === 'undefined' ? 'fixed-asset-request-placeholder' : crypto.randomUUID() }
