"use client"

import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { useLocale, useTranslations } from 'next-intl'
import { api, getJSON } from './Requester'
import { buildStructuredInvoiceRequest, calculateInvoiceTotals, type InvoiceFormLine } from './structuredInvoiceForm'

interface IssuedInvoice { id: string; documentId: string; syntax: string; kind: string; invoiceNumber: string; issueDate: string }
interface NumberSequence { year: number; nextValue: number }
type CorrectionTemplate = { data: { buyer: Record<string, unknown>; currency: string; lines: Array<{ taxRateBasisPoints: number; unitCode: string }>; grossAmountCents: number }; buyerReference: string; buyerElectronicAddress: { schemeId: '0204' | '9930' | 'EM'; value: string }; paymentTerms: string; paymentIban: string }
const newLine = (id = crypto.randomUUID()): InvoiceFormLine => ({ id, description: '', quantity: '1', unitCode: 'C62', netAmount: '', taxRate: '19' })
const today = () => new Date().toISOString().slice(0, 10)

async function readList<T>(response: Response) {
  const body = await getJSON(response)
  if (!response.ok || body?.success !== true || !Array.isArray(body.data)) throw new Error(typeof body?.error === 'string' ? body.error : 'Invoice data could not be loaded.')
  return body.data as T[]
}

export function StructuredInvoicesWorkspace() {
  const t = useTranslations('StructuredInvoices')
  const locale = useLocale()
  const [invoices, setInvoices] = useState<IssuedInvoice[]>([])
  const [sequences, setSequences] = useState<NumberSequence[]>([])
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [status, setStatus] = useState('')
  const [year, setYear] = useState(String(new Date().getFullYear())); const [firstNumber, setFirstNumber] = useState('1'); const [confirmed, setConfirmed] = useState(false)
  const [issueDate, setIssueDate] = useState(today()); const [supplyDate, setSupplyDate] = useState(today())
  const [buyerReference, setBuyerReference] = useState('')
  const [buyerElectronicAddressScheme, setBuyerElectronicAddressScheme] = useState<'0204' | '9930' | 'EM'>('0204'); const [buyerElectronicAddress, setBuyerElectronicAddress] = useState('')
  const [buyerName, setBuyerName] = useState(''); const [buyerStreet, setBuyerStreet] = useState(''); const [buyerPostalCode, setBuyerPostalCode] = useState(''); const [buyerCity, setBuyerCity] = useState(''); const [buyerCountry, setBuyerCountry] = useState('DE'); const [buyerVatId, setBuyerVatId] = useState('')
  const [correction, setCorrection] = useState<{ target: IssuedInvoice; template: CorrectionTemplate; issueDate: string; description: string; net: string; rate: string } | null>(null)
  const [paymentTerms, setPaymentTerms] = useState(''); const [paymentIban, setPaymentIban] = useState(''); const [lines, setLines] = useState<InvoiceFormLine[]>([newLine('line-1')]); const [requestKey, setRequestKey] = useState('')
  const totals = useMemo(() => { try { return calculateInvoiceTotals(lines) } catch { return { netAmountCents: 0, taxAmountCents: 0, grossAmountCents: 0 } } }, [lines])
  const money = (cents: number) => new Intl.NumberFormat(locale, { style: 'currency', currency: 'EUR' }).format(cents / 100)

  const load = useCallback(async () => {
    try {
      const [issued, configured] = await Promise.all([readList<IssuedInvoice>(await api.get('/api/tax/e-invoices')), readList<NumberSequence>(await api.get('/api/tax/e-invoices/number-sequences'))])
      setInvoices(issued); setSequences(configured)
    } catch (loadError) { setError(loadError instanceof Error ? loadError.message : t('loadFailed')) }
    finally { setLoading(false) }
  }, [t])
  useEffect(() => { setRequestKey(current => current || `invoice-ui-${crypto.randomUUID()}`); void load() }, [load])

  async function initializeSequence(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError(''); setStatus('')
    try {
      const response = await api.post('/api/tax/e-invoices', { action: 'configure-number-sequence', year: Number(year), firstUnusedNumber: Number(firstNumber), confirmedExistingSeries: confirmed })
      const body = await getJSON(response); if (!response.ok || body?.success !== true) throw new Error(body?.issues?.join(' ') || t('setupFailed'))
      setStatus(t('sequenceReady')); await load()
    } catch (setupError) { setError(setupError instanceof Error ? setupError.message : t('setupFailed')) }
    finally { setBusy(false) }
  }

  async function issue(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError(''); setStatus('')
    try {
      const request = buildStructuredInvoiceRequest({ requestKey, issueDate, supplyDate, buyerReference, buyerElectronicAddressScheme, buyerElectronicAddress, buyerName, buyerStreet, buyerPostalCode, buyerCity, buyerCountry, buyerVatId, paymentTerms, paymentIban, lines })
      const response = await api.post('/api/tax/e-invoices', request); const body = await getJSON(response)
      if (!response.ok || body?.success !== true) throw new Error(body?.issues?.join(' ') || t('issueFailed'))
      setStatus(t('issued', { number: body.data.invoiceNumber })); setBuyerReference(''); setBuyerElectronicAddress(''); setBuyerName(''); setBuyerStreet(''); setBuyerPostalCode(''); setBuyerCity(''); setBuyerVatId(''); setPaymentTerms(''); setLines([newLine()]); setRequestKey(`invoice-ui-${crypto.randomUUID()}`); await load()
    } catch (issueError) { setError(issueError instanceof Error ? issueError.message : t('issueFailed')) }
    finally { setBusy(false) }
  }

  async function beginCredit(target: IssuedInvoice) { setBusy(true); setError(''); try { const response = await api.get(`/api/tax/e-invoices/${target.id}/corrections`); const body = await getJSON(response); if (!response.ok || body?.success !== true) throw new Error(body?.issues?.join(' ') || t('creditFailed')); const template = body.data as CorrectionTemplate; setCorrection({ target, template, issueDate: today(), description: t('creditDescription', { number: target.invoiceNumber }), net: '', rate: String((template.data.lines[0]?.taxRateBasisPoints ?? 1900) / 100) }) } catch (reason) { setError(reason instanceof Error ? reason.message : t('creditFailed')) } finally { setBusy(false) } }
  async function issueCredit(event: FormEvent) { event.preventDefault(); if (!correction) return; setBusy(true); setError(''); setStatus(''); try { const netAmountCents = Math.round(Number(correction.net) * 100); const rateBasisPoints = Number(correction.rate) * 100; const taxAmountCents = Math.round(netAmountCents * rateBasisPoints / 10_000); const base = correction.template.data; const response = await api.post(`/api/tax/e-invoices/${correction.target.id}/corrections`, { kind: 'credit-note', requestKey: `credit-ui-${crypto.randomUUID()}`, issueDate: correction.issueDate, supplyDate: correction.issueDate, buyer: base.buyer, currency: base.currency, lines: [{ description: correction.description, quantity: 1, unitCode: base.lines[0]?.unitCode ?? 'C62', netAmountCents, taxRateBasisPoints: rateBasisPoints, taxCategoryCode: 'S' }], netAmountCents, taxAmountCents, grossAmountCents: netAmountCents + taxAmountCents, buyerReference: correction.template.buyerReference, buyerElectronicAddress: correction.template.buyerElectronicAddress, paymentTerms: correction.template.paymentTerms, paymentIban: correction.template.paymentIban }); const body = await getJSON(response); if (!response.ok || body?.success !== true) throw new Error(body?.issues?.join(' ') || t('creditFailed')); setStatus(t('credited', { original: correction.target.invoiceNumber, number: body.data.invoiceNumber })); setCorrection(null); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : t('creditFailed')) } finally { setBusy(false) } }

  const updateLine = (id: string, field: keyof InvoiceFormLine, value: string) => setLines(current => current.map(line => line.id === id ? { ...line, [field]: value } as InvoiceFormLine : line))
  if (loading) return <p>{t('loading')}</p>
  return <div className="container-fluid px-0"><header className="mb-4"><h1>{t('title')}</h1><p className="text-muted">{t('subtitle')}</p></header>
    {error && <div className="alert alert-danger" role="alert">{error}</div>}{status && <div className="alert alert-success" role="status">{status}</div>}
    <section className="card mb-4"><div className="card-body"><h2 className="h4">{t('numbering')}</h2><p>{sequences.length ? t('configured', { values: sequences.map(item => `${item.year}: ${item.nextValue}`).join(', ') }) : t('notConfigured')}</p><form className="row g-3 align-items-end" onSubmit={initializeSequence}><div className="col-sm-3"><label className="form-label" htmlFor="invoice-year">{t('invoiceYear')}</label><input className="form-control" id="invoice-year" type="number" min="2000" max="9999" value={year} onChange={event => setYear(event.target.value)} /></div><div className="col-sm-3"><label className="form-label" htmlFor="first-number">{t('firstNumber')}</label><input className="form-control" id="first-number" type="number" min="1" max="999999" value={firstNumber} onChange={event => setFirstNumber(event.target.value)} /></div><div className="col-sm-4"><div className="form-check"><input className="form-check-input" id="confirm-number" type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} /><label className="form-check-label" htmlFor="confirm-number">{t('confirmNumber')}</label></div></div><div className="col-sm-2"><button disabled={busy || !confirmed} className="btn btn-outline-primary" type="submit">{t('initialize')}</button></div></form></div></section>
    <section className="card mb-4"><div className="card-body"><h2 className="h4">{t('newInvoice')}</h2><form onSubmit={issue}>
      <div className="row g-3"><div className="col-sm-3"><label className="form-label" htmlFor="issue-date">{t('issueDate')}</label><input required className="form-control" id="issue-date" type="date" value={issueDate} onChange={event => setIssueDate(event.target.value)} /></div><div className="col-sm-3"><label className="form-label" htmlFor="supply-date">{t('supplyDate')}</label><input required className="form-control" id="supply-date" type="date" value={supplyDate} onChange={event => setSupplyDate(event.target.value)} /></div></div>
      <fieldset className="mt-3"><legend className="h5">{t('buyer')}</legend><div className="row g-3"><div className="col-md-6"><label className="form-label" htmlFor="buyer-reference">{t('buyerReference')}</label><input required className="form-control" id="buyer-reference" value={buyerReference} onChange={event => setBuyerReference(event.target.value)} /></div><div className="col-md-3"><label className="form-label" htmlFor="buyer-endpoint-scheme">{t('buyerEndpointScheme')}</label><select className="form-select" id="buyer-endpoint-scheme" value={buyerElectronicAddressScheme} onChange={event => setBuyerElectronicAddressScheme(event.target.value as '0204' | '9930' | 'EM')}><option value="0204">0204 – Leitweg-ID</option><option value="9930">9930 – German VAT ID</option><option value="EM">EM – Email</option></select></div><div className="col-md-3"><label className="form-label" htmlFor="buyer-endpoint">{t('buyerEndpoint')}</label><input required className="form-control" id="buyer-endpoint" value={buyerElectronicAddress} onChange={event => setBuyerElectronicAddress(event.target.value)} /></div><div className="col-md-6"><label className="form-label" htmlFor="buyer-name">{t('buyerName')}</label><input required className="form-control" id="buyer-name" value={buyerName} onChange={event => setBuyerName(event.target.value)} /></div><div className="col-md-6"><label className="form-label" htmlFor="buyer-street">{t('buyerStreet')}</label><input required className="form-control" id="buyer-street" value={buyerStreet} onChange={event => setBuyerStreet(event.target.value)} /></div><div className="col-sm-3"><label className="form-label" htmlFor="buyer-postal">{t('buyerPostal')}</label><input required className="form-control" id="buyer-postal" value={buyerPostalCode} onChange={event => setBuyerPostalCode(event.target.value)} /></div><div className="col-sm-3"><label className="form-label" htmlFor="buyer-city">{t('buyerCity')}</label><input required className="form-control" id="buyer-city" value={buyerCity} onChange={event => setBuyerCity(event.target.value)} /></div><div className="col-sm-3"><label className="form-label" htmlFor="buyer-country">{t('buyerCountry')}</label><input required className="form-control" id="buyer-country" maxLength={2} value={buyerCountry} onChange={event => setBuyerCountry(event.target.value)} /></div><div className="col-sm-3"><label className="form-label" htmlFor="buyer-vat">{t('buyerVat')}</label><input className="form-control" id="buyer-vat" value={buyerVatId} onChange={event => setBuyerVatId(event.target.value)} /></div></div></fieldset>
      <fieldset className="mt-4"><legend className="h5">{t('lines')}</legend>{lines.map((line, index) => <div className="row g-2 mb-3" key={line.id}><div className="col-md-5"><label className="form-label" htmlFor={`description-${line.id}`}>{t('description', { row: index + 1 })}</label><input required className="form-control" id={`description-${line.id}`} value={line.description} onChange={event => updateLine(line.id, 'description', event.target.value)} /></div><div className="col-md-2"><label className="form-label" htmlFor={`quantity-${line.id}`}>{t('quantity', { row: index + 1 })}</label><input required className="form-control" id={`quantity-${line.id}`} value={line.quantity} onChange={event => updateLine(line.id, 'quantity', event.target.value)} /></div><div className="col-md-1"><label className="form-label" htmlFor={`unit-${line.id}`}>{t('unit', { row: index + 1 })}</label><input required className="form-control" id={`unit-${line.id}`} value={line.unitCode} onChange={event => updateLine(line.id, 'unitCode', event.target.value)} /></div><div className="col-md-2"><label className="form-label" htmlFor={`net-${line.id}`}>{t('net', { row: index + 1 })}</label><input required className="form-control" id={`net-${line.id}`} inputMode="decimal" value={line.netAmount} onChange={event => updateLine(line.id, 'netAmount', event.target.value)} /></div><div className="col-md-1"><label className="form-label" htmlFor={`vat-${line.id}`}>{t('vat', { row: index + 1 })}</label><select className="form-select" id={`vat-${line.id}`} value={line.taxRate} onChange={event => updateLine(line.id, 'taxRate', event.target.value)}><option value="19">19%</option><option value="7">7%</option></select></div><div className="col-md-1 d-flex align-items-end"><button className="btn btn-outline-danger" type="button" aria-label={t('remove', { row: index + 1 })} disabled={lines.length === 1} onClick={() => setLines(current => current.filter(item => item.id !== line.id))}>×</button></div></div>)}<button className="btn btn-outline-secondary" type="button" onClick={() => setLines(current => [...current, newLine()])}>{t('addLine')}</button></fieldset>
      <div className="row g-3 mt-2"><div className="col-md-6"><label className="form-label" htmlFor="payment-terms">{t('paymentTerms')}</label><input required className="form-control" id="payment-terms" value={paymentTerms} onChange={event => setPaymentTerms(event.target.value)} /></div><div className="col-md-6"><label className="form-label" htmlFor="payment-iban">{t('iban')}</label><input required className="form-control" id="payment-iban" value={paymentIban} onChange={event => setPaymentIban(event.target.value)} /></div></div>
      <dl className="row mt-4"><dt className="col-sm-2">{t('netTotal')}</dt><dd className="col-sm-2">{money(totals.netAmountCents)}</dd><dt className="col-sm-2">{t('vatTotal')}</dt><dd className="col-sm-2">{money(totals.taxAmountCents)}</dd><dt className="col-sm-2">{t('grossTotal')}</dt><dd className="col-sm-2">{money(totals.grossAmountCents)}</dd></dl><p className="text-muted">{t('immutableWarning')}</p><button disabled={busy} className="btn btn-primary" type="submit">{t('issue')}</button>
    </form></div></section>
    {correction && <section className="card mb-4"><div className="card-body"><h2 className="h4">{t('newCredit', { number: correction.target.invoiceNumber })}</h2><form onSubmit={issueCredit}><div className="row g-3"><div className="col-md-3"><label className="form-label" htmlFor="credit-date">{t('issueDate')}</label><input required className="form-control" id="credit-date" type="date" value={correction.issueDate} onChange={event => setCorrection({ ...correction, issueDate: event.target.value })} /></div><div className="col-md-4"><label className="form-label" htmlFor="credit-description">{t('creditReason')}</label><input required className="form-control" id="credit-description" value={correction.description} onChange={event => setCorrection({ ...correction, description: event.target.value })} /></div><div className="col-md-3"><label className="form-label" htmlFor="credit-net">{t('creditNet')}</label><input required min="0.01" step="0.01" type="number" className="form-control" id="credit-net" value={correction.net} onChange={event => setCorrection({ ...correction, net: event.target.value })} /></div><div className="col-md-2"><label className="form-label" htmlFor="credit-rate">{t('vat', { row: 1 })}</label><select className="form-select" id="credit-rate" value={correction.rate} onChange={event => setCorrection({ ...correction, rate: event.target.value })}><option value="19">19%</option><option value="7">7%</option></select></div></div><button disabled={busy} className="btn btn-danger mt-3" type="submit">{t('issueCredit')}</button></form></div></section>}
    <section><h2 className="h4">{t('issuedInvoices')}</h2>{invoices.length ? <div className="table-responsive"><table className="table"><thead><tr><th>{t('number')}</th><th>{t('issueDate')}</th><th>{t('kind')}</th><th>{t('syntax')}</th><th>{t('actions')}</th></tr></thead><tbody>{invoices.map(invoice => <tr key={invoice.id}><td>{invoice.invoiceNumber}</td><td>{invoice.issueDate.slice(0, 10)}</td><td>{invoice.kind}</td><td>{invoice.syntax}</td><td><a className="me-3" target="_blank" rel="noreferrer" href={`/api/tax/e-invoices/${invoice.id}/rendering`}>{t('preview')}</a><a className="me-3" download href={`/api/documents/${invoice.documentId}/file`}>{t('download')}</a>{invoice.kind === 'invoice' && <button type="button" className="btn btn-sm btn-outline-danger" onClick={() => void beginCredit(invoice)}>{t('creditNote')}</button>}</td></tr>)}</tbody></table></div> : <p>{t('noneIssued')}</p>}</section>
  </div>
}
